IF OBJECT_ID(N'svo.LINES_CODE_COMBO_LOOKUP', 'U') IS NOT NULL
    DROP TABLE svo.LINES_CODE_COMBO_LOOKUP;
GO

CREATE TABLE svo.LINES_CODE_COMBO_LOOKUP
(
    CODE_COMBINATION_BK     BIGINT         NOT NULL,

    COMPANY_ID              VARCHAR(100)    NULL,
    COMPANY_DESC            VARCHAR(500)    NULL,

    COSTCENTER_ID           VARCHAR(100)    NULL,
    COSTCENTER_DESC         VARCHAR(500)    NULL,

    BUSINESSOFFERING_ID     VARCHAR(100)    NULL,
    BUSINESSOFFERING_DESC   VARCHAR(500)    NULL,

    ACCOUNT_ID              VARCHAR(100)    NULL,
    ACCOUNT_DESC            VARCHAR(500)    NULL,

    INDUSTRY_ID             VARCHAR(100)    NULL,
    INDUSTRY_DESC           VARCHAR(500)    NULL,

    INTERCOMPANY_ID         VARCHAR(100)    NULL,
    INTERCOMPANY_DESC       VARCHAR(500)    NULL
) ON FG_SilverMisc;
GO

CREATE UNIQUE INDEX IX_CODECOMBO_LKP
ON svo.LINES_CODE_COMBO_LOOKUP (CODE_COMBINATION_BK)
ON FG_SilverMisc;
GO