/* =========================================================
   usp_Load_D_BUSINESS_OFFERING
   SCD2 incremental load. CodeCombo dim from GL value set hierarchy.
   Watermark filter, expire changed rows, insert new current rows.
   Idempotent: safe to retry same watermark range.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_D_BUSINESS_OFFERING
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.D_BUSINESS_OFFERING',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000)  = NULL,

        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @LoadDttm       DATETIME2(0)   = SYSDATETIME(),
        @HighDate       DATE           = '9999-12-31',

        @LastWatermark  DATETIME2(7),
        @MaxWatermark   DATETIME2(7)   = NULL,

        @RowInserted    INT            = 0,
        @RowExpired     INT            = 0,
        @RowUpdated     INT            = 0;

    BEGIN TRY
        SELECT @LastWatermark = w.LAST_WATERMARK
        FROM etl.ETL_WATERMARK w
        WHERE w.TABLE_NAME = @TargetObject;

        IF @LastWatermark IS NULL
            SET @LastWatermark = '1900-01-01';

        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED');

        SET @RunId = SCOPE_IDENTITY();

        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_OFFERING_ID' AND object_id = OBJECT_ID('svo.D_BUSINESS_OFFERING'))
        BEGIN
            DROP INDEX UX_D_BUSINESS_OFFERING_ID ON svo.D_BUSINESS_OFFERING;
        END;

        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_OFFERING_BK_CURR' AND object_id = OBJECT_ID('svo.D_BUSINESS_OFFERING'))
        BEGIN
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_OFFERING_BK_CURR
            ON svo.D_BUSINESS_OFFERING (BUSINESS_OFFERING_ID)
            WHERE CURR_IND = 'Y'
            ON FG_SilverDim;
        END;

        IF NOT EXISTS (SELECT 1 FROM svo.D_BUSINESS_OFFERING WHERE BUSINESS_OFFERING_SK = 0)
        BEGIN
            SET IDENTITY_INSERT svo.D_BUSINESS_OFFERING ON;

            INSERT INTO svo.D_BUSINESS_OFFERING
            (BUSINESS_OFFERING_SK, BUSINESS_OFFERING_ID, BUSINESS_OFFERING_LVL1_CODE, BUSINESS_OFFERING_LVL1_DESC,
             BUSINESS_OFFERING_LVL2_CODE, BUSINESS_OFFERING_LVL2_DESC, BUSINESS_OFFERING_LVL3_CODE, BUSINESS_OFFERING_LVL3_DESC,
             BUSINESS_OFFERING_LVL4_CODE, BUSINESS_OFFERING_LVL4_DESC, BUSINESS_OFFERING_LVL5_CODE, BUSINESS_OFFERING_LVL5_DESC,
             BUSINESS_OFFERING_DISTANCE, BUSINESS_OFFERING_CATEGORY, BUSINESS_OFFERING_ENABLED_FLAG,
             START_DATE_ACTIVE, END_DATE_ACTIVE, CREATED_BY, CREATION_DATE, BZ_LOAD_DATE, SV_LOAD_DATE,
             EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND)
            VALUES
            (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',
             0,'Missing',NULL,'0001-01-01','9999-12-31','SYSTEM','2025-10-18',CAST(GETDATE() AS DATE),CAST(GETDATE() AS DATE),
             @AsOfDate,@HighDate,@LoadDttm,@LoadDttm,'Y');

            SET IDENTITY_INSERT svo.D_BUSINESS_OFFERING OFF;
        END;

        IF OBJECT_ID('tempdb..#src') IS NOT NULL DROP TABLE #src;

        SELECT
            s.BUSINESS_OFFERING_ID,
            s.BUSINESS_OFFERING_LVL1_CODE, s.BUSINESS_OFFERING_LVL1_DESC,
            s.BUSINESS_OFFERING_LVL2_CODE, s.BUSINESS_OFFERING_LVL2_DESC,
            s.BUSINESS_OFFERING_LVL3_CODE, s.BUSINESS_OFFERING_LVL3_DESC,
            s.BUSINESS_OFFERING_LVL4_CODE, s.BUSINESS_OFFERING_LVL4_DESC,
            s.BUSINESS_OFFERING_LVL5_CODE, s.BUSINESS_OFFERING_LVL5_DESC,
            s.BUSINESS_OFFERING_DISTANCE, s.BUSINESS_OFFERING_CATEGORY, s.BUSINESS_OFFERING_ENABLED_FLAG,
            s.START_DATE_ACTIVE, s.END_DATE_ACTIVE, s.CREATED_BY, s.CREATION_DATE,
            s.BZ_LOAD_DATE, s.SV_LOAD_DATE, s.SourceAddDateTime
        INTO #src
        FROM
        (
            SELECT
                ISNULL(LTRIM(RTRIM(lvl5.VALUE)),'-1') AS BUSINESS_OFFERING_ID,
                COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL1_CODE,
                COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL1_DESC,
                COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL2_CODE,
                COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL2_DESC,
                COALESCE(h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL3_CODE,
                COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL3_DESC,
                COALESCE(h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL4_CODE,
                COALESCE(lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL4_DESC,
                lvl5.VALUE AS BUSINESS_OFFERING_LVL5_CODE,
                lvl5.DESCRIPTION AS BUSINESS_OFFERING_LVL5_DESC,
                0 AS BUSINESS_OFFERING_DISTANCE,
                lvl5.ATTRIBUTECATEGORY AS BUSINESS_OFFERING_CATEGORY,
                lvl5.ENABLEDFLAG AS BUSINESS_OFFERING_ENABLED_FLAG,
                ISNULL(lvl5.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
                ISNULL(lvl5.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
                lvl5.CREATEDBY AS CREATED_BY,
                CAST(lvl5.CREATIONDATE AS DATE) AS CREATION_DATE,
                COALESCE(CAST(h1.AddDateTime AS DATE), CAST(GETDATE() AS DATE)) AS BZ_LOAD_DATE,
                CAST(GETDATE() AS DATE) AS SV_LOAD_DATE,
                (SELECT MAX(v.dt) FROM (VALUES (h1.AddDateTime),(ver1.AddDateTime),(lvl1.AddDateTime),(lvl2.AddDateTime),(lvl3.AddDateTime),(lvl4.AddDateTime),(lvl5.AddDateTime)) v(dt)) AS SourceAddDateTime,
                ROW_NUMBER() OVER (PARTITION BY ISNULL(LTRIM(RTRIM(lvl5.VALUE)),'-1') ORDER BY (SELECT MAX(v.dt) FROM (VALUES (h1.AddDateTime),(ver1.AddDateTime),(lvl1.AddDateTime),(lvl2.AddDateTime),(lvl3.AddDateTime),(lvl4.AddDateTime),(lvl5.AddDateTime)) v(dt)) DESC) AS rn
            FROM bzo.GL_SegmentValueHierarchyExtractPVO h1
            INNER JOIN bzo.GL_FndTreeAndVersionVO ver1 ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'BUSINESS OFFERING LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP28PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
            RIGHT JOIN bzo.GL_ValueSetValuesPVO lvl5 ON lvl5.VALUE = h1.DEP0PK1VALUE AND lvl5.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
            WHERE lvl5.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR' AND lvl5.SUMMARYFLAG = 'N'
              AND (h1.AddDateTime > @LastWatermark OR ver1.AddDateTime > @LastWatermark OR lvl1.AddDateTime > @LastWatermark OR lvl2.AddDateTime > @LastWatermark OR lvl3.AddDateTime > @LastWatermark OR lvl4.AddDateTime > @LastWatermark OR lvl5.AddDateTime > @LastWatermark)
        ) s
        WHERE s.rn = 1;

        SELECT @MaxWatermark = MAX(SourceAddDateTime) FROM #src;

        UPDATE tgt
        SET tgt.END_DATE = DATEADD(DAY, -1, @AsOfDate), tgt.CURR_IND = 'N', tgt.UDT_DATE = @LoadDttm
        FROM svo.D_BUSINESS_OFFERING tgt
        INNER JOIN #src src ON src.BUSINESS_OFFERING_ID = tgt.BUSINESS_OFFERING_ID
        WHERE tgt.CURR_IND = 'Y'
          AND (
                ISNULL(tgt.BUSINESS_OFFERING_LVL1_CODE,'') <> ISNULL(src.BUSINESS_OFFERING_LVL1_CODE,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL1_DESC,'') <> ISNULL(src.BUSINESS_OFFERING_LVL1_DESC,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL2_CODE,'') <> ISNULL(src.BUSINESS_OFFERING_LVL2_CODE,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL2_DESC,'') <> ISNULL(src.BUSINESS_OFFERING_LVL2_DESC,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL3_CODE,'') <> ISNULL(src.BUSINESS_OFFERING_LVL3_CODE,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL3_DESC,'') <> ISNULL(src.BUSINESS_OFFERING_LVL3_DESC,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL4_CODE,'') <> ISNULL(src.BUSINESS_OFFERING_LVL4_CODE,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL4_DESC,'') <> ISNULL(src.BUSINESS_OFFERING_LVL4_DESC,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL5_CODE,'') <> ISNULL(src.BUSINESS_OFFERING_LVL5_CODE,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_LVL5_DESC,'') <> ISNULL(src.BUSINESS_OFFERING_LVL5_DESC,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_DISTANCE, -999) <> ISNULL(src.BUSINESS_OFFERING_DISTANCE, -999)
             OR ISNULL(tgt.BUSINESS_OFFERING_CATEGORY,'') <> ISNULL(src.BUSINESS_OFFERING_CATEGORY,'')
             OR ISNULL(tgt.BUSINESS_OFFERING_ENABLED_FLAG,'') <> ISNULL(src.BUSINESS_OFFERING_ENABLED_FLAG,'')
             OR tgt.START_DATE_ACTIVE <> src.START_DATE_ACTIVE
             OR tgt.END_DATE_ACTIVE <> src.END_DATE_ACTIVE
             OR ISNULL(tgt.CREATED_BY,'') <> ISNULL(src.CREATED_BY,'')
             OR ISNULL(tgt.CREATION_DATE,'1900-01-01') <> ISNULL(src.CREATION_DATE,'1900-01-01')
          );

        SET @RowExpired = @@ROWCOUNT;

        INSERT INTO svo.D_BUSINESS_OFFERING
        (BUSINESS_OFFERING_ID, BUSINESS_OFFERING_LVL1_CODE, BUSINESS_OFFERING_LVL1_DESC,
         BUSINESS_OFFERING_LVL2_CODE, BUSINESS_OFFERING_LVL2_DESC, BUSINESS_OFFERING_LVL3_CODE, BUSINESS_OFFERING_LVL3_DESC,
         BUSINESS_OFFERING_LVL4_CODE, BUSINESS_OFFERING_LVL4_DESC, BUSINESS_OFFERING_LVL5_CODE, BUSINESS_OFFERING_LVL5_DESC,
         BUSINESS_OFFERING_DISTANCE, BUSINESS_OFFERING_CATEGORY, BUSINESS_OFFERING_ENABLED_FLAG,
         START_DATE_ACTIVE, END_DATE_ACTIVE, CREATED_BY, CREATION_DATE, BZ_LOAD_DATE, SV_LOAD_DATE,
         EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND)
        SELECT
            src.BUSINESS_OFFERING_ID, src.BUSINESS_OFFERING_LVL1_CODE, src.BUSINESS_OFFERING_LVL1_DESC,
            src.BUSINESS_OFFERING_LVL2_CODE, src.BUSINESS_OFFERING_LVL2_DESC, src.BUSINESS_OFFERING_LVL3_CODE, src.BUSINESS_OFFERING_LVL3_DESC,
            src.BUSINESS_OFFERING_LVL4_CODE, src.BUSINESS_OFFERING_LVL4_DESC, src.BUSINESS_OFFERING_LVL5_CODE, src.BUSINESS_OFFERING_LVL5_DESC,
            src.BUSINESS_OFFERING_DISTANCE, src.BUSINESS_OFFERING_CATEGORY, src.BUSINESS_OFFERING_ENABLED_FLAG,
            src.START_DATE_ACTIVE, src.END_DATE_ACTIVE, src.CREATED_BY, src.CREATION_DATE, src.BZ_LOAD_DATE, src.SV_LOAD_DATE,
            @AsOfDate, @HighDate, @LoadDttm, @LoadDttm, 'Y'
        FROM #src src
        LEFT JOIN svo.D_BUSINESS_OFFERING tgt ON tgt.BUSINESS_OFFERING_ID = src.BUSINESS_OFFERING_ID AND tgt.CURR_IND = 'Y'
        WHERE tgt.BUSINESS_OFFERING_ID IS NULL;

        SET @RowInserted = @@ROWCOUNT;

        IF @MaxWatermark IS NOT NULL
        BEGIN
            UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = @MaxWatermark, UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;
        END

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg  = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        ;THROW;
    END CATCH
END;
GO
