/* =========================================================
   usp_Load_D_GL_HEADER
   SCD2 incremental load. Source: bzo.GL_JournalHeaderExtractPVO
   Watermark: AddDateTime (or LAST_UPDATE_DATE fallback). Grain: JE_HEADER_ID.
   Expire changed rows, insert new current rows. Plug row SK=0 if missing.
   Joins: D_LEDGER (CURR_IND='Y'), bzo GL_JournalCategory/JournalSource.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_D_GL_HEADER
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.D_GL_HEADER',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000) = NULL,
        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @LoadDttm       DATETIME2(0)   = SYSDATETIME(),
        @HighDate       DATE           = '9999-12-31',
        @LastWatermark  DATETIME2(7),
        @MaxWatermark   DATETIME2(7)   = NULL,
        @RowInserted    INT            = 0,
        @RowExpired     INT            = 0,
        @RowUpdated     INT            = 0;

    BEGIN TRY
        SELECT @LastWatermark = w.LAST_WATERMARK
        FROM etl.ETL_WATERMARK w
        WHERE w.TABLE_NAME = @TargetObject;

        IF @LastWatermark IS NULL
            SET @LastWatermark = '1900-01-01';

        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED');

        SET @RunId = SCOPE_IDENTITY();
        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        IF NOT EXISTS (SELECT 1 FROM svo.D_GL_HEADER WHERE GL_HEADER_SK = 0)
        BEGIN
            SET IDENTITY_INSERT svo.D_GL_HEADER ON;
            INSERT INTO svo.D_GL_HEADER
            (GL_HEADER_SK, JE_HEADER_ID, LEDGER_SK, POSTED_DATE_SK, DEFAULT_EFFECTIVE_DATE_SK, GL_HEADER_NAME, GL_HEADER_STATUS, GL_HEADER_DESCRIPTION,
             ACCRUAL_REV_CHANGESIGN_FLAG, ACTUAL_FLAG, BALANCED_JE_FLAG, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE,
             EXTERNAL_REFERENCE, JE_BATCH_ID, CATEGORY, JE_SOURCE, MULTI_CURRENCY_FLAG, POST_CURRENCY_CODE, POST_MULTI_CURRENCY_FLAG,
             RUNNING_TOTAL_CR, RUNNING_TOTAL_DR, RUNNING_TOTAL_ACCOUNTED_CR, RUNNING_TOTAL_ACCOUNTED_DR, CR_DR_VARIANCE,
             DATE_CREATED, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
             EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND, BZ_LOAD_DATE, SV_LOAD_DATE)
            VALUES
            (0, -1, 0, 0, 0, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0001-01-01', 0, 'NULL', 'NULL', -1, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL',
             0, 0, 0, 0, 0, '0001-01-01', 'NULL', '0001-01-01', '0001-01-01', 'NULL', 'NULL', @AsOfDate, @HighDate, @LoadDttm, @LoadDttm, 'Y', '0001-01-01', CAST(GETDATE() AS DATE));
            SET IDENTITY_INSERT svo.D_GL_HEADER OFF;
        END;

        IF OBJECT_ID('tempdb..#src') IS NOT NULL DROP TABLE #src;

        SELECT
            H.JEHEADERID AS JE_HEADER_ID,
            ISNULL(LGR.LEDGER_SK, 0) AS LEDGER_SK,
            ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, H.GLJEHEADERSPOSTEDDATE), 112) AS INT), 0) AS POSTED_DATE_SK,
            ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, H.GLJEHEADERSDEFAULTEFFECTIVEDATE), 112) AS INT), 0) AS DEFAULT_EFFECTIVE_DATE_SK,
            ISNULL(H.GLJEHEADERSNAME, 'NULL') AS GL_HEADER_NAME,
            ISNULL(H.GLJEHEADERSSTATUS, 'NULL') AS GL_HEADER_STATUS,
            ISNULL(H.GLJEHEADERSDESCRIPTION, 'NULL') AS GL_HEADER_DESCRIPTION,
            ISNULL(H.GLJEHEADERSACCRUALREVCHANGESIGNFLAG, 'NULL') AS ACCRUAL_REV_CHANGESIGN_FLAG,
            ISNULL(H.GLJEHEADERSACTUALFLAG, 'NULL') AS ACTUAL_FLAG,
            ISNULL(H.GLJEHEADERSBALANCEDJEFLAG, 'NULL') AS BALANCED_JE_FLAG,
            ISNULL(H.GLJEHEADERSCURRENCYCODE, 'NULL') AS CURRENCY_CODE,
            CAST(ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONDATE, '1900-01-01') AS DATE) AS CURRENCY_CONVERSION_DATE,
            ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONRATE, 0) AS CURRENCY_CONVERSION_RATE,
            ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONTYPE, 'NULL') AS CURRENCY_CONVERSION_TYPE,
            ISNULL(H.GLJEHEADERSEXTERNALREFERENCE, 'NULL') AS EXTERNAL_REFERENCE,
            ISNULL(H.GLJEHEADERSJEBATCHID, 0) AS JE_BATCH_ID,
            ISNULL(cat.JournalCategoryJeCategoryKey, 'NULL') AS CATEGORY,
            ISNULL(src.JournalSourceJeSourceKey, 'NULL') AS JE_SOURCE,
            ISNULL(H.GLJEHEADERSMULTICURRENCYFLAG, 'NULL') AS MULTI_CURRENCY_FLAG,
            ISNULL(H.GLJEHEADERSPOSTCURRENCYCODE, 'NULL') AS POST_CURRENCY_CODE,
            ISNULL(H.GLJEHEADERSPOSTMULTICURRENCYFLAG, 'NULL') AS POST_MULTI_CURRENCY_FLAG,
            CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALCR, 0) AS FLOAT) AS RUNNING_TOTAL_CR,
            CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALDR, 0) AS FLOAT) AS RUNNING_TOTAL_DR,
            CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_CR,
            CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_DR,
            CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT) - CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS CR_DR_VARIANCE,
            CAST(ISNULL(H.GLJEHEADERSDATECREATED, '1900-01-01') AS DATE) AS DATE_CREATED,
            ISNULL(H.GLJEHEADERSCREATEDBY, 'NULL') AS CREATED_BY,
            CAST(ISNULL(H.GLJEHEADERSCREATIONDATE, '1900-01-01') AS DATE) AS CREATION_DATE,
            CAST(ISNULL(H.GLJEHEADERSLASTUPDATEDATE, '1900-01-01') AS DATE) AS LAST_UPDATE_DATE,
            ISNULL(H.GLJEHEADERSLASTUPDATELOGIN, 'NULL') AS LAST_UPDATE_LOGIN,
            ISNULL(H.GLJEHEADERSLASTUPDATEDBY, 'NULL') AS LAST_UPDATED_BY,
            CAST(COALESCE(H.AddDateTime, H.GLJEHEADERSLASTUPDATEDATE, GETDATE()) AS DATE) AS BZ_LOAD_DATE,
            CAST(GETDATE() AS DATE) AS SV_LOAD_DATE,
            COALESCE(H.AddDateTime, CAST(H.GLJEHEADERSLASTUPDATEDATE AS DATETIME2(7)), SYSDATETIME()) AS SourceAddDateTime
        INTO #src
        FROM (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY H.JEHEADERID ORDER BY COALESCE(H.AddDateTime, CAST(H.GLJEHEADERSLASTUPDATEDATE AS DATETIME2(7)), SYSDATETIME()) DESC) AS rn
            FROM bzo.GL_JournalHeaderExtractPVO H
            WHERE COALESCE(H.AddDateTime, CAST(H.GLJEHEADERSLASTUPDATEDATE AS DATETIME2(7)), '1900-01-01') > @LastWatermark
        ) H
        LEFT JOIN svo.D_LEDGER AS LGR ON LGR.LEDGER_ID = H.GLJEHEADERSLEDGERID AND LGR.CURR_IND = 'Y'
        LEFT JOIN bzo.GL_JournalCategoryExtractPVO cat ON H.GlJeHeadersJeCategory = cat.JournalCategoryJeCategoryName
        LEFT JOIN bzo.GL_JournalSourceExtractPVO src ON H.GlJeHeadersJeSource = src.JournalSourceJeSourceName
        WHERE H.rn = 1;

        SELECT @MaxWatermark = MAX(SourceAddDateTime) FROM #src;

        UPDATE tgt
        SET tgt.END_DATE = DATEADD(DAY, -1, @AsOfDate), tgt.CURR_IND = 'N', tgt.UDT_DATE = @LoadDttm
        FROM svo.D_GL_HEADER tgt
        INNER JOIN #src src ON src.JE_HEADER_ID = tgt.JE_HEADER_ID
        WHERE tgt.CURR_IND = 'Y'
          AND (
              ISNULL(tgt.LEDGER_SK, 0) <> ISNULL(src.LEDGER_SK, 0)
              OR ISNULL(tgt.GL_HEADER_NAME, '') <> ISNULL(src.GL_HEADER_NAME, '')
              OR ISNULL(tgt.GL_HEADER_STATUS, '') <> ISNULL(src.GL_HEADER_STATUS, '')
              OR ISNULL(tgt.GL_HEADER_DESCRIPTION, '') <> ISNULL(src.GL_HEADER_DESCRIPTION, '')
              OR ISNULL(tgt.POSTED_DATE_SK, 0) <> ISNULL(src.POSTED_DATE_SK, 0)
              OR ISNULL(tgt.DEFAULT_EFFECTIVE_DATE_SK, 0) <> ISNULL(src.DEFAULT_EFFECTIVE_DATE_SK, 0)
          );

        SET @RowExpired = @@ROWCOUNT;

        INSERT INTO svo.D_GL_HEADER
        (JE_HEADER_ID, LEDGER_SK, POSTED_DATE_SK, DEFAULT_EFFECTIVE_DATE_SK, GL_HEADER_NAME, GL_HEADER_STATUS, GL_HEADER_DESCRIPTION,
         ACCRUAL_REV_CHANGESIGN_FLAG, ACTUAL_FLAG, BALANCED_JE_FLAG, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE,
         EXTERNAL_REFERENCE, JE_BATCH_ID, CATEGORY, JE_SOURCE, MULTI_CURRENCY_FLAG, POST_CURRENCY_CODE, POST_MULTI_CURRENCY_FLAG,
         RUNNING_TOTAL_CR, RUNNING_TOTAL_DR, RUNNING_TOTAL_ACCOUNTED_CR, RUNNING_TOTAL_ACCOUNTED_DR, CR_DR_VARIANCE,
         DATE_CREATED, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
         EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND, BZ_LOAD_DATE, SV_LOAD_DATE)
        SELECT
            src.JE_HEADER_ID, src.LEDGER_SK, src.POSTED_DATE_SK, src.DEFAULT_EFFECTIVE_DATE_SK, src.GL_HEADER_NAME, src.GL_HEADER_STATUS, src.GL_HEADER_DESCRIPTION,
            src.ACCRUAL_REV_CHANGESIGN_FLAG, src.ACTUAL_FLAG, src.BALANCED_JE_FLAG, src.CURRENCY_CODE, src.CURRENCY_CONVERSION_DATE, src.CURRENCY_CONVERSION_RATE, src.CURRENCY_CONVERSION_TYPE,
            src.EXTERNAL_REFERENCE, src.JE_BATCH_ID, src.CATEGORY, src.JE_SOURCE, src.MULTI_CURRENCY_FLAG, src.POST_CURRENCY_CODE, src.POST_MULTI_CURRENCY_FLAG,
            src.RUNNING_TOTAL_CR, src.RUNNING_TOTAL_DR, src.RUNNING_TOTAL_ACCOUNTED_CR, src.RUNNING_TOTAL_ACCOUNTED_DR, src.CR_DR_VARIANCE,
            src.DATE_CREATED, src.CREATED_BY, src.CREATION_DATE, src.LAST_UPDATE_DATE, src.LAST_UPDATE_LOGIN, src.LAST_UPDATED_BY,
            @AsOfDate, @HighDate, @LoadDttm, @LoadDttm, 'Y', src.BZ_LOAD_DATE, src.SV_LOAD_DATE
        FROM #src src
        LEFT JOIN svo.D_GL_HEADER tgt ON tgt.JE_HEADER_ID = src.JE_HEADER_ID AND tgt.CURR_IND = 'Y'
        WHERE tgt.JE_HEADER_ID IS NULL;

        SET @RowInserted = @@ROWCOUNT;

        IF @MaxWatermark IS NOT NULL
            UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = @MaxWatermark, UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        ;THROW;
    END CATCH
END;
GO
