/* =========================================================
   usp_Load_D_COMPANY
   Type 6 SCD incremental load. CodeCombo dim from GL value set hierarchy.
   HISTORIC_*_LVL*_CODE and HISTORIC_*_LVL*_DESC store previous hierarchy values when a change creates a new version.
   Watermark filter, expire changed rows, insert new current rows. Idempotent.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_D_COMPANY
    @BatchId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.D_COMPANY',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000) = NULL,

        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @LoadDttm       DATETIME2(0)   = SYSDATETIME(),
        @HighDate       DATE           = '9999-12-31',

        @LastWatermark  DATETIME2(7),
        @MaxWatermark   DATETIME2(7)   = NULL,

        @RowInserted    INT            = 0,
        @RowExpired     INT            = 0,
        @RowUpdated     INT            = 0,
        @TableBridgeID  INT            = NULL;

    SELECT @TableBridgeID = TableBridgeID FROM meta.MedallionTableBridge WHERE targettable = N'GL_SegmentValueHierarchyExtractPVO';

    BEGIN TRY
        SELECT @LastWatermark = w.LAST_WATERMARK
        FROM etl.ETL_WATERMARK w
        WHERE w.TABLE_NAME = @TargetObject;

        IF @LastWatermark IS NULL
            SET @LastWatermark = '1900-01-01';

        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS, BATCH_ID, TABLE_BRIDGE_ID)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED', ISNULL(@BatchId, -1), ISNULL(@TableBridgeID, -1));

        SET @RunId = SCOPE_IDENTITY();

        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_ID' AND object_id = OBJECT_ID('svo.D_COMPANY'))
        BEGIN
            DROP INDEX UX_D_COMPANY_ID ON svo.D_COMPANY;
        END;

        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_BK_CURR' AND object_id = OBJECT_ID('svo.D_COMPANY'))
        BEGIN
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_COMPANY_BK_CURR
            ON svo.D_COMPANY (COMPANY_ID)
            WHERE CURR_IND = 'Y'
            ON FG_SilverDim;
        END;

        IF NOT EXISTS (SELECT 1 FROM svo.D_COMPANY WHERE COMPANY_SK = 0)
        BEGIN
            SET IDENTITY_INSERT svo.D_COMPANY ON;

            INSERT INTO svo.D_COMPANY
            (COMPANY_SK, COMPANY_ID, COMPANY_LVL1_CODE, COMPANY_LVL1_DESC, COMPANY_LVL2_CODE, COMPANY_LVL2_DESC,
             COMPANY_LVL3_CODE, COMPANY_LVL3_DESC, COMPANY_LVL4_CODE, COMPANY_LVL4_DESC, COMPANY_LVL5_CODE, COMPANY_LVL5_DESC,
             COMPANY_LVL6_CODE, COMPANY_LVL6_DESC, COMPANY_LVL7_CODE, COMPANY_LVL7_DESC,
             COMPANY_DISTANCE, COMPANY_CATEGORY, COMPANY_ENABLED_FLAG, START_DATE_ACTIVE, END_DATE_ACTIVE,
             CREATED_BY, CREATION_DATE,
             HISTORIC_COMPANY_LVL1_CODE, HISTORIC_COMPANY_LVL1_DESC, HISTORIC_COMPANY_LVL2_CODE, HISTORIC_COMPANY_LVL2_DESC,
             HISTORIC_COMPANY_LVL3_CODE, HISTORIC_COMPANY_LVL3_DESC, HISTORIC_COMPANY_LVL4_CODE, HISTORIC_COMPANY_LVL4_DESC,
             HISTORIC_COMPANY_LVL5_CODE, HISTORIC_COMPANY_LVL5_DESC, HISTORIC_COMPANY_LVL6_CODE, HISTORIC_COMPANY_LVL6_DESC,
             HISTORIC_COMPANY_LVL7_CODE, HISTORIC_COMPANY_LVL7_DESC,
             BZ_LOAD_DATE, SV_LOAD_DATE, EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND)
            VALUES
            (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',
             0,'Missing',NULL,'0001-01-01','9999-12-31','SYSTEM','2025-10-18',
             '-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',
             GETDATE(),GETDATE(),@AsOfDate,@HighDate,@LoadDttm,@LoadDttm,'Y');

            SET IDENTITY_INSERT svo.D_COMPANY OFF;
        END;

        IF OBJECT_ID('tempdb..#src') IS NOT NULL DROP TABLE #src;

        SELECT
            s.COMPANY_ID,
            s.COMPANY_LVL1_CODE, s.COMPANY_LVL1_DESC, s.COMPANY_LVL2_CODE, s.COMPANY_LVL2_DESC,
            s.COMPANY_LVL3_CODE, s.COMPANY_LVL3_DESC, s.COMPANY_LVL4_CODE, s.COMPANY_LVL4_DESC,
            s.COMPANY_LVL5_CODE, s.COMPANY_LVL5_DESC, s.COMPANY_LVL6_CODE, s.COMPANY_LVL6_DESC,
            s.COMPANY_LVL7_CODE, s.COMPANY_LVL7_DESC, s.COMPANY_DISTANCE, s.COMPANY_CATEGORY, s.COMPANY_ENABLED_FLAG,
            s.START_DATE_ACTIVE, s.END_DATE_ACTIVE, s.CREATED_BY, s.CREATION_DATE, s.BZ_LOAD_DATE, s.SV_LOAD_DATE, s.SourceAddDateTime
        INTO #src
        FROM
        (
            SELECT
                ISNULL(LTRIM(RTRIM(lvl7.VALUE)),'-1') AS COMPANY_ID,
                COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL1_CODE,
                COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL1_DESC,
                COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL2_CODE,
                COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL2_DESC,
                COALESCE(h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL3_CODE,
                COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL3_DESC,
                COALESCE(h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL4_CODE,
                COALESCE(lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL4_DESC,
                COALESCE(h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL5_CODE,
                COALESCE(lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL5_DESC,
                COALESCE(h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL6_CODE,
                COALESCE(lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL6_DESC,
                lvl7.VALUE AS COMPANY_LVL7_CODE, lvl7.DESCRIPTION AS COMPANY_LVL7_DESC,
                0 AS COMPANY_DISTANCE, lvl7.ATTRIBUTECATEGORY AS COMPANY_CATEGORY, lvl7.ENABLEDFLAG AS COMPANY_ENABLED_FLAG,
                ISNULL(lvl7.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE, ISNULL(lvl7.ENDDATEACTIVE, '9999-12-31') AS END_DATE_ACTIVE,
                lvl7.CREATEDBY AS CREATED_BY, CAST(lvl7.CREATIONDATE AS DATE) AS CREATION_DATE,
                COALESCE(CAST(h1.AddDateTime AS DATETIME), GETDATE()) AS BZ_LOAD_DATE, GETDATE() AS SV_LOAD_DATE,
                (SELECT MAX(v.dt) FROM (VALUES (h1.AddDateTime),(ver1.AddDateTime),(lvl1.AddDateTime),(lvl2.AddDateTime),(lvl3.AddDateTime),(lvl4.AddDateTime),(lvl5.AddDateTime),(lvl6.AddDateTime),(lvl7.AddDateTime)) v(dt)) AS SourceAddDateTime,
                ROW_NUMBER() OVER (PARTITION BY ISNULL(LTRIM(RTRIM(lvl7.VALUE)),'-1') ORDER BY (SELECT MAX(v.dt) FROM (VALUES (h1.AddDateTime),(ver1.AddDateTime),(lvl1.AddDateTime),(lvl2.AddDateTime),(lvl3.AddDateTime),(lvl4.AddDateTime),(lvl5.AddDateTime),(lvl6.AddDateTime),(lvl7.AddDateTime)) v(dt)) DESC) AS rn
            FROM bzo.GL_SegmentValueHierarchyExtractPVO h1
            INNER JOIN bzo.GL_FndTreeAndVersionVO ver1 ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP28PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl5 ON lvl5.VALUE = h1.DEP27PK1VALUE AND lvl5.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            INNER JOIN bzo.GL_ValueSetValuesPVO lvl6 ON lvl6.VALUE = h1.DEP26PK1VALUE AND lvl6.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            RIGHT JOIN bzo.GL_ValueSetValuesPVO lvl7 ON lvl7.VALUE = h1.DEP0PK1VALUE AND lvl7.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
            WHERE lvl7.ATTRIBUTECATEGORY = 'COMPANY LAMAR' AND lvl7.SUMMARYFLAG = 'N'
              AND (h1.AddDateTime > @LastWatermark OR ver1.AddDateTime > @LastWatermark OR lvl1.AddDateTime > @LastWatermark OR lvl2.AddDateTime > @LastWatermark OR lvl3.AddDateTime > @LastWatermark OR lvl4.AddDateTime > @LastWatermark OR lvl5.AddDateTime > @LastWatermark OR lvl6.AddDateTime > @LastWatermark OR lvl7.AddDateTime > @LastWatermark)
        ) s
        WHERE s.rn = 1;

        SELECT @MaxWatermark = MAX(SourceAddDateTime) FROM #src;

        UPDATE tgt
        SET tgt.END_DATE = DATEADD(DAY, -1, @AsOfDate), tgt.CURR_IND = 'N', tgt.UDT_DATE = @LoadDttm
        FROM svo.D_COMPANY tgt
        INNER JOIN #src src ON src.COMPANY_ID = tgt.COMPANY_ID
        WHERE tgt.CURR_IND = 'Y'
          AND (
                ISNULL(tgt.COMPANY_LVL1_CODE,'') <> ISNULL(src.COMPANY_LVL1_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL1_DESC,'') <> ISNULL(src.COMPANY_LVL1_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL2_CODE,'') <> ISNULL(src.COMPANY_LVL2_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL2_DESC,'') <> ISNULL(src.COMPANY_LVL2_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL3_CODE,'') <> ISNULL(src.COMPANY_LVL3_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL3_DESC,'') <> ISNULL(src.COMPANY_LVL3_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL4_CODE,'') <> ISNULL(src.COMPANY_LVL4_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL4_DESC,'') <> ISNULL(src.COMPANY_LVL4_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL5_CODE,'') <> ISNULL(src.COMPANY_LVL5_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL5_DESC,'') <> ISNULL(src.COMPANY_LVL5_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL6_CODE,'') <> ISNULL(src.COMPANY_LVL6_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL6_DESC,'') <> ISNULL(src.COMPANY_LVL6_DESC,'')
             OR ISNULL(tgt.COMPANY_LVL7_CODE,'') <> ISNULL(src.COMPANY_LVL7_CODE,'')
             OR ISNULL(tgt.COMPANY_LVL7_DESC,'') <> ISNULL(src.COMPANY_LVL7_DESC,'')
             OR ISNULL(tgt.COMPANY_DISTANCE, -999) <> ISNULL(src.COMPANY_DISTANCE, -999)
             OR ISNULL(tgt.COMPANY_CATEGORY,'') <> ISNULL(src.COMPANY_CATEGORY,'')
             OR ISNULL(tgt.COMPANY_ENABLED_FLAG,'') <> ISNULL(src.COMPANY_ENABLED_FLAG,'')
             OR tgt.START_DATE_ACTIVE <> src.START_DATE_ACTIVE
             OR tgt.END_DATE_ACTIVE <> src.END_DATE_ACTIVE
             OR ISNULL(tgt.CREATED_BY,'') <> ISNULL(src.CREATED_BY,'')
             OR ISNULL(tgt.CREATION_DATE,'1900-01-01') <> ISNULL(src.CREATION_DATE,'1900-01-01')
          );

        SET @RowExpired = @@ROWCOUNT;

        INSERT INTO svo.D_COMPANY
        (COMPANY_ID, COMPANY_LVL1_CODE, COMPANY_LVL1_DESC, COMPANY_LVL2_CODE, COMPANY_LVL2_DESC,
         COMPANY_LVL3_CODE, COMPANY_LVL3_DESC, COMPANY_LVL4_CODE, COMPANY_LVL4_DESC, COMPANY_LVL5_CODE, COMPANY_LVL5_DESC,
         COMPANY_LVL6_CODE, COMPANY_LVL6_DESC, COMPANY_LVL7_CODE, COMPANY_LVL7_DESC,
         COMPANY_DISTANCE, COMPANY_CATEGORY, COMPANY_ENABLED_FLAG, START_DATE_ACTIVE, END_DATE_ACTIVE,
         CREATED_BY, CREATION_DATE,
         HISTORIC_COMPANY_LVL1_CODE, HISTORIC_COMPANY_LVL1_DESC, HISTORIC_COMPANY_LVL2_CODE, HISTORIC_COMPANY_LVL2_DESC,
         HISTORIC_COMPANY_LVL3_CODE, HISTORIC_COMPANY_LVL3_DESC, HISTORIC_COMPANY_LVL4_CODE, HISTORIC_COMPANY_LVL4_DESC,
         HISTORIC_COMPANY_LVL5_CODE, HISTORIC_COMPANY_LVL5_DESC, HISTORIC_COMPANY_LVL6_CODE, HISTORIC_COMPANY_LVL6_DESC,
         HISTORIC_COMPANY_LVL7_CODE, HISTORIC_COMPANY_LVL7_DESC,
         BZ_LOAD_DATE, SV_LOAD_DATE, EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND)
        SELECT
            src.COMPANY_ID, src.COMPANY_LVL1_CODE, src.COMPANY_LVL1_DESC, src.COMPANY_LVL2_CODE, src.COMPANY_LVL2_DESC,
            src.COMPANY_LVL3_CODE, src.COMPANY_LVL3_DESC, src.COMPANY_LVL4_CODE, src.COMPANY_LVL4_DESC, src.COMPANY_LVL5_CODE, src.COMPANY_LVL5_DESC,
            src.COMPANY_LVL6_CODE, src.COMPANY_LVL6_DESC, src.COMPANY_LVL7_CODE, src.COMPANY_LVL7_DESC,
            src.COMPANY_DISTANCE, src.COMPANY_CATEGORY, src.COMPANY_ENABLED_FLAG, src.START_DATE_ACTIVE, src.END_DATE_ACTIVE,
            src.CREATED_BY, src.CREATION_DATE,
            COALESCE(prev.COMPANY_LVL1_CODE, src.COMPANY_LVL1_CODE), COALESCE(prev.COMPANY_LVL1_DESC, src.COMPANY_LVL1_DESC), COALESCE(prev.COMPANY_LVL2_CODE, src.COMPANY_LVL2_CODE), COALESCE(prev.COMPANY_LVL2_DESC, src.COMPANY_LVL2_DESC),
            COALESCE(prev.COMPANY_LVL3_CODE, src.COMPANY_LVL3_CODE), COALESCE(prev.COMPANY_LVL3_DESC, src.COMPANY_LVL3_DESC), COALESCE(prev.COMPANY_LVL4_CODE, src.COMPANY_LVL4_CODE), COALESCE(prev.COMPANY_LVL4_DESC, src.COMPANY_LVL4_DESC),
            COALESCE(prev.COMPANY_LVL5_CODE, src.COMPANY_LVL5_CODE), COALESCE(prev.COMPANY_LVL5_DESC, src.COMPANY_LVL5_DESC), COALESCE(prev.COMPANY_LVL6_CODE, src.COMPANY_LVL6_CODE), COALESCE(prev.COMPANY_LVL6_DESC, src.COMPANY_LVL6_DESC),
            COALESCE(prev.COMPANY_LVL7_CODE, src.COMPANY_LVL7_CODE), COALESCE(prev.COMPANY_LVL7_DESC, src.COMPANY_LVL7_DESC),
            src.BZ_LOAD_DATE, src.SV_LOAD_DATE,
            @AsOfDate, @HighDate, @LoadDttm, @LoadDttm, 'Y'
        FROM #src src
        LEFT JOIN svo.D_COMPANY tgt ON tgt.COMPANY_ID = src.COMPANY_ID AND tgt.CURR_IND = 'Y'
        LEFT JOIN svo.D_COMPANY prev ON prev.COMPANY_ID = src.COMPANY_ID AND prev.CURR_IND = 'N' AND prev.END_DATE = DATEADD(DAY, -1, @AsOfDate)
        WHERE tgt.COMPANY_ID IS NULL;

        SET @RowInserted = @@ROWCOUNT;

        IF @MaxWatermark IS NOT NULL
        BEGIN
            UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = @MaxWatermark, UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;
        END

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg  = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_BK_CURR' AND object_id = OBJECT_ID('svo.D_COMPANY'))
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_COMPANY_BK_CURR ON svo.D_COMPANY(COMPANY_ID) WHERE CURR_IND = 'Y' ON FG_SilverDim;
        ;THROW;
    END CATCH
END;
GO
