/* =========================================================
   usp_Load_D_GL_HEADER
   SCD2 incremental load (Option A: true history). Source: bzo.GL_JournalHeaderExtractPVO
   All source versions per BK kept; processed in chronological order so dimension reflects every change.
   Watermark: AddDateTime (or LAST_UPDATE_DATE fallback). EFF_DATE from source effective date. Grain: JE_HEADER_ID.
   Joins: D_LEDGER (CURR_IND='Y'), bzo GL_JournalCategory/JournalSource.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_D_GL_HEADER
    @BatchId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.D_GL_HEADER',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000) = NULL,
        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @LoadDttm       DATETIME2(0)   = SYSDATETIME(),
        @HighDate       DATE           = '9999-12-31',
        @LastWatermark  DATETIME2(7),
        @MaxWatermark   DATETIME2(7)   = NULL,
        @RowInserted    INT            = 0,
        @RowExpired     INT            = 0,
        @RowUpdated     INT            = 0,
        @max_rn         INT            = 0,
        @rn             INT            = 2,
        @TableBridgeID  INT            = NULL;

    SELECT @TableBridgeID = TableBridgeID FROM meta.MedallionTableBridge WHERE targettable = N'GL_JournalHeaderExtractPVO';

    BEGIN TRY
        SELECT @LastWatermark = w.LAST_WATERMARK
        FROM etl.ETL_WATERMARK w
        WHERE w.TABLE_NAME = @TargetObject;

        IF @LastWatermark IS NULL
            SET @LastWatermark = '1900-01-01';

        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS, BATCH_ID, TABLE_BRIDGE_ID)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED', ISNULL(@BatchId, -1), ISNULL(@TableBridgeID, -1));

        SET @RunId = SCOPE_IDENTITY();
        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_D_GL_HEADER_LEDGER_SK_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            DROP INDEX IX_D_GL_HEADER_LEDGER_SK_CURR ON svo.D_GL_HEADER;
        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            DROP INDEX UX_D_GL_HEADER_JE_HEADER_ID ON svo.D_GL_HEADER;
        IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            DROP INDEX UX_D_GL_HEADER_JE_HEADER_ID_CURR ON svo.D_GL_HEADER;

        IF NOT EXISTS (SELECT 1 FROM svo.D_GL_HEADER WHERE GL_HEADER_SK = 0)
        BEGIN
            SET IDENTITY_INSERT svo.D_GL_HEADER ON;
            INSERT INTO svo.D_GL_HEADER
            (GL_HEADER_SK, JE_HEADER_ID, LEDGER_SK, POSTED_DATE_SK, DEFAULT_EFFECTIVE_DATE_SK, GL_HEADER_NAME, GL_HEADER_STATUS, GL_HEADER_DESCRIPTION,
             ACCRUAL_REV_CHANGESIGN_FLAG, ACTUAL_FLAG, BALANCED_JE_FLAG, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE,
             EXTERNAL_REFERENCE, JE_BATCH_ID, CATEGORY, JE_SOURCE, MULTI_CURRENCY_FLAG, POST_CURRENCY_CODE, POST_MULTI_CURRENCY_FLAG,
             RUNNING_TOTAL_CR, RUNNING_TOTAL_DR, RUNNING_TOTAL_ACCOUNTED_CR, RUNNING_TOTAL_ACCOUNTED_DR, CR_DR_VARIANCE,
             DATE_CREATED, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
             EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND, BZ_LOAD_DATE, SV_LOAD_DATE)
            VALUES
            (0, -1, 0, 0, 0, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0001-01-01', 0, 'NULL', 'NULL', -1, 'NULL', 'NULL', 'NULL', 'NULL', 'NULL',
             0, 0, 0, 0, 0, '0001-01-01', 'NULL', '0001-01-01', '0001-01-01', 'NULL', 'NULL', @AsOfDate, @HighDate, @LoadDttm, @LoadDttm, 'Y', CAST('1900-01-01' AS DATETIME), GETDATE());
            SET IDENTITY_INSERT svo.D_GL_HEADER OFF;
        END;

        IF OBJECT_ID('tempdb..#src') IS NOT NULL DROP TABLE #src;

        SELECT
            d.JEHEADERID AS JE_HEADER_ID,
            ISNULL(LGR.LEDGER_SK, 0) AS LEDGER_SK,
            ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, d.GLJEHEADERSPOSTEDDATE), 112) AS INT), 0) AS POSTED_DATE_SK,
            ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, d.GLJEHEADERSDEFAULTEFFECTIVEDATE), 112) AS INT), 0) AS DEFAULT_EFFECTIVE_DATE_SK,
            ISNULL(d.GLJEHEADERSNAME, 'NULL') AS GL_HEADER_NAME,
            ISNULL(d.GLJEHEADERSSTATUS, 'NULL') AS GL_HEADER_STATUS,
            ISNULL(d.GLJEHEADERSDESCRIPTION, 'NULL') AS GL_HEADER_DESCRIPTION,
            ISNULL(d.GLJEHEADERSACCRUALREVCHANGESIGNFLAG, 'NULL') AS ACCRUAL_REV_CHANGESIGN_FLAG,
            ISNULL(d.GLJEHEADERSACTUALFLAG, 'NULL') AS ACTUAL_FLAG,
            ISNULL(d.GLJEHEADERSBALANCEDJEFLAG, 'NULL') AS BALANCED_JE_FLAG,
            ISNULL(d.GLJEHEADERSCURRENCYCODE, 'NULL') AS CURRENCY_CODE,
            CAST(ISNULL(d.GLJEHEADERSCURRENCYCONVERSIONDATE, '1900-01-01') AS DATE) AS CURRENCY_CONVERSION_DATE,
            ISNULL(d.GLJEHEADERSCURRENCYCONVERSIONRATE, 0) AS CURRENCY_CONVERSION_RATE,
            ISNULL(d.GLJEHEADERSCURRENCYCONVERSIONTYPE, 'NULL') AS CURRENCY_CONVERSION_TYPE,
            ISNULL(d.GLJEHEADERSEXTERNALREFERENCE, 'NULL') AS EXTERNAL_REFERENCE,
            ISNULL(d.GLJEHEADERSJEBATCHID, 0) AS JE_BATCH_ID,
            ISNULL(cat.JournalCategoryJeCategoryKey, 'NULL') AS CATEGORY,
            ISNULL(src.JournalSourceJeSourceKey, 'NULL') AS JE_SOURCE,
            ISNULL(d.GLJEHEADERSMULTICURRENCYFLAG, 'NULL') AS MULTI_CURRENCY_FLAG,
            ISNULL(d.GLJEHEADERSPOSTCURRENCYCODE, 'NULL') AS POST_CURRENCY_CODE,
            ISNULL(d.GLJEHEADERSPOSTMULTICURRENCYFLAG, 'NULL') AS POST_MULTI_CURRENCY_FLAG,
            CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALCR, 0) AS FLOAT) AS RUNNING_TOTAL_CR,
            CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALDR, 0) AS FLOAT) AS RUNNING_TOTAL_DR,
            CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_CR,
            CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_DR,
            CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT) - CAST(ISNULL(d.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS CR_DR_VARIANCE,
            CAST(ISNULL(d.GLJEHEADERSDATECREATED, '1900-01-01') AS DATE) AS DATE_CREATED,
            ISNULL(d.GLJEHEADERSCREATEDBY, 'NULL') AS CREATED_BY,
            CAST(ISNULL(d.GLJEHEADERSCREATIONDATE, '1900-01-01') AS DATE) AS CREATION_DATE,
            CAST(ISNULL(d.GLJEHEADERSLASTUPDATEDATE, '1900-01-01') AS DATE) AS LAST_UPDATE_DATE,
            ISNULL(d.GLJEHEADERSLASTUPDATELOGIN, 'NULL') AS LAST_UPDATE_LOGIN,
            ISNULL(d.GLJEHEADERSLASTUPDATEDBY, 'NULL') AS LAST_UPDATED_BY,
            d.BZ_LOAD_DATE,
            SYSDATETIME() AS SV_LOAD_DATE,
            d.SourceAddDateTime,
            CAST(d.SourceAddDateTime AS DATE) AS SourceEffDate,
            ROW_NUMBER() OVER (PARTITION BY d.JEHEADERID ORDER BY d.SourceAddDateTime ASC, d.BZ_LOAD_DATE DESC) AS rn_asc
        INTO #src
        FROM
        (
            SELECT s.*,
                   ROW_NUMBER() OVER (PARTITION BY s.JEHEADERID, s.SourceAddDateTime ORDER BY s.BZ_LOAD_DATE DESC) AS dedup_rn
            FROM
            (
                SELECT
                    H.*,
                    COALESCE(H.AddDateTime, H.GLJEHEADERSLASTUPDATEDATE, SYSDATETIME()) AS BZ_LOAD_DATE,
                    COALESCE(H.AddDateTime, CAST(H.GLJEHEADERSLASTUPDATEDATE AS DATETIME2(7)), SYSDATETIME()) AS SourceAddDateTime
                FROM bzo.GL_JournalHeaderExtractPVO H
                WHERE COALESCE(H.AddDateTime, CAST(H.GLJEHEADERSLASTUPDATEDATE AS DATETIME2(7)), '1900-01-01') > @LastWatermark
            ) s
        ) d
        LEFT JOIN svo.D_LEDGER AS LGR ON LGR.LEDGER_ID = d.GLJEHEADERSLEDGERID AND LGR.CURR_IND = 'Y'
        LEFT JOIN bzo.GL_JournalCategoryExtractPVO cat ON d.GlJeHeadersJeCategory = cat.JournalCategoryJeCategoryName
        LEFT JOIN bzo.GL_JournalSourceExtractPVO src ON d.GlJeHeadersJeSource = src.JournalSourceJeSourceName
        WHERE d.dedup_rn = 1;

        SELECT @MaxWatermark = MAX(SourceAddDateTime) FROM #src;
        SELECT @max_rn = ISNULL(MAX(rn_asc), 0) FROM #src;

        /* ===== Type 2: expire current rows where rn_asc=1 has attribute changes ===== */
        UPDATE tgt
        SET tgt.END_DATE = DATEADD(DAY, -1, src.SourceEffDate), tgt.CURR_IND = 'N', tgt.UDT_DATE = @LoadDttm
        FROM svo.D_GL_HEADER tgt
        INNER JOIN #src src ON src.JE_HEADER_ID = tgt.JE_HEADER_ID AND src.rn_asc = 1
        WHERE tgt.CURR_IND = 'Y'
          AND (
                ISNULL(tgt.LEDGER_SK,-999) <> ISNULL(src.LEDGER_SK,-999)
             OR ISNULL(tgt.POSTED_DATE_SK,-999) <> ISNULL(src.POSTED_DATE_SK,-999)
             OR ISNULL(tgt.DEFAULT_EFFECTIVE_DATE_SK,-999) <> ISNULL(src.DEFAULT_EFFECTIVE_DATE_SK,-999)
             OR ISNULL(tgt.GL_HEADER_NAME,'') <> ISNULL(src.GL_HEADER_NAME,'')
             OR ISNULL(tgt.GL_HEADER_STATUS,'') <> ISNULL(src.GL_HEADER_STATUS,'')
             OR ISNULL(tgt.GL_HEADER_DESCRIPTION,'') <> ISNULL(src.GL_HEADER_DESCRIPTION,'')
             OR ISNULL(tgt.CATEGORY,'') <> ISNULL(src.CATEGORY,'')
             OR ISNULL(tgt.JE_SOURCE,'') <> ISNULL(src.JE_SOURCE,'')
             OR ISNULL(tgt.CURRENCY_CODE,'') <> ISNULL(src.CURRENCY_CODE,'')
             OR ISNULL(tgt.EXTERNAL_REFERENCE,'') <> ISNULL(src.EXTERNAL_REFERENCE,'')
             OR ISNULL(tgt.JE_BATCH_ID,-999) <> ISNULL(src.JE_BATCH_ID,-999)
             OR tgt.DATE_CREATED <> src.DATE_CREATED
             OR ISNULL(tgt.CREATED_BY,'') <> ISNULL(src.CREATED_BY,'')
             OR tgt.CREATION_DATE <> src.CREATION_DATE
             OR tgt.LAST_UPDATE_DATE <> src.LAST_UPDATE_DATE
          );

        SET @RowExpired += @@ROWCOUNT;

        /* ===== Option A: first version (rn_asc=1) – insert where no current row ===== */
        INSERT INTO svo.D_GL_HEADER
        (JE_HEADER_ID, LEDGER_SK, POSTED_DATE_SK, DEFAULT_EFFECTIVE_DATE_SK, GL_HEADER_NAME, GL_HEADER_STATUS, GL_HEADER_DESCRIPTION,
         ACCRUAL_REV_CHANGESIGN_FLAG, ACTUAL_FLAG, BALANCED_JE_FLAG, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE,
         EXTERNAL_REFERENCE, JE_BATCH_ID, CATEGORY, JE_SOURCE, MULTI_CURRENCY_FLAG, POST_CURRENCY_CODE, POST_MULTI_CURRENCY_FLAG,
         RUNNING_TOTAL_CR, RUNNING_TOTAL_DR, RUNNING_TOTAL_ACCOUNTED_CR, RUNNING_TOTAL_ACCOUNTED_DR, CR_DR_VARIANCE,
         DATE_CREATED, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
         EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND, BZ_LOAD_DATE, SV_LOAD_DATE)
        SELECT
            src.JE_HEADER_ID, src.LEDGER_SK, src.POSTED_DATE_SK, src.DEFAULT_EFFECTIVE_DATE_SK, src.GL_HEADER_NAME, src.GL_HEADER_STATUS, src.GL_HEADER_DESCRIPTION,
            src.ACCRUAL_REV_CHANGESIGN_FLAG, src.ACTUAL_FLAG, src.BALANCED_JE_FLAG, src.CURRENCY_CODE, src.CURRENCY_CONVERSION_DATE, src.CURRENCY_CONVERSION_RATE, src.CURRENCY_CONVERSION_TYPE,
            src.EXTERNAL_REFERENCE, src.JE_BATCH_ID, src.CATEGORY, src.JE_SOURCE, src.MULTI_CURRENCY_FLAG, src.POST_CURRENCY_CODE, src.POST_MULTI_CURRENCY_FLAG,
            src.RUNNING_TOTAL_CR, src.RUNNING_TOTAL_DR, src.RUNNING_TOTAL_ACCOUNTED_CR, src.RUNNING_TOTAL_ACCOUNTED_DR, src.CR_DR_VARIANCE,
            src.DATE_CREATED, src.CREATED_BY, src.CREATION_DATE, src.LAST_UPDATE_DATE, src.LAST_UPDATE_LOGIN, src.LAST_UPDATED_BY,
            src.SourceEffDate, @HighDate, @LoadDttm, @LoadDttm, 'Y', src.BZ_LOAD_DATE, src.SV_LOAD_DATE
        FROM #src src
        WHERE src.rn_asc = 1
          AND NOT EXISTS (SELECT 1 FROM svo.D_GL_HEADER tgt WHERE tgt.JE_HEADER_ID = src.JE_HEADER_ID AND tgt.CURR_IND = 'Y');

        SET @RowInserted = @@ROWCOUNT;

        /* ===== Option A: subsequent versions (rn_asc 2..max) – expire current then insert with source EFF_DATE ===== */
        WHILE @rn <= @max_rn
        BEGIN
            UPDATE tgt
            SET tgt.END_DATE = DATEADD(DAY, -1, src.SourceEffDate), tgt.CURR_IND = 'N', tgt.UDT_DATE = @LoadDttm
            FROM svo.D_GL_HEADER tgt
            INNER JOIN #src src ON src.JE_HEADER_ID = tgt.JE_HEADER_ID AND src.rn_asc = @rn
            WHERE tgt.CURR_IND = 'Y';

            SET @RowExpired += @@ROWCOUNT;

            INSERT INTO svo.D_GL_HEADER
            (JE_HEADER_ID, LEDGER_SK, POSTED_DATE_SK, DEFAULT_EFFECTIVE_DATE_SK, GL_HEADER_NAME, GL_HEADER_STATUS, GL_HEADER_DESCRIPTION,
             ACCRUAL_REV_CHANGESIGN_FLAG, ACTUAL_FLAG, BALANCED_JE_FLAG, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE,
             EXTERNAL_REFERENCE, JE_BATCH_ID, CATEGORY, JE_SOURCE, MULTI_CURRENCY_FLAG, POST_CURRENCY_CODE, POST_MULTI_CURRENCY_FLAG,
             RUNNING_TOTAL_CR, RUNNING_TOTAL_DR, RUNNING_TOTAL_ACCOUNTED_CR, RUNNING_TOTAL_ACCOUNTED_DR, CR_DR_VARIANCE,
             DATE_CREATED, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
             EFF_DATE, END_DATE, CRE_DATE, UDT_DATE, CURR_IND, BZ_LOAD_DATE, SV_LOAD_DATE)
            SELECT
                src.JE_HEADER_ID, src.LEDGER_SK, src.POSTED_DATE_SK, src.DEFAULT_EFFECTIVE_DATE_SK, src.GL_HEADER_NAME, src.GL_HEADER_STATUS, src.GL_HEADER_DESCRIPTION,
                src.ACCRUAL_REV_CHANGESIGN_FLAG, src.ACTUAL_FLAG, src.BALANCED_JE_FLAG, src.CURRENCY_CODE, src.CURRENCY_CONVERSION_DATE, src.CURRENCY_CONVERSION_RATE, src.CURRENCY_CONVERSION_TYPE,
                src.EXTERNAL_REFERENCE, src.JE_BATCH_ID, src.CATEGORY, src.JE_SOURCE, src.MULTI_CURRENCY_FLAG, src.POST_CURRENCY_CODE, src.POST_MULTI_CURRENCY_FLAG,
                src.RUNNING_TOTAL_CR, src.RUNNING_TOTAL_DR, src.RUNNING_TOTAL_ACCOUNTED_CR, src.RUNNING_TOTAL_ACCOUNTED_DR, src.CR_DR_VARIANCE,
                src.DATE_CREATED, src.CREATED_BY, src.CREATION_DATE, src.LAST_UPDATE_DATE, src.LAST_UPDATE_LOGIN, src.LAST_UPDATED_BY,
                src.SourceEffDate, @HighDate, @LoadDttm, @LoadDttm, 'Y', src.BZ_LOAD_DATE, src.SV_LOAD_DATE
            FROM #src src
            WHERE src.rn_asc = @rn
              AND NOT EXISTS (SELECT 1 FROM svo.D_GL_HEADER tgt WHERE tgt.JE_HEADER_ID = src.JE_HEADER_ID AND tgt.CURR_IND = 'Y');

            SET @RowInserted += @@ROWCOUNT;
            SET @rn += 1;
        END

        IF @MaxWatermark IS NOT NULL
            UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = @MaxWatermark, UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;

        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_D_GL_HEADER_LEDGER_SK_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE NONCLUSTERED INDEX IX_D_GL_HEADER_LEDGER_SK_CURR ON svo.D_GL_HEADER(LEDGER_SK, CURR_IND) ON FG_SilverDim;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID ON svo.D_GL_HEADER(JE_HEADER_ID) ON FG_SilverDim;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID_CURR ON svo.D_GL_HEADER(JE_HEADER_ID) WHERE (CURR_IND='Y') ON FG_SilverDim;

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_EXPIRED = @RowExpired, ROW_UPDATED = @RowUpdated, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_D_GL_HEADER_LEDGER_SK_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE NONCLUSTERED INDEX IX_D_GL_HEADER_LEDGER_SK_CURR ON svo.D_GL_HEADER(LEDGER_SK, CURR_IND) ON FG_SilverDim;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID ON svo.D_GL_HEADER(JE_HEADER_ID) ON FG_SilverDim;
        IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
            CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID_CURR ON svo.D_GL_HEADER(JE_HEADER_ID) WHERE (CURR_IND='Y') ON FG_SilverDim;
        ;THROW;
    END CATCH
END;
GO
