IF OBJECT_ID('svo.D_RM_SATISFACTION_METHOD','U') IS NOT NULL
    DROP TABLE svo.D_RM_SATISFACTION_METHOD;
GO

CREATE TABLE svo.D_RM_SATISFACTION_METHOD
(
    RM_SATISFACTION_METHOD_SK  BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SATISFACTION_METHOD_CODE   VARCHAR(60)   NOT NULL,
    SATISFACTION_METHOD_NAME   VARCHAR(240)  NULL,
    BZ_LOAD_DATE               DATE          NOT NULL DEFAULT (CAST(GETDATE() AS DATE)),
    SV_LOAD_DATE               DATE          NOT NULL DEFAULT (CAST(GETDATE() AS DATE))
) ON [FG_SilverDim];
GO

SET IDENTITY_INSERT svo.D_RM_SATISFACTION_METHOD ON;

INSERT INTO svo.D_RM_SATISFACTION_METHOD
(
    RM_SATISFACTION_METHOD_SK,
    SATISFACTION_METHOD_CODE,
    SATISFACTION_METHOD_NAME,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
VALUES
(
    0,
    'UNK',
    'Unknown',
    CAST(GETDATE() AS DATE),
    CAST(GETDATE() AS DATE)
);

SET IDENTITY_INSERT svo.D_RM_SATISFACTION_METHOD OFF;
GO

INSERT INTO svo.D_RM_SATISFACTION_METHOD
(
    SATISFACTION_METHOD_CODE,
    SATISFACTION_METHOD_NAME,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
SELECT
    M.PerfObligationsSatisfactionMethod                          AS SATISFACTION_METHOD_CODE,
    M.PerfObligationsSatisfactionMethod                          AS SATISFACTION_METHOD_NAME,
    COALESCE(MIN(CAST(M.AddDateTime AS DATE)), CAST(GETDATE() AS DATE)) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE)                                      AS SV_LOAD_DATE
FROM bzo.VRM_PerfObligationsPVO AS M
WHERE M.PerfObligationsSatisfactionMethod IS NOT NULL
  AND LTRIM(RTRIM(M.PerfObligationsSatisfactionMethod)) <> ''
GROUP BY
    M.PerfObligationsSatisfactionMethod;
GO