USE Oracle_Reporting_P2;
GO

IF OBJECT_ID('svo.D_AR_RECEIPT_METHOD','U') IS NOT NULL
    DROP TABLE svo.D_AR_RECEIPT_METHOD;
GO

CREATE TABLE svo.D_AR_RECEIPT_METHOD
(
    RECEIPT_METHOD_SK                 BIGINT IDENTITY(1,1) NOT NULL,

    -- Business key from source
    AR_RECEIPT_METHOD_RECEIPT_METHOD_ID  BIGINT       NOT NULL,

    -- Attributes
    AR_RECEIPT_METHOD_NAME            VARCHAR(30)  NOT NULL,

    -- DW audit
    BZ_LOAD_DATE                      DATE        NOT NULL,
    SV_LOAD_DATE                      DATE        NOT NULL,

    CONSTRAINT PK_D_AR_RECEIPT_METHOD
        PRIMARY KEY CLUSTERED (RECEIPT_METHOD_SK)
) ON FG_SilverDim;
GO

-- Unique index on business key
CREATE UNIQUE NONCLUSTERED INDEX UX_D_AR_RECEIPT_METHOD_BK
ON svo.D_AR_RECEIPT_METHOD (AR_RECEIPT_METHOD_RECEIPT_METHOD_ID)
ON FG_SilverDim;
GO

SET IDENTITY_INSERT svo.D_AR_RECEIPT_METHOD ON;

INSERT INTO svo.D_AR_RECEIPT_METHOD
(
    RECEIPT_METHOD_SK,
    AR_RECEIPT_METHOD_RECEIPT_METHOD_ID,
    AR_RECEIPT_METHOD_NAME,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
VALUES
(
    0,
    0,
    'UNKNOWN',
    CAST('1900-01-01' AS DATE),
    CAST(GETDATE() AS DATE)
);

SET IDENTITY_INSERT svo.D_AR_RECEIPT_METHOD OFF;
GO

MERGE svo.D_AR_RECEIPT_METHOD AS tgt
USING
(
    SELECT
        b.ArReceiptMethodReceiptMethodId AS AR_RECEIPT_METHOD_RECEIPT_METHOD_ID,
        b.ArReceiptMethodName            AS AR_RECEIPT_METHOD_NAME,
        CAST(b.AddDateTime AS DATE)      AS BZ_LOAD_DATE
    FROM bzo.AR_ReceiptMethodExtractPVO b
) AS src
    ON tgt.AR_RECEIPT_METHOD_RECEIPT_METHOD_ID = src.AR_RECEIPT_METHOD_RECEIPT_METHOD_ID

WHEN MATCHED THEN
    UPDATE SET
        tgt.AR_RECEIPT_METHOD_NAME = src.AR_RECEIPT_METHOD_NAME,
        tgt.BZ_LOAD_DATE           = src.BZ_LOAD_DATE,
        tgt.SV_LOAD_DATE           = CAST(GETDATE() AS DATE)

WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        AR_RECEIPT_METHOD_RECEIPT_METHOD_ID,
        AR_RECEIPT_METHOD_NAME,
        BZ_LOAD_DATE,
        SV_LOAD_DATE
    )
    VALUES
    (
        src.AR_RECEIPT_METHOD_RECEIPT_METHOD_ID,
        src.AR_RECEIPT_METHOD_NAME,
        src.BZ_LOAD_DATE,
        CAST(GETDATE() AS DATE)
    );
GO
