USE Oracle_Reporting_P2
GO

SET NOCOUNT ON;
GO


/* ============================================================
   1) D_AR_TRANSACTION_TYPE
   ============================================================ */

IF OBJECT_ID('[svo].[D_AR_TRANSACTION_TYPE]', 'U') IS NOT NULL
    DROP TABLE [svo].[D_AR_TRANSACTION_TYPE];
GO

CREATE TABLE [svo].[D_AR_TRANSACTION_TYPE]
(
    AR_TRANSACTION_TYPE_SK          bigint          IDENTITY(1,1) NOT NULL,
    AR_TRANSACTION_TYPE_SEQ_ID      bigint          NOT NULL,
    AR_TRANSACTION_TYPE_NAME        varchar(20)     NULL,

    AddDateTime                     datetime        NULL,
    BZ_LOAD_DATE                    AS CONVERT(date, AddDateTime) PERSISTED,
    SV_LOAD_DATE                    date            NOT NULL
        CONSTRAINT DF_D_AR_TRANSACTION_TYPE_SV_LOAD_DATE DEFAULT (CONVERT(date, GETDATE())),

    CONSTRAINT PK_D_AR_TRANSACTION_TYPE PRIMARY KEY CLUSTERED (AR_TRANSACTION_TYPE_SK)
        ON [FG_SilverDim]
)
ON [FG_SilverDim];
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_D_AR_TRANSACTION_TYPE_BK
ON [svo].[D_AR_TRANSACTION_TYPE] (AR_TRANSACTION_TYPE_SEQ_ID)
ON [FG_SilverDim];
GO

IF NOT EXISTS (SELECT 1 FROM [svo].[D_AR_TRANSACTION_TYPE] WHERE AR_TRANSACTION_TYPE_SEQ_ID = 0)
BEGIN
    SET IDENTITY_INSERT [svo].[D_AR_TRANSACTION_TYPE] ON;

    INSERT INTO [svo].[D_AR_TRANSACTION_TYPE]
    (
        AR_TRANSACTION_TYPE_SK,
        AR_TRANSACTION_TYPE_SEQ_ID,
        AR_TRANSACTION_TYPE_NAME,
        AddDateTime,
        SV_LOAD_DATE
    )
    VALUES
    (
        0, 0, 'UNKNOWN', GETDATE(), CONVERT(date, GETDATE())
    );

    SET IDENTITY_INSERT [svo].[D_AR_TRANSACTION_TYPE] OFF;
END
GO

;WITH S AS
(
    SELECT
        T.RaCustTrxTypeCustTrxTypeSeqId    AS AR_TRANSACTION_TYPE_SEQ_ID,
        T.RaCustTrxTypeName                AS AR_TRANSACTION_TYPE_NAME,
        T.AddDateTime
    FROM [bzo].[AR_TransactionTypeExtractPVO] T
)
MERGE [svo].[D_AR_TRANSACTION_TYPE] AS D
USING S
ON D.AR_TRANSACTION_TYPE_SEQ_ID = S.AR_TRANSACTION_TYPE_SEQ_ID
WHEN MATCHED THEN
    UPDATE SET
        D.AR_TRANSACTION_TYPE_NAME = S.AR_TRANSACTION_TYPE_NAME,
        D.AddDateTime              = S.AddDateTime
WHEN NOT MATCHED BY TARGET THEN
    INSERT (AR_TRANSACTION_TYPE_SEQ_ID, AR_TRANSACTION_TYPE_NAME, AddDateTime)
    VALUES (S.AR_TRANSACTION_TYPE_SEQ_ID, S.AR_TRANSACTION_TYPE_NAME, S.AddDateTime)
WHEN NOT MATCHED BY SOURCE
    AND D.AR_TRANSACTION_TYPE_SK <> 0
THEN DELETE
;
GO
