USE [Oracle_Reporting_P2];
GO

IF OBJECT_ID('svo.D_SM_SUBSCRIPTION','U') IS NOT NULL 
    DROP TABLE svo.D_SM_SUBSCRIPTION;
GO

CREATE TABLE svo.D_SM_SUBSCRIPTION
(
    SUBSCRIPTION_SK      BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SUBSCRIPTION_ID      BIGINT NOT NULL,
    BILL_TO_ACCT_ID      BIGINT NULL,
    BILL_TO_SITE_USE_ID  BIGINT NULL,
    BUSINESS_UNIT_ID     BIGINT NULL,
    LEGAL_ENTITY_ID      BIGINT NULL,
    CREATION_DATE        DATE   NULL,
    BZ_LOAD_DATE         DATE   NULL,
    SV_LOAD_DATE         DATE   NULL
) ON [FG_SilverDim];
GO

SET IDENTITY_INSERT svo.D_SM_SUBSCRIPTION ON;
INSERT INTO svo.D_SM_SUBSCRIPTION
    (SUBSCRIPTION_SK, SUBSCRIPTION_ID, BILL_TO_ACCT_ID, BILL_TO_SITE_USE_ID, BUSINESS_UNIT_ID, LEGAL_ENTITY_ID, CREATION_DATE, BZ_LOAD_DATE, SV_LOAD_DATE)
VALUES
    (0, -1, -1, -1, -1, -1, '0001-01-01', '0001-01-01', '0001-01-01');
SET IDENTITY_INSERT svo.D_SM_SUBSCRIPTION OFF;
GO

INSERT INTO svo.D_SM_SUBSCRIPTION
(
    SUBSCRIPTION_ID,
    BILL_TO_ACCT_ID,
    BILL_TO_SITE_USE_ID,
    BUSINESS_UNIT_ID,
    LEGAL_ENTITY_ID,
    CREATION_DATE,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
SELECT DISTINCT
    H.SubscriptionId,
    H.BillToAcctId,
    H.BillToSiteUseId,
    H.BusinessUnitId,
    H.LegalEntityId,
    CAST(H.CreationDate AS DATE),
    CAST(H.AddDateTime AS DATE),
    CAST(GETDATE() AS DATE)
FROM bzo.OSS_SubscriptionHeaderExtractPVO H
WHERE NOT EXISTS (
    SELECT 1 FROM svo.D_SM_SUBSCRIPTION D WHERE D.SUBSCRIPTION_ID = H.SubscriptionId
);
GO