-- Rebuild Dimensions from scratch. EVERYTHING WILL BE REPLACED! ---

USE Oracle_Reporting_P2;
GO

/* =========================
   GL Code Combination Lookup
   ========================= */
IF OBJECT_ID(N'stage.LINES_CODE_COMBO_LOOKUP', 'U') IS NOT NULL
    DROP TABLE stage.LINES_CODE_COMBO_LOOKUP;
GO

CREATE TABLE stage.LINES_CODE_COMBO_LOOKUP(
    CODE_COMBINATION_BK BIGINT NULL,
    COMPANY_ID VARCHAR(100) NULL,
    COMPANY_DESC VARCHAR(500) NULL,
    COSTCENTER_ID VARCHAR(100) NULL,
    COSTCENTER_DESC VARCHAR(500) NULL,
    BUSINESSOFFERING_ID VARCHAR(100) NULL,
    BUSINESSOFFERING_DESC VARCHAR(500) NULL,
    ACCOUNT_ID VARCHAR(100) NULL,
    ACCOUNT_DESC VARCHAR(500) NULL,
    INDUSTRY_ID VARCHAR(100) NULL,
    INDUSTRY_DESC VARCHAR(500) NULL,
    INTERCOMPANY_ID VARCHAR(100) NULL,
    INTERCOMPANY_DESC VARCHAR(500) NULL
) ON FG_SilverMisc;
GO

INSERT INTO STAGE.LINES_CODE_COMBO_LOOKUP (
     CODE_COMBINATION_BK,
     COMPANY_ID,
     COMPANY_DESC,
     COSTCENTER_ID,
     COSTCENTER_DESC,
     BUSINESSOFFERING_ID,
     BUSINESSOFFERING_DESC,
     ACCOUNT_ID,
     ACCOUNT_DESC,
     INDUSTRY_ID,
     INDUSTRY_DESC,
     INTERCOMPANY_ID,
     INTERCOMPANY_DESC
)
SELECT 
     CAST(C1.CODECOMBINATIONCODECOMBINATIONID AS BIGINT) AS CODE_COMBINATION_BK,
     C1.CODECOMBINATIONSEGMENT1   AS COMPANY_ID,
     VSEG1.DESCRIPTION            AS COMPANY_DESC,
     C1.CODECOMBINATIONSEGMENT2   AS COSTCENTER_ID,
     VSEG2.DESCRIPTION            AS COSTCENTER_DESC,
     C1.CODECOMBINATIONSEGMENT3   AS BUSINESSOFFERING_ID,
     VSEG3.DESCRIPTION            AS BUSINESSOFFERING_DESC,
     C1.CODECOMBINATIONSEGMENT4   AS ACCOUNT_ID,
     VSEG4.DESCRIPTION            AS ACCOUNT_DESC,
     C1.CODECOMBINATIONSEGMENT5   AS INDUSTRY_ID,
     VSEG5.DESCRIPTION            AS INDUSTRY_DESC,
     C1.CODECOMBINATIONSEGMENT6   AS INTERCOMPANY_ID,
     VSEG6.DESCRIPTION            AS INTERCOMPANY_DESC
FROM bzo.GL_CodeCombinationExtractPVO AS C1
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG1 ON C1.CODECOMBINATIONSEGMENT1 = VSEG1.VALUE  AND VSEG1.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG2 ON C1.CODECOMBINATIONSEGMENT2 = VSEG2.VALUE  AND VSEG2.ATTRIBUTECATEGORY = 'CENTER LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG3 ON C1.CODECOMBINATIONSEGMENT3 = VSEG3.VALUE  AND VSEG3.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG4 ON C1.CODECOMBINATIONSEGMENT4 = VSEG4.VALUE  AND VSEG4.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG5 ON C1.CODECOMBINATIONSEGMENT5 = VSEG5.VALUE  AND VSEG5.ATTRIBUTECATEGORY = 'INDUSTRY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO AS VSEG6 ON C1.CODECOMBINATIONSEGMENT6 = VSEG6.VALUE  AND VSEG6.ATTRIBUTECATEGORY = 'INTERCOMPANY LAMAR';
GO

CREATE UNIQUE INDEX IX_CODECOMBO_LKP 
ON stage.LINES_CODE_COMBO_LOOKUP (CODE_COMBINATION_BK ASC)
ON FG_SilverMisc;
GO

