-- Rebuild Dimensions from scratch. EVERYTHING WILL BE REPLACED! ---

USE Oracle_Reporting_P2;
GO

/* =======
   COMPANY
   ======= */
IF OBJECT_ID(N'svo.D_COMPANY', 'U') IS NOT NULL
    DROP TABLE svo.D_COMPANY;
GO

CREATE TABLE svo.D_COMPANY
(
    COMPANY_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    COMPANY_ID        VARCHAR(100) NOT NULL,
    COMPANY_LVL1_CODE VARCHAR(100) NULL,
    COMPANY_LVL1_DESC VARCHAR(500) NULL,
    COMPANY_LVL2_CODE VARCHAR(25) NULL,
    COMPANY_LVL2_DESC VARCHAR(500) NULL,
    COMPANY_LVL3_CODE VARCHAR(25) NULL,
    COMPANY_LVL3_DESC VARCHAR(500) NULL,
    COMPANY_LVL4_CODE VARCHAR(150) NULL,
    COMPANY_LVL4_DESC VARCHAR(500) NULL,
    COMPANY_LVL5_CODE VARCHAR(100) NULL,
    COMPANY_LVL5_DESC VARCHAR(500) NULL,
    COMPANY_LVL6_CODE VARCHAR(25) NULL,
    COMPANY_LVL6_DESC VARCHAR(500) NULL,
    COMPANY_LVL7_CODE VARCHAR(25) NULL,
    COMPANY_LVL7_DESC VARCHAR(500) NULL,
    COMPANY_DISTANCE  SMALLINT NULL,
    COMPANY_CATEGORY  VARCHAR(60) NULL,
    COMPANY_ENABLED_FLAG VARCHAR(4) NULL,
    START_DATE_ACTIVE    DATE NOT NULL,
    END_DATE_ACTIVE      DATE NOT NULL,
    CREATED_BY           VARCHAR(64) NULL,
    CREATION_DATE        DATE NULL,
    BZ_LOAD_DATE         DATE NULL,
    SV_LOAD_DATE         DATE NULL
) ON FG_SilverDim;
GO

INSERT INTO svo.D_COMPANY (
     COMPANY_ID,
     COMPANY_LVL1_CODE,
     COMPANY_LVL1_DESC,
     COMPANY_LVL2_CODE,
     COMPANY_LVL2_DESC,
     COMPANY_LVL3_CODE,
     COMPANY_LVL3_DESC,
     COMPANY_LVL4_CODE,
     COMPANY_LVL4_DESC,
     COMPANY_LVL5_CODE,
     COMPANY_LVL5_DESC,
     COMPANY_LVL6_CODE,
     COMPANY_LVL6_DESC,
     COMPANY_LVL7_CODE,
     COMPANY_LVL7_DESC,
     COMPANY_DISTANCE,
     COMPANY_CATEGORY,
     COMPANY_ENABLED_FLAG,
     START_DATE_ACTIVE,
     END_DATE_ACTIVE,
     CREATED_BY,
     CREATION_DATE,
     BZ_LOAD_DATE,
     SV_LOAD_DATE
)
SELECT
    ISNULL(TRIM(lvl7.VALUE),'-1') AS COMPANY_ID,
    COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE, h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL1_CODE,
    COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL1_DESC,
    COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL2_CODE,
    COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL2_DESC,
    COALESCE(h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL3_CODE,
    COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL3_DESC,
    COALESCE(h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL4_CODE,
    COALESCE(lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL4_DESC,
    COALESCE(h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL5_CODE,
    COALESCE(lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL5_DESC,
    COALESCE(h1.DEP26PK1VALUE,lvl7.VALUE) AS COMPANY_LVL6_CODE,
    COALESCE(lvl6.DESCRIPTION,lvl7.DESCRIPTION) AS COMPANY_LVL6_DESC,
    lvl7.VALUE       AS COMPANY_LVL7_CODE,
    lvl7.DESCRIPTION AS COMPANY_LVL7_DESC,
    0                  AS COMPANY_DISTANCE,
    lvl7.ATTRIBUTECATEGORY AS COMPANY_CATEGORY,
    lvl7.ENABLEDFLAG AS COMPANY_ENABLED_FLAG,
    ISNULL(lvl7.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
    ISNULL(lvl7.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
    lvl7.CREATEDBY AS CREATED_BY,
    CAST(lvl7.CREATIONDATE AS DATE) AS CREATION_DATE,
    COALESCE(CAST(h1.AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM bzo.GL_SegmentValueHierarchyExtractPVO h1 
INNER JOIN bzo.GL_FndTreeAndVersionVO ver1 
    ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP28PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl5 ON lvl5.VALUE = h1.DEP27PK1VALUE AND lvl5.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl6 ON lvl6.VALUE = h1.DEP26PK1VALUE AND lvl6.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
RIGHT JOIN bzo.GL_ValueSetValuesPVO lvl7 ON lvl7.VALUE = h1.DEP0PK1VALUE AND lvl7.ATTRIBUTECATEGORY = 'COMPANY LAMAR'
WHERE lvl7.ATTRIBUTECATEGORY = 'COMPANY LAMAR' AND lvl7.SUMMARYFLAG = 'N';
GO

/* =========================
   COMPANY
   ========================= */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_ID' AND object_id = OBJECT_ID('svo.D_COMPANY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COMPANY_ID ON svo.D_COMPANY(COMPANY_ID) ON FG_SilverDim;;
END

IF NOT EXISTS (SELECT 1 FROM svo.D_COMPANY WHERE COMPANY_SK = 0)
BEGIN
    SET IDENTITY_INSERT svo.D_COMPANY ON;

    INSERT INTO svo.D_COMPANY(COMPANY_SK,COMPANY_ID,COMPANY_LVL1_CODE,COMPANY_LVL1_DESC,COMPANY_LVL2_CODE,
        COMPANY_LVL2_DESC,COMPANY_LVL3_CODE,COMPANY_LVL3_DESC,COMPANY_LVL4_CODE,COMPANY_LVL4_DESC,COMPANY_LVL5_CODE,
        COMPANY_LVL5_DESC,COMPANY_LVL6_CODE,COMPANY_LVL6_DESC,COMPANY_LVL7_CODE,COMPANY_LVL7_DESC,COMPANY_DISTANCE,
        COMPANY_CATEGORY,COMPANY_ENABLED_FLAG,START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,CREATION_DATE) 
    VALUES (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',0,
            'Missing','NULL','0001-01-01','9999-12-31','UNK','2025-10-18');

    SET IDENTITY_INSERT svo.D_COMPANY OFF;
END