 SELECT TOP (1000) [RUN_ID]
      ,[PROC_NAME]
      ,[TARGET_OBJECT]
      ,[ASOF_DATE]
      ,[START_DTTM]
      ,[END_DTTM]
      ,[STATUS]
      ,[ROW_INSERTED]
      ,[ROW_EXPIRED]
      ,[ROW_UPDATED]
      ,[ERROR_MESSAGE]
  FROM [Oracle_Reporting_P2].[etl].[ETL_RUN]
