-- Single-query version: SL Journal Distribution lines not in AP, joined to D_AP_INVOICE_HEADER
SELECT
	'ASSIGN'										AS AP_INVOICE_DIST_FACT_PK
,	IH.AP_INVOICE_HEADER_SK
,	IH.INVOICE_ID
,	-1												AS INVOICE_LINE_NUMBER	--AE_LINE_NUM?, TMP_LINE_NUM?
,	SL.SOURCE_DIST_ID_NUM1							AS INVOICE_DISTRIBUTION_ID
,	-1												AS DIST_INV_LINE_NUMBER
,	-1												AS DISTRIBUTION_LINE_NUMBER
,	SL.ACCOUNTING_DATE_SK							AS DIST_ACCOUNTING_DATE_SK
,	SL.ACCOUNTING_DATE_SK							AS LINE_ACCOUNTING_DATE_SK		--Unknown Date
--GL STRING
,	NULL as ACCOUNT_SK
,	NULL as BUSINESS_OFFERING_SK
,	NULL as COMPANY_SK
,	NULL AS COST_CENTER_SK
,	NULL AS INDUSTRY_SK
,	NULL AS INTERCOMPANY_SK
--INVOICE HEADER or LINE?
,	NULL AS LEGAL_ENTITY_SK
,	NULL AS BUSINESS_UNIT_SK
,	NULL AS VENDOR_SITE_SK
,	NULL AS LEDGER_SK
--OTHER
,	'UNK'											AS DISTRIBUTION_CLASS
,	SL.LINE_DESCRIPTION								AS DIST_DESCRIPTION
,	SL.LINE_DESCRIPTION								AS LINE_DESCRIPTION
,	SL.ACCOUNTED_CR - SL.ACCOUNTED_DR				AS DISTRIBUTION_AMOUNT
,	'Y'												AS POSTED_FLAG
,	'UNK'											AS TAX_1099
,	'UNK'											AS INV_TAX_JURISDICTION_CODE
,	'UNK'											AS INV_TAX_RATE
,	'UNK'											AS LINE_TYPE_LOOKUP_CODE
--PJC FIELDS - REMOVE
,	0												AS PO_DISTRIBUTION_ID
--DIST ADMIN FIELDS
--DW ADMIN FIELDS
,	0												AS IS_ORIG_AP_INV
FROM 
	(
		SELECT
			SL.SL_JOURNAL_DIST_FACT_PK
		,	SL.TRANSACTION_SOURCE_ID_INT1
		,	SL.SOURCE_DIST_ID_NUM1
		,	SL.ACCOUNTED_CR
		,	SL.ACCOUNTED_DR
		,	SL.CODE_COMBINATION_ID
		,	SL.ACCOUNTING_DATE_SK
		,	SL.ACCOUNTING_DATE_SK	AS LINE_ACCOUNTING_DATE_SK
		,	SL.EVENT_TYPE_CODE
		,	SL.TRANSACTION_ENTITY_CODE
		,	SL.LINE_DESCRIPTION
		,	SL.SOURCE_DISTRIBUTION_TYPE
		FROM
			svo.F_SL_JOURNAL_DISTRIBUTION						SL
			LEFT JOIN svo.F_AP_INVOICE_LINE_DISTRIBUTION		AP	ON	SL.TRANSACTION_SOURCE_ID_INT1	=	AP.INVOICE_ID
																	AND SL.SOURCE_DIST_ID_NUM1			=	AP.INVOICE_DISTRIBUTION_ID	
		WHERE 1=1
			AND SL.APPLICATION_ID				=	200
			AND SL.TRANSACTION_ENTITY_CODE		=	'AP_INVOICES'
			--AND SL.TRANSACTION_SOURCE_ID_INT1	=	'1389193'
			AND AP.INVOICE_ID					IS  NULL				--If its already there, don't care
			AND (ACCOUNTED_CR-ACCOUNTED_DR)		!=	0					--If its 0, don't care
			AND SL.CODE_COMBINATION_ID			=	116001				--OPEXP = D.ACCOUNT.LVL 5 CODE
	) SL
	INNER JOIN svo.D_AP_INVOICE_HEADER	IH	ON	IH.INVOICE_ID	=	SL.TRANSACTION_SOURCE_ID_INT1
WHERE 1=1
	AND SL.TRANSACTION_SOURCE_ID_INT1	=	1389193
