/*
    Lamar DW - Alter script for svo GL amount columns
    Aligns silver table data types with bzo source (decimal(29,4)).
    Run against target database when source PVO columns have changed.
    Safe to run multiple times (idempotent for same target types).
*/

SET NOCOUNT ON;
GO

/* svo.D_GL_HEADER - running totals from bzo.GL_JournalHeaderExtractPVO */
ALTER TABLE svo.D_GL_HEADER ALTER COLUMN RUNNING_TOTAL_CR          decimal(29,4) NOT NULL;
ALTER TABLE svo.D_GL_HEADER ALTER COLUMN RUNNING_TOTAL_DR          decimal(29,4) NOT NULL;
ALTER TABLE svo.D_GL_HEADER ALTER COLUMN RUNNING_TOTAL_ACCOUNTED_CR decimal(29,4) NOT NULL;
ALTER TABLE svo.D_GL_HEADER ALTER COLUMN RUNNING_TOTAL_ACCOUNTED_DR decimal(29,4) NOT NULL;
ALTER TABLE svo.D_GL_HEADER ALTER COLUMN CR_DR_VARIANCE            decimal(29,4) NOT NULL;
GO

/* svo.F_GL_BALANCES - balance amounts from bzo.GL_BalanceExtractPVO
   Drop dependent indexes first (they INCLUDE these columns), alter, then recreate. */
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_BALANCES_COMPANY_SK' AND object_id = OBJECT_ID('svo.F_GL_BALANCES'))
    DROP INDEX IX_F_GL_BALANCES_COMPANY_SK ON svo.F_GL_BALANCES;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_BALANCES_ACCOUNT_SK' AND object_id = OBJECT_ID('svo.F_GL_BALANCES'))
    DROP INDEX IX_F_GL_BALANCES_ACCOUNT_SK ON svo.F_GL_BALANCES;
GO

ALTER TABLE svo.F_GL_BALANCES ALTER COLUMN BEGIN_BALANCE_AMT   decimal(29,4) NULL;
ALTER TABLE svo.F_GL_BALANCES ALTER COLUMN PERIOD_ACTIVITY_AMT  decimal(29,4) NULL;
ALTER TABLE svo.F_GL_BALANCES ALTER COLUMN END_BALANCE_AMT      decimal(29,4) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_BALANCES_COMPANY_SK' AND object_id = OBJECT_ID('svo.F_GL_BALANCES'))
    CREATE NONCLUSTERED INDEX IX_F_GL_BALANCES_COMPANY_SK ON svo.F_GL_BALANCES(COMPANY_SK)
    INCLUDE (ACCOUNT_SK, BUSINESS_OFFERING_SK, COST_CENTER_SK, INDUSTRY_SK, INTERCOMPANY_SK, LEDGER_SK, BALANCE_DATE_SK, BEGIN_BALANCE_AMT, PERIOD_ACTIVITY_AMT, END_BALANCE_AMT, CURRENCY_CODE) ON FG_SilverFact;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_BALANCES_ACCOUNT_SK' AND object_id = OBJECT_ID('svo.F_GL_BALANCES'))
    CREATE NONCLUSTERED INDEX IX_F_GL_BALANCES_ACCOUNT_SK ON svo.F_GL_BALANCES(ACCOUNT_SK)
    INCLUDE (BUSINESS_OFFERING_SK, COMPANY_SK, COST_CENTER_SK, INDUSTRY_SK, INTERCOMPANY_SK, LEDGER_SK, BALANCE_DATE_SK, BEGIN_BALANCE_AMT, PERIOD_ACTIVITY_AMT, END_BALANCE_AMT, CURRENCY_CODE) ON FG_SilverFact;
GO

/* svo.F_GL_LINES - already decimal(29,4) in DDL; included for completeness if needed */
-- ALTER TABLE svo.F_GL_LINES ALTER COLUMN ACCOUNTED_CR   decimal(29,4) NULL;
-- ALTER TABLE svo.F_GL_LINES ALTER COLUMN ACCOUNTED_DR   decimal(29,4) NULL;
-- ALTER TABLE svo.F_GL_LINES ALTER COLUMN AMOUNT_USD     decimal(29,4) NULL;
-- ALTER TABLE svo.F_GL_LINES ALTER COLUMN AMOUNT_LOCAL   decimal(29,4) NULL;
-- GO

PRINT 'Alter_svo_GL_DecimalColumns.sql completed.';
GO
