/*
    Index definitions for Lamar data warehouse (svo schema)
    Source: g.sql DDL from DW_BronzeSilver_PROD
    Idempotent: IF NOT EXISTS ... CREATE (safe to run repeatedly)
    Database-agnostic: database set by connection.
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

/* ========
   D_ACCOUNT
   ======== */
--  Unique lookup on BK
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_ACCOUNT_ID' AND object_id = OBJECT_ID('svo.D_ACCOUNT'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_ACCOUNT_ID ON svo.D_ACCOUNT(ACCOUNT_ID) ON FG_SilverDim;
END

/* ========
   D_AP_DISBURSEMENT_HEADER
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_AP_DISBURSEMENT_HEADER_CHECK_ID' AND object_id = OBJECT_ID('svo.D_AP_DISBURSEMENT_HEADER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_AP_DISBURSEMENT_HEADER_CHECK_ID ON svo.D_AP_DISBURSEMENT_HEADER(CHECK_ID) ON FG_SilverFact;
END

/* ========
   D_AP_INVOICE_HEADER
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_AP_INVOICE_HEADER_INVOICE_ID' AND object_id = OBJECT_ID('svo.D_AP_INVOICE_HEADER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_AP_INVOICE_HEADER_INVOICE_ID ON svo.D_AP_INVOICE_HEADER(INVOICE_ID) ON FG_SilverDim;
END

/* ========
   D_BUSINESS_OFFERING
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_OFFERING_ID' AND object_id = OBJECT_ID('svo.D_BUSINESS_OFFERING'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_OFFERING_ID ON svo.D_BUSINESS_OFFERING(BUSINESS_OFFERING_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_OFFERING_ID_CURR' AND object_id = OBJECT_ID('svo.D_BUSINESS_OFFERING'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_OFFERING_ID_CURR ON svo.D_BUSINESS_OFFERING(BUSINESS_OFFERING_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_BUSINESS_UNIT
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_UNIT_BK_CURR' AND object_id = OBJECT_ID('svo.D_BUSINESS_UNIT'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_UNIT_BK_CURR ON svo.D_BUSINESS_UNIT(BUSINESS_UNIT_ID)
    WHERE (CURR_IND='Y') ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_BUSINESS_UNIT_ID_CURR' AND object_id = OBJECT_ID('svo.D_BUSINESS_UNIT'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_UNIT_ID_CURR ON svo.D_BUSINESS_UNIT(BUSINESS_UNIT_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_CALENDAR (fiscal dimension; DATE_SK is PK, unique on DATE for lookups)
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_CALENDAR_DATE' AND object_id = OBJECT_ID('svo.D_CALENDAR'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_CALENDAR_DATE ON svo.D_CALENDAR([DATE]) ON FG_SilverDim;
END

/* ========
   D_COMPANY
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_ID' AND object_id = OBJECT_ID('svo.D_COMPANY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COMPANY_ID ON svo.D_COMPANY(COMPANY_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COMPANY_ID_CURR' AND object_id = OBJECT_ID('svo.D_COMPANY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COMPANY_ID_CURR ON svo.D_COMPANY(COMPANY_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_COST_CENTER
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COST_CENTER_ID' AND object_id = OBJECT_ID('svo.D_COST_CENTER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COST_CENTER_ID ON svo.D_COST_CENTER(COST_CENTER_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COST_CENTER_ID_CURR' AND object_id = OBJECT_ID('svo.D_COST_CENTER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COST_CENTER_ID_CURR ON svo.D_COST_CENTER(COST_CENTER_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_CURRENCY
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_CURRENCY_ID' AND object_id = OBJECT_ID('svo.D_CURRENCY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_CURRENCY_ID ON svo.D_CURRENCY(CURRENCY_ID) ON FG_SilverDim;
END

/* ========
   D_GL_HEADER
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_D_GL_HEADER_LEDGER_SK_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_D_GL_HEADER_LEDGER_SK_CURR ON svo.D_GL_HEADER(LEDGER_SK, CURR_IND) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID ON svo.D_GL_HEADER(JE_HEADER_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_GL_HEADER_JE_HEADER_ID_CURR' AND object_id = OBJECT_ID('svo.D_GL_HEADER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_GL_HEADER_JE_HEADER_ID_CURR ON svo.D_GL_HEADER(JE_HEADER_ID)
    WHERE (CURR_IND='Y') ON FG_SilverDim;
END

/* ========
   D_INDUSTRY
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_INDUSTRY_ID' AND object_id = OBJECT_ID('svo.D_INDUSTRY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INDUSTRY_ID ON svo.D_INDUSTRY(INDUSTRY_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_INDUSTRY_ID_CURR' AND object_id = OBJECT_ID('svo.D_INDUSTRY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INDUSTRY_ID_CURR ON svo.D_INDUSTRY(INDUSTRY_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_INTERCOMPANY
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_INTERCOMPANY_ID' AND object_id = OBJECT_ID('svo.D_INTERCOMPANY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INTERCOMPANY_ID ON svo.D_INTERCOMPANY(INTERCOMPANY_ID) ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_INTERCOMPANY_ID_CURR' AND object_id = OBJECT_ID('svo.D_INTERCOMPANY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INTERCOMPANY_ID_CURR ON svo.D_INTERCOMPANY(INTERCOMPANY_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_LEDGER
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_LEDGER_ID_CURR' AND object_id = OBJECT_ID('svo.D_LEDGER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_LEDGER_ID_CURR ON svo.D_LEDGER(LEDGER_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_LEDGER_BK_CURR' AND object_id = OBJECT_ID('svo.D_LEDGER'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_LEDGER_BK_CURR ON svo.D_LEDGER(LEDGER_ID)
    WHERE (CURR_IND='Y') ON FG_SilverDim;
END

/* ========
   D_LEGAL_ENTITY
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_LEGAL_ENTITY_ID_CURR' AND object_id = OBJECT_ID('svo.D_LEGAL_ENTITY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_LEGAL_ENTITY_ID_CURR ON svo.D_LEGAL_ENTITY(LEGAL_ENTITY_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_PAYMENT_METHOD
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_PAYMENT_METHOD_ID_CURR' AND object_id = OBJECT_ID('svo.D_PAYMENT_METHOD'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_PAYMENT_METHOD_ID_CURR ON svo.D_PAYMENT_METHOD(PAYMENT_METHOD_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_PAYMENT_TERM
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_PAYMENT_TERM_ID_CURR' AND object_id = OBJECT_ID('svo.D_PAYMENT_TERM'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_PAYMENT_TERM_ID_CURR ON svo.D_PAYMENT_TERM(PAYMENT_TERM_ID)
    WHERE (CURR_IND='Y' AND END_DATE='9999-12-31') ON FG_SilverDim;
END

/* ========
   D_PARTY_CONTACT_POINT (SCD2; unique on BK for current row)
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_PARTY_CONTACT_POINT_BK_CURR' AND object_id = OBJECT_ID('svo.D_PARTY_CONTACT_POINT'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_PARTY_CONTACT_POINT_BK_CURR ON svo.D_PARTY_CONTACT_POINT(CONTACT_POINT_ID)
    WHERE (CURR_IND = 'Y') ON FG_SilverDim;
END

/* ========
   D_PARTY_SITE (SCD2; unique on BK for current row)
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_PARTY_SITE_BK_CURR' AND object_id = OBJECT_ID('svo.D_PARTY_SITE'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_PARTY_SITE_BK_CURR ON svo.D_PARTY_SITE(PARTY_SITE_ID)
    WHERE (CURR_IND = 'Y') ON FG_SilverDim;
END

/* ========
   D_VENDOR_SITE
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_VENDOR_SITE_VENDOR_SITE_ID' AND object_id = OBJECT_ID('svo.D_VENDOR_SITE'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_VENDOR_SITE_VENDOR_SITE_ID ON svo.D_VENDOR_SITE(VENDOR_SITE_ID) ON FG_SilverDim;
END

/* ========
   F_AP_AGING_SNAPSHOT
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_AGING_SNAPSHOT_SNAPDT_ACCTSK_ETC' AND object_id = OBJECT_ID('svo.F_AP_AGING_SNAPSHOT'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_AGING_SNAPSHOT_SNAPDT_ACCTSK_ETC ON svo.F_AP_AGING_SNAPSHOT
    (SNAPSHOT_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK)
    INCLUDE (ORIGINAL_AMOUNT, AMOUNT_PAID, AMOUNT_REMAINING, DAYS_PAST_DUE, AGING_BUCKET_CODE)
    ON FG_SilverFact;
END

/* ========
   F_AP_INVOICE_LINE_DISTRIBUTION
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_INV_LINE_DISTDT_ACCTSK_ETC' AND object_id = OBJECT_ID('svo.F_AP_INVOICE_LINE_DISTRIBUTION'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_INV_LINE_DISTDT_ACCTSK_ETC ON svo.F_AP_INVOICE_LINE_DISTRIBUTION
    (DIST_ACCOUNTING_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK)
    INCLUDE (DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG)
    ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_INV_LINE_INV_HEADER_ACCTSK_ETC' AND object_id = OBJECT_ID('svo.F_AP_INVOICE_LINE_DISTRIBUTION'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_INV_LINE_INV_HEADER_ACCTSK_ETC ON svo.F_AP_INVOICE_LINE_DISTRIBUTION
    (AP_INVOICE_HEADER_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK)
    INCLUDE (DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG, TYPE_1099)
    ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_F_AP_INV_LINE_INVOICE_DISTRIBUTION_ID' AND object_id = OBJECT_ID('svo.F_AP_INVOICE_LINE_DISTRIBUTION'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_F_AP_INV_LINE_INVOICE_DISTRIBUTION_ID ON svo.F_AP_INVOICE_LINE_DISTRIBUTION(INVOICE_DISTRIBUTION_ID) ON FG_SilverFact;
END

/* ========
   F_AP_INVOICE_LINE_DISTRIBUTION_V2
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_INV_LINE_V2_DISTDT_ACCTSK_ETC' AND object_id = OBJECT_ID('svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_INV_LINE_V2_DISTDT_ACCTSK_ETC ON svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2
    (DIST_ACCOUNTING_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK)
    INCLUDE (DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG, IS_ORIG_AP_INV)
    ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_INV_LINE_V2_INV_HEADER_ACCTSK_ETC' AND object_id = OBJECT_ID('svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_INV_LINE_V2_INV_HEADER_ACCTSK_ETC ON svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2
    (AP_INVOICE_HEADER_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK)
    INCLUDE (DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG, TYPE_1099, IS_ORIG_AP_INV)
    ON FG_SilverFact;
END

/* ========
   F_AP_PAYMENTS
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_PAYMENTS_ACCT_DATE' AND object_id = OBJECT_ID('svo.F_AP_PAYMENTS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_PAYMENTS_ACCT_DATE ON svo.F_AP_PAYMENTS
    (ACCOUNTING_DATE_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK, LEDGER_SK)
    INCLUDE (AP_INVOICE_PAYMENTS_ALL_CHECK_ID, AP_CHECKS_ALL_CHECK_NUMBER, AP_INVOICE_PAYMENTS_ALL_AMOUNT, AP_CHECKS_ALL_AMOUNT, INV_CURRENCY_SK, PAY_CURRENCY_SK)
    ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_AP_PAYMENTS_CHECK' AND object_id = OBJECT_ID('svo.F_AP_PAYMENTS'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_AP_PAYMENTS_CHECK ON svo.F_AP_PAYMENTS(AP_INVOICE_PAYMENTS_ALL_CHECK_ID)
    INCLUDE (AP_CHECKS_ALL_CHECK_NUMBER, AP_INVOICE_PAYMENTS_ALL_INVOICE_PAYMENT_ID, ACCOUNTING_DATE_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK, LEDGER_SK, AP_INVOICE_PAYMENTS_ALL_AMOUNT, AP_CHECKS_ALL_AMOUNT)
    ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_F_AP_PAYMENTS_INVOICE_PAYMENT_ID' AND object_id = OBJECT_ID('svo.F_AP_PAYMENTS'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_F_AP_PAYMENTS_INVOICE_PAYMENT_ID ON svo.F_AP_PAYMENTS(AP_INVOICE_PAYMENTS_ALL_INVOICE_PAYMENT_ID)
    INCLUDE (AP_INVOICE_HEADER_SK, AP_DISBURSEMENT_HEADER_SK, AP_INVOICE_PAYMENTS_ALL_CHECK_ID, ACCOUNTING_DATE_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK, LEDGER_SK, AP_INVOICE_PAYMENTS_ALL_AMOUNT, AP_CHECKS_ALL_AMOUNT)
    ON FG_SilverFact;
END

/* ========
   F_GL_BALANCES
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_F_GL_BALANCES_NK' AND object_id = OBJECT_ID('svo.F_GL_BALANCES'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_F_GL_BALANCES_NK ON svo.F_GL_BALANCES(LEDGER_SK, BALANCE_DATE_SK, CODE_COMBINATION_ID, CURRENCY_CODE, PERIOD_NUMBER) ON FG_SilverFact;
END

/* ========
   F_GL_LINES
   ======== */
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_LINES_JE_HEADER_LINE' AND object_id = OBJECT_ID('svo.F_GL_LINES'))
    DROP INDEX IX_F_GL_LINES_JE_HEADER_LINE ON svo.F_GL_LINES;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_LINES_GL_HEADER_LINE' AND object_id = OBJECT_ID('svo.F_GL_LINES'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_GL_LINES_GL_HEADER_LINE ON svo.F_GL_LINES(GL_HEADER_SK, LINE_NUM) ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_GL_LINES_EFFDT_ACCTSK_COSK_ETC' AND object_id = OBJECT_ID('svo.F_GL_LINES'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_GL_LINES_EFFDT_ACCTSK_COSK_ETC ON svo.F_GL_LINES
    (EFFECTIVE_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, INDUSTRY_SK, COST_CENTER_SK, INTERCOMPANY_SK)
    INCLUDE (DESCRIPTION, ACCOUNTED_CR, ACCOUNTED_DR, AMOUNT_USD, AMOUNT_LOCAL)
    ON FG_SilverFact;
END

/* ========
   F_OS_BUDGET
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_OS_BUDGET_ACCTSK_COSK_ETC' AND object_id = OBJECT_ID('svo.F_OS_BUDGET'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_OS_BUDGET_ACCTSK_COSK_ETC ON svo.F_OS_BUDGET
    (BUDGET_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, COST_CENTER_SK)
    INCLUDE (AMOUNT)
    ON FG_SilverFact;
END

/* ========
   F_SL_JOURNAL_DISTRIBUTION
   ======== */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_F_SL_JOURNAL_DIST_AE_HEADER' AND object_id = OBJECT_ID('svo.F_SL_JOURNAL_DISTRIBUTION'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_F_SL_JOURNAL_DIST_AE_HEADER ON svo.F_SL_JOURNAL_DISTRIBUTION(AE_HEADER_ID, REF_AE_HEADER_ID, TEMP_LINE_NUM) ON FG_SilverFact;
END
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_F_SL_JOURNAL_DIST_ACCTDT_DIM' AND object_id = OBJECT_ID('svo.F_SL_JOURNAL_DISTRIBUTION'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_F_SL_JOURNAL_DIST_ACCTDT_DIM ON svo.F_SL_JOURNAL_DISTRIBUTION
    (ACCOUNTING_DATE_SK, ACCOUNT_SK, COMPANY_SK, BUSINESS_OFFERING_SK, COST_CENTER_SK, INDUSTRY_SK, INTERCOMPANY_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK)
    INCLUDE (ACCOUNTED_DR, ACCOUNTED_CR, LINE_DESCRIPTION, AE_HEADER_ID, REF_AE_HEADER_ID)
    ON FG_SilverFact;
END

/* ========
   LINES_CODE_COMBO_LOOKUP
   ======== */
--  Unique lookup on BK
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_LINES_CODE_COMBO_LOOKUP_BK' AND object_id = OBJECT_ID('svo.LINES_CODE_COMBO_LOOKUP'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_LINES_CODE_COMBO_LOOKUP_BK ON svo.LINES_CODE_COMBO_LOOKUP(CODE_COMBINATION_BK) ON FG_SilverMisc;
END
GO
