-- Rebuild Dimensions from scratch. EVERYTHING WILL BE REPLACED! ---

 
 /* ========
   ACCOUNT
   ======== */
IF OBJECT_ID(N'Oracle_Reporting_P2.svo.D_ACCOUNT', 'U') IS NOT NULL
    DROP TABLE Oracle_Reporting_P2.svo.D_ACCOUNT;
GO

CREATE TABLE Oracle_Reporting_P2.svo.D_ACCOUNT
(
    ACCOUNT_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ACCOUNT_ID        VARCHAR(100) NOT NULL,
    ACCOUNT_LVL1_CODE VARCHAR(100) NULL,
    ACCOUNT_LVL1_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL2_CODE VARCHAR(25) NULL,
    ACCOUNT_LVL2_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL3_CODE VARCHAR(25) NULL,
    ACCOUNT_LVL3_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL4_CODE VARCHAR(150) NULL,
    ACCOUNT_LVL4_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL5_CODE VARCHAR(100) NULL,
    ACCOUNT_LVL5_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL6_CODE VARCHAR(25) NULL,
    ACCOUNT_LVL6_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL7_CODE VARCHAR(25) NULL,
    ACCOUNT_LVL7_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL8_CODE VARCHAR(150) NULL,
    ACCOUNT_LVL8_DESC VARCHAR(500) NULL,
    ACCOUNT_LVL9_CODE VARCHAR(150) NULL,
    ACCOUNT_LVL9_DESC VARCHAR(500) NULL,
    ACCOUNT_DISTANCE  SMALLINT NULL,
    ACCOUNT_CATEGORY  VARCHAR(60) NULL,
    ACCOUNT_ENABLED_FLAG VARCHAR(4) NULL,
    START_DATE_ACTIVE    DATE NOT NULL,
    END_DATE_ACTIVE      DATE NOT NULL,
    CREATED_BY           VARCHAR(64) NULL,
    CREATION_DATE        DATE NULL,
    BZ_LOAD_DATE         DATE NULL,
    SV_LOAD_DATE         DATE NULL
) ON FG_SilverDim;
GO

TRUNCATE TABLE Oracle_Reporting_P2.svo.D_ACCOUNT;
GO

INSERT INTO Oracle_Reporting_P2.svo.D_ACCOUNT (
     ACCOUNT_ID,
     ACCOUNT_LVL1_CODE,
     ACCOUNT_LVL1_DESC,
     ACCOUNT_LVL2_CODE,
     ACCOUNT_LVL2_DESC,
     ACCOUNT_LVL3_CODE,
     ACCOUNT_LVL3_DESC,
     ACCOUNT_LVL4_CODE,
     ACCOUNT_LVL4_DESC,
     ACCOUNT_LVL5_CODE,
     ACCOUNT_LVL5_DESC,
     ACCOUNT_LVL6_CODE,
     ACCOUNT_LVL6_DESC,
     ACCOUNT_LVL7_CODE,
     ACCOUNT_LVL7_DESC,
     ACCOUNT_LVL8_CODE,
     ACCOUNT_LVL8_DESC,
     ACCOUNT_LVL9_CODE,
     ACCOUNT_LVL9_DESC,
     ACCOUNT_DISTANCE,
     ACCOUNT_CATEGORY,
     ACCOUNT_ENABLED_FLAG,
     START_DATE_ACTIVE,
     END_DATE_ACTIVE,
     CREATED_BY,
     CREATION_DATE,
     BZ_LOAD_DATE,
     SV_LOAD_DATE 
)
SELECT distinct
    ISNULL(TRIM(lvl9.VALUE),'-1') AS ACCOUNT_ID,
    COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL1_CODE,
    COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION)  AS ACCOUNT_LVL1_DESC,
    COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL2_CODE,
    COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION)  AS ACCOUNT_LVL2_DESC,
    COALESCE(h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL3_CODE,
    COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION)  AS ACCOUNT_LVL3_DESC,
    COALESCE(h1.DEP28PK1VALUE,h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL4_CODE,
    COALESCE(lvl4.DESCRIPTION,lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION)  AS ACCOUNT_LVL4_DESC,
    COALESCE(h1.DEP27PK1VALUE,h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL5_CODE,
    COALESCE(lvl5.DESCRIPTION,lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION)  AS ACCOUNT_LVL5_DESC,
    COALESCE(h1.DEP26PK1VALUE,h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL6_CODE,
    COALESCE(lvl6.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION) AS ACCOUNT_LVL6_DESC,
    COALESCE(h1.DEP25PK1VALUE,h1.DEP24PK1VALUE,lvl9.VALUE) AS ACCOUNT_LVL7_CODE,
    COALESCE(lvl7.DESCRIPTION,lvl8.DESCRIPTION,lvl9.DESCRIPTION) AS ACCOUNT_LVL7_DESC,
    COALESCE(h1.DEP24PK1VALUE,lvl9.VALUE)  AS ACCOUNT_LVL8_CODE,
    COALESCE(lvl8.DESCRIPTION,lvl9.DESCRIPTION) AS ACCOUNT_LVL8_DESC,
    lvl9.VALUE       AS ACCOUNT_LVL9_CODE,
    lvl9.DESCRIPTION AS ACCOUNT_LVL9_DESC,
    0                  AS ACCOUNT_DISTANCE,
    lvl9.ATTRIBUTECATEGORY AS ACCOUNT_CATEGORY,
    lvl9.ENABLEDFLAG AS ACCOUNT_ENABLED_FLAG,
    ISNULL(lvl9.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
    ISNULL(lvl9.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
    lvl9.CREATEDBY AS CREATED_BY,
    CAST(lvl9.CREATIONDATE AS DATE) AS CREATION_DATE,
    CAST(MAX(H1.AddDateTime) OVER () AS DATE) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM DW_BronzeSilver_PROD.bzo.GL_SegmentValueHierarchyExtractPVO h1 
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_FndTreeAndVersionVO ver1 
    ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP28PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl5 ON lvl5.VALUE = h1.DEP27PK1VALUE AND lvl5.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl6 ON lvl6.VALUE = h1.DEP26PK1VALUE AND lvl6.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl7 ON lvl7.VALUE = h1.DEP25PK1VALUE AND lvl7.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl8 ON lvl8.VALUE = h1.DEP24PK1VALUE AND lvl8.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
RIGHT JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl9 ON lvl9.VALUE = h1.DEP0PK1VALUE AND lvl9.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR'
WHERE lvl9.ATTRIBUTECATEGORY = 'ACCOUNT LAMAR' AND lvl9.SUMMARYFLAG = 'N';
GO


 


--  Ensure SK=0 Unknown row exists
IF NOT EXISTS (SELECT 1 FROM Oracle_Reporting_P2.svo.D_ACCOUNT WHERE ACCOUNT_SK = 0)
BEGIN
    SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_ACCOUNT ON;

    INSERT INTO Oracle_Reporting_P2.svo.D_ACCOUNT (ACCOUNT_SK,ACCOUNT_ID,ACCOUNT_LVL1_CODE,ACCOUNT_LVL1_DESC,ACCOUNT_LVL2_CODE,
                ACCOUNT_LVL2_DESC,ACCOUNT_LVL3_CODE,ACCOUNT_LVL3_DESC,ACCOUNT_LVL4_CODE,ACCOUNT_LVL4_DESC,
                ACCOUNT_LVL5_CODE,ACCOUNT_LVL5_DESC,ACCOUNT_LVL6_CODE,ACCOUNT_LVL6_DESC,ACCOUNT_LVL7_CODE,
                ACCOUNT_LVL7_DESC,ACCOUNT_LVL8_CODE,ACCOUNT_LVL8_DESC,ACCOUNT_LVL9_CODE,ACCOUNT_LVL9_DESC,
                ACCOUNT_DISTANCE,ACCOUNT_CATEGORY,ACCOUNT_ENABLED_FLAG,START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,CREATION_DATE) 
    VALUES (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1',
            'Unknown','-1','Unknown',0,'Missing','NULL','0001-01-01','9999-12-31','GJR','2025-10-18');

    SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_ACCOUNT OFF;
END
GO
