
/* =============
   INTERCOMPANY
   ============= */
IF OBJECT_ID(N'Oracle_Reporting_P2.svo.D_INTERCOMPANY', 'U') IS NOT NULL
    DROP TABLE Oracle_Reporting_P2.svo.D_INTERCOMPANY;
GO

CREATE TABLE Oracle_Reporting_P2.svo.D_INTERCOMPANY
(
    INTERCOMPANY_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    INTERCOMPANY_ID        VARCHAR(100) NOT NULL,
    INTERCOMPANY_LVL1_CODE VARCHAR(100) NULL,
    INTERCOMPANY_LVL1_DESC VARCHAR(500) NULL,
    INTERCOMPANY_LVL2_CODE VARCHAR(25) NULL,
    INTERCOMPANY_LVL2_DESC VARCHAR(500) NULL,
    INTERCOMPANY_LVL3_CODE VARCHAR(25) NULL,
    INTERCOMPANY_LVL3_DESC VARCHAR(500) NULL,
    INTERCOMPANY_DISTANCE  SMALLINT NULL,
    INTERCOMPANY_CATEGORY  VARCHAR(60) NULL,
    INTERCOMPANY_ENABLED_FLAG VARCHAR(4) NULL,
    START_DATE_ACTIVE     DATE NOT NULL,
    END_DATE_ACTIVE       DATE NOT NULL,
    CREATED_BY            VARCHAR(64) NULL,
    CREATION_DATE         DATE NULL,
    BZ_LOAD_DATE          DATE NULL,
    SV_LOAD_DATE          DATE NULL
) ON FG_SilverDim;
GO

TRUNCATE TABLE Oracle_Reporting_P2.svo.D_INTERCOMPANY;
GO

INSERT INTO Oracle_Reporting_P2.svo.D_INTERCOMPANY (
     INTERCOMPANY_ID,
     INTERCOMPANY_LVL1_CODE,
     INTERCOMPANY_LVL1_DESC,
     INTERCOMPANY_LVL2_CODE,
     INTERCOMPANY_LVL2_DESC,
     INTERCOMPANY_LVL3_CODE,
     INTERCOMPANY_LVL3_DESC,
     INTERCOMPANY_DISTANCE,
     INTERCOMPANY_CATEGORY,
     INTERCOMPANY_ENABLED_FLAG,
     START_DATE_ACTIVE,
     END_DATE_ACTIVE,
     CREATED_BY,
     CREATION_DATE,
     BZ_LOAD_DATE,
     SV_LOAD_DATE
)
SELECT
    ISNULL(TRIM(lvl3.VALUE),'-1') AS INTERCOMPANY_ID,
    COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,lvl3.VALUE) AS INTERCOMPANY_LVL1_CODE,
    COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION) AS INTERCOMPANY_LVL1_DESC,
    COALESCE(h1.DEP30PK1VALUE,lvl3.VALUE) AS INTERCOMPANY_LVL2_CODE,
    COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION) AS INTERCOMPANY_LVL2_DESC,
    lvl3.VALUE       AS INTERCOMPANY_LVL3_CODE,
    lvl3.DESCRIPTION AS INTERCOMPANY_LVL3_DESC,
    0                  AS INTERCOMPANY_DISTANCE,
    lvl3.ATTRIBUTECATEGORY AS INTERCOMPANY_CATEGORY,
    lvl3.ENABLEDFLAG AS INTERCOMPANY_ENABLED_FLAG,
    ISNULL(lvl3.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
    ISNULL(lvl3.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
    lvl3.CREATEDBY AS CREATED_BY,
    CAST(lvl3.CREATIONDATE AS DATE) AS CREATION_DATE,
    COALESCE(CAST(h1.AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM DW_BronzeSilver_PROD.bzo.GL_SegmentValueHierarchyExtractPVO h1 
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_FndTreeAndVersionVO ver1 
    ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'INTERCOMPANY LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'INTERCOMPANY LAMAR'
INNER JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'INTERCOMPANY LAMAR'
RIGHT JOIN DW_BronzeSilver_PROD.bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP0PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'INTERCOMPANY LAMAR'
WHERE lvl3.ATTRIBUTECATEGORY = 'INTERCOMPANY LAMAR' AND lvl3.SUMMARYFLAG = 'N';
GO




/* =========================
   INTERCOMPANY
   ========================= */
--IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_INTERCOMPANY_ID' AND object_id = OBJECT_ID('Oracle_Reporting_P2.svo.D_INTERCOMPANY'))
--BEGIN
--    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INTERCOMPANY_ID ON Oracle_Reporting_P2.svo.D_INTERCOMPANY(INTERCOMPANY_ID) ON FG_SilverDim;
--END

IF NOT EXISTS (SELECT 1 FROM Oracle_Reporting_P2.svo.D_INTERCOMPANY WHERE INTERCOMPANY_SK = 0)
BEGIN
    SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_INTERCOMPANY ON;

    INSERT INTO Oracle_Reporting_P2.svo.D_INTERCOMPANY (INTERCOMPANY_SK,INTERCOMPANY_ID,INTERCOMPANY_LVL1_CODE,INTERCOMPANY_LVL1_DESC,INTERCOMPANY_LVL2_CODE,
            INTERCOMPANY_LVL2_DESC,INTERCOMPANY_LVL3_CODE,INTERCOMPANY_LVL3_DESC,INTERCOMPANY_DISTANCE,INTERCOMPANY_CATEGORY,
            INTERCOMPANY_ENABLED_FLAG,START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,CREATION_DATE) 
    VALUES (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown',0,'Missing','NULL','0001-01-01','9999-12-31','UNK','2025-10-18');

    SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_INTERCOMPANY OFF;
END
GO

 