
--/* ====
--   DATE
--   ==== */
IF OBJECT_ID(N'Oracle_Reporting_P2.svo.D_CALENDAR', 'U') IS NOT NULL
    DROP TABLE Oracle_Reporting_P2.svo.D_CALENDAR;
GO

CREATE TABLE Oracle_Reporting_P2.svo.D_CALENDAR
(
    DATE_SK                          INT             NOT NULL PRIMARY KEY,
    DATE                             DATE            NULL,
    DAY_OF_WEEK                      INT             NULL,
    PERIOD_ID                        INT             NULL,
    PERIOD_NUMBER             INT             NULL,
    PERIOD_NAME               NVARCHAR(25)    NULL,
    PERIOD_START_DATE         DATE            NULL,
    PERIOD_END_DATE           DATE            NULL,
    PERIOD_TYPE               NVARCHAR(25)    NULL,
    QUARTER_NUMBER            INT             NULL,
    QUARTER_START_DATE        DATE            NULL,
    QUARTER_END_DATE          DATE            NULL,
    YEAR_NUMBER               INT             NULL,
    YEAR_START_DATE           DATE            NULL,
    YEAR_END_DATE             DATE            NULL,
    JULIAN_DATE                      INT             NULL,
    LAST_UPDATE_DATE                 DATE            NULL,
    OBJECT_VERSION_NUMBER            INT             NULL,
    CALENDAR_ID                      NVARCHAR(25)    NULL,
    GL_CALENDARS_USER_PERIOD_SET_NAME NVARCHAR(25)   NULL,
    BZ_LOAD_DATE                     DATE            NULL,
    SV_LOAD_DATE                     DATE            NULL
) ON FG_SilverDim;

TRUNCATE TABLE Oracle_Reporting_P2.svo.D_CALENDAR;

INSERT INTO Oracle_Reporting_P2.svo.D_CALENDAR (
    DATE_SK,
    DATE,
    DAY_OF_WEEK,
    PERIOD_ID,
    PERIOD_NUMBER,
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    QUARTER_NUMBER,
    QUARTER_START_DATE,
    QUARTER_END_DATE,
    YEAR_NUMBER,
    YEAR_START_DATE,
    YEAR_END_DATE,
    JULIAN_DATE,
    PERIOD_TYPE,
    LAST_UPDATE_DATE,
    OBJECT_VERSION_NUMBER,
    CALENDAR_ID,
    GL_CALENDARS_USER_PERIOD_SET_NAME,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)SELECT DISTINCT 
        CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, D.REPORTDATE), 112) AS INT) AS DATE_SK,
        CAST(D.REPORTDATE AS DATE) AS DATE,
        D.DAYOFWEEK,
        CAST(FORMAT(D.REPORTDATE, 'yyyyMM') AS INT) AS PERIOD_ID,
        D.FISCALPERIODNUMBER,
        D.FISCALPERIODNAME,
        CAST(D.FISCALPERIODSTARTDATE AS DATE),
        CAST(D.FISCALPERIODENDDATE AS DATE),
        D.FISCALQUARTERNUMBER,
        CAST(D.FISCALQUARTERSTARTDATE AS DATE),
        CAST(D.FISCALQUARTERENDDATE AS DATE),
        CAST(P.PERIODPERIODYEAR AS INT),
        CAST(D.FISCALYEARSTARTDATE AS DATE),
        CAST(D.FISCALYEARENDDATE AS DATE),
        D.JULIANDATE,
        D.FISCALPERIODTYPE,
        CAST(D.LASTUPDATEDATE AS DATE),
        P.PERIODOBJECTVERSIONNUMBER,
        D.GLCALENDARSCALENDARID,
        D.GLCALENDARSUSERPERIODSETNAME,
        CAST(D.AddDateTime AS DATE),
        CAST(GETDATE() AS DATE)
FROM DW_BronzeSilver_PROD.bzo.GL_FiscalDayPVO D
JOIN DW_BronzeSilver_PROD.bzo.GL_FiscalPeriodExtractPVO P
  ON D.FISCALPERIODNAME = P.PERIODPERIODNAME
WHERE D.FISCALPERIODADJUSTMENTPERIODFLAG = 'N'
  AND P.PERIODADJUSTMENTPERIODFLAG = 'N'
  AND D.GlCalendarsUserPeriodSetName = 'LAMAR CAL'
;
GO

/* =========================
   DATE DIM — keep DATE_BK as the surrogate
   ========================= */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_CALENDAR_DATE_BK' AND object_id = OBJECT_ID('Oracle_Reporting_P2.svo.D_CALENDAR'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_CALENDAR_DATE_BK ON Oracle_Reporting_P2.svo.D_CALENDAR(DATE_SK) ON FG_SilverDim;
END

-- Plug date row DATE_BK = 0
IF NOT EXISTS (SELECT 1 FROM Oracle_Reporting_P2.svo.D_CALENDAR WHERE DATE_SK = 0)
BEGIN
    INSERT INTO Oracle_Reporting_P2.svo.D_CALENDAR
    (DATE_SK, DATE, DAY_OF_WEEK, PERIOD_NUMBER,PERIOD_NAME,PERIOD_START_DATE,PERIOD_END_DATE,
    QUARTER_NUMBER,QUARTER_START_DATE,QUARTER_END_DATE,YEAR_NUMBER,YEAR_START_DATE,
    YEAR_END_DATE,JULIAN_DATE,PERIOD_TYPE,LAST_UPDATE_DATE,OBJECT_VERSION_NUMBER,CALENDAR_ID,GL_CALENDARS_USER_PERIOD_SET_NAME, BZ_LOAD_DATE, SV_LOAD_DATE)
    VALUES
    (10101, '0001-01-01', NULL, NULL, 'Unknown', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, NULL, NULL, NULL, GETDATE(), GETDATE());

    INSERT INTO Oracle_Reporting_P2.svo.D_CALENDAR
    (DATE_SK, DATE, DAY_OF_WEEK, PERIOD_NUMBER,PERIOD_NAME,PERIOD_START_DATE,PERIOD_END_DATE,
    QUARTER_NUMBER,QUARTER_START_DATE,QUARTER_END_DATE,YEAR_NUMBER,YEAR_START_DATE,
    YEAR_END_DATE,JULIAN_DATE,PERIOD_TYPE,LAST_UPDATE_DATE,OBJECT_VERSION_NUMBER,CALENDAR_ID,GL_CALENDARS_USER_PERIOD_SET_NAME, BZ_LOAD_DATE, SV_LOAD_DATE)
    VALUES
    (99991231, '9999-12-31', NULL, NULL, 'Unknown', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, NULL, NULL, NULL, GETDATE(), GETDATE());

END
GO