
--/* ========
--   CURRENCY
--   ======== */
IF OBJECT_ID(N'Oracle_Reporting_P2.svo.D_CURRENCY', 'U') IS NOT NULL
    DROP TABLE Oracle_Reporting_P2.svo.D_CURRENCY;
GO

CREATE TABLE Oracle_Reporting_P2.svo.D_CURRENCY(
    CURRENCY_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CURRENCY_ID        VARCHAR(50) NOT NULL,
    CURRENCY_CODE_FROM VARCHAR(5) NOT NULL,
    CURRENCY_CODE_TO   VARCHAR(5) NOT NULL,
    CURRENCY_CONV_DATE DATE NOT NULL,
    CURRENCY_CONV_RATE NUMERIC(18,4),
    CURRENCY_CONV_TYPE VARCHAR(25),
    CURRENCY_CONV_STATUS VARCHAR(1),
    BZ_LOAD_DATE        DATE,
    SV_LOAD_DATE        DATE
) ON FG_SilverDim;
GO

TRUNCATE TABLE Oracle_Reporting_P2.svo.D_CURRENCY;
GO

IF NOT EXISTS (SELECT * FROM Oracle_Reporting_P2.svo.D_CURRENCY WHERE CURRENCY_SK = 0)
BEGIN
	SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_CURRENCY ON;

		INSERT INTO Oracle_Reporting_P2.svo.D_CURRENCY(
			CURRENCY_SK,
			CURRENCY_ID,
			CURRENCY_CODE_FROM,
            CURRENCY_CODE_TO,
			CURRENCY_CONV_DATE,
			CURRENCY_CONV_RATE,
			CURRENCY_CONV_TYPE,
            CURRENCY_CONV_STATUS,
            BZ_LOAD_DATE,
            SV_LOAD_DATE
        )
		VALUES
		(0,-1,'UNK','UNK','0001-01-01',1,'UNK','U','0001-01-01',CAST(GETDATE() AS DATE))
		
	SET IDENTITY_INSERT Oracle_Reporting_P2.svo.D_CURRENCY OFF;
END

INSERT INTO Oracle_Reporting_P2.svo.D_CURRENCY(
    CURRENCY_ID,
    CURRENCY_CODE_FROM,
    CURRENCY_CODE_TO,
    CURRENCY_CONV_DATE,
    CURRENCY_CONV_RATE,
    CURRENCY_CONV_TYPE,
    CURRENCY_CONV_STATUS,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
SELECT DISTINCT
    CONCAT(
        ISNULL(L.DailyRateFromCurrency,'UNK'),
        CONVERT(CHAR(8), ISNULL(L.DailyRateConversionDate,'0001-01-01'), 112),
        ISNULL(TRIM(L.DailyRateConversionType), 'UNK')
    ) AS CURRENCY_ID,
    ISNULL(TRIM(L.DailyRateFromCurrency), 'UNK') AS CURRENCY_CODE_FROM,
    ISNULL(TRIM(L.DailyRateToCurrency), 'UNK') AS CURRENCY_CODE_TO,
    CAST(L.DailyRateConversionDate AS DATE) AS CURRENCY_CONV_DATE,
    CAST(ISNULL(L.DailyRateConversionRate,1) AS NUMERIC(18,4)) AS CURRENCY_CONV_RATE,
    ISNULL(TRIM(L.DailyRateConversionType), 'UNK') AS CURRENCY_CONV_TYPE,
    ISNULL(L.DailyRateStatusCode,'U') AS CURRENCY_CONV_STATUS,
    CAST(L.AddDateTime AS DATE) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM DW_BronzeSilver_PROD.bzo.GL_DailyRateExtractPVO L;
GO

--IF EXISTS (SELECT 1 FROM Oracle_Reporting_P2.svo.D_CURRENCY  WHERE (CURRENCY_ID = '-1') ) DELETE FROM Oracle_Reporting_P2.svo.D_CURRENCY  WHERE (CURRENCY_ID = '-1')

----  Unique lookup on BK
--IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_CURRENCY_ID' AND object_id = OBJECT_ID('Oracle_Reporting_P2.svo.D_CURRENCY'))
--BEGIN
--    CREATE UNIQUE NONCLUSTERED INDEX UX_D_CURRENCY_ID ON Oracle_Reporting_P2.svo.D_CURRENCY(CURRENCY_ID);
--END

