

IF OBJECT_ID('Oracle_Reporting_P2.svo.F_AP_AGING_SNAPSHOT','U') IS NOT NULL
    DROP TABLE Oracle_Reporting_P2.svo.F_AP_AGING_SNAPSHOT;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [svo].[F_AP_AGING_SNAPSHOT]
(
    AP_AGING_SNAPSHOT_PK          BIGINT IDENTITY(1,1) NOT NULL,

    SNAPSHOT_DATE_SK              INT           NOT NULL,

    AP_INVOICE_HEADER_SK          BIGINT        NOT NULL,
    AP_DISBURSEMENT_HEADER_SK     BIGINT        NULL,

    ACCOUNT_SK                    BIGINT        NOT NULL,
    BUSINESS_OFFERING_SK          BIGINT        NOT NULL,
    COMPANY_SK                    BIGINT        NOT NULL,
    COST_CENTER_SK                BIGINT        NOT NULL,
    INDUSTRY_SK                   BIGINT        NOT NULL,
    INTERCOMPANY_SK               BIGINT        NOT NULL,
    LEGAL_ENTITY_SK               BIGINT        NOT NULL,
    BUSINESS_UNIT_SK              BIGINT        NOT NULL,
    VENDOR_SITE_SK                BIGINT        NOT NULL,
    LEDGER_SK                     BIGINT        NOT NULL,

    INV_CURRENCY_SK               BIGINT        NOT NULL,
    PAY_CURRENCY_SK               BIGINT        NOT NULL,

    DUE_DATE_SK                   INT           NULL,
    ACCOUNTING_DATE_SK            INT           NULL,

    PAYMENT_DOCUMENT_ID           BIGINT        NOT NULL,
    PAYMENT_NUM                   INT           NULL,

    ORIGINAL_AMOUNT               DECIMAL(29,4) NOT NULL,
    AMOUNT_PAID                   DECIMAL(29,4) NOT NULL,
    AMOUNT_REMAINING              DECIMAL(29,4) NOT NULL,

    DAYS_PAST_DUE                 INT           NULL,
    AGING_BUCKET_CODE             VARCHAR(20)   NOT NULL,   -- e.g. CURRENT, 0-30, 31-60, 61-90, 90+

    BZ_LOAD_DATE                  DATE          NOT NULL,
    SV_LOAD_DATE                  DATE          NOT NULL,

    CONSTRAINT PK_F_AP_AGING_SNAPSHOT
        PRIMARY KEY CLUSTERED (AP_AGING_SNAPSHOT_PK ASC)

) ON [FG_SilverFact];
GO

TRUNCATE TABLE Oracle_Reporting_P2.svo.F_AP_AGING_SNAPSHOT;
GO

INSERT INTO Oracle_Reporting_P2.svo.F_AP_AGING_SNAPSHOT
(
    SNAPSHOT_DATE_SK,
    AP_INVOICE_HEADER_SK,
    AP_DISBURSEMENT_HEADER_SK,
    ACCOUNT_SK,
    BUSINESS_OFFERING_SK,
    COMPANY_SK,
    COST_CENTER_SK,
    INDUSTRY_SK,
    INTERCOMPANY_SK,
    LEGAL_ENTITY_SK,
    BUSINESS_UNIT_SK,
    VENDOR_SITE_SK,
    LEDGER_SK,
    INV_CURRENCY_SK,
    PAY_CURRENCY_SK,
    DUE_DATE_SK,
    ACCOUNTING_DATE_SK,
    PAYMENT_DOCUMENT_ID,
    PAYMENT_NUM,
    ORIGINAL_AMOUNT,
    AMOUNT_PAID,
    AMOUNT_REMAINING,
    DAYS_PAST_DUE,
    AGING_BUCKET_CODE,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
    SELECT
        CONVERT(INT, FORMAT(CAST(GETDATE() AS DATE),'yyyyMMdd')),
        P.AP_INVOICE_HEADER_SK,
        P.AP_DISBURSEMENT_HEADER_SK,
        P.ACCOUNT_SK,
        P.BUSINESS_OFFERING_SK,
        P.COMPANY_SK,
        P.COST_CENTER_SK,
        P.INDUSTRY_SK,
        P.INTERCOMPANY_SK,
        P.LEGAL_ENTITY_SK,
        P.BUSINESS_UNIT_SK,
        P.VENDOR_SITE_SK,
        P.LEDGER_SK,
        P.INV_CURRENCY_SK,
        P.PAY_CURRENCY_SK,
        P.DUE_DATE_SK,
        P.ACCOUNTING_DATE_SK,
        P.PAYMENT_DOCUMENT_ID,
        P.AP_PAYMENT_SCHEDULES_ALL_PAYMENT_NUM AS PAYMENT_NUM,
        SUM(ISNULL(P.AP_PAYMENT_SCHEDULES_ALL_GROSS_AMOUNT, 0)) AS ORIGINAL_AMOUNT,
        SUM(ISNULL(P.AP_PAYMENT_SCHEDULES_ALL_GROSS_AMOUNT, 0) - ISNULL(P.AP_PAYMENT_SCHEDULES_ALL_AMOUNT_REMAINING, 0)) AS AMOUNT_PAID,
        SUM(ISNULL(P.AP_PAYMENT_SCHEDULES_ALL_AMOUNT_REMAINING, 0))     AS AMOUNT_REMAINING,
        MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) AS DAYS_PAST_DUE,
    CASE
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) IS NULL THEN 'NO DUE DATE'
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) IS NULL THEN 'NO DUE DATE'
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) <= 0 THEN 'CURRENT'
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) BETWEEN 1 AND 30 THEN '1-30'
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) BETWEEN 31 AND 60 THEN '31-60'
        WHEN MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) BETWEEN 61 AND 90 THEN '61-90'
        ELSE '90+'
    END AS AGING_BUCKET_CODE,
        P.BZ_LOAD_DATE_PAID,
        CAST(GETDATE() AS DATE)
    FROM Oracle_Reporting_P2.svo.F_AP_PAYMENTS AS P
    LEFT JOIN Oracle_Reporting_P2.svo.D_CALENDAR AS D_DUE  ON D_DUE.DATE_SK = P.DUE_DATE_SK
    WHERE ISNULL(P.AP_PAYMENT_SCHEDULES_ALL_AMOUNT_REMAINING, 0) <> 0
    GROUP BY
        P.AP_INVOICE_HEADER_SK,
        P.AP_DISBURSEMENT_HEADER_SK,
        P.ACCOUNT_SK,
        P.BUSINESS_OFFERING_SK,
        P.COMPANY_SK,
        P.COST_CENTER_SK,
        P.INDUSTRY_SK,
        P.INTERCOMPANY_SK,
        P.LEGAL_ENTITY_SK,
        P.BUSINESS_UNIT_SK,
        P.VENDOR_SITE_SK,
        P.LEDGER_SK,
        P.INV_CURRENCY_SK,
        P.PAY_CURRENCY_SK,
        P.DUE_DATE_SK,
        P.ACCOUNTING_DATE_SK,
        P.PAYMENT_DOCUMENT_ID,
        P.AP_PAYMENT_SCHEDULES_ALL_PAYMENT_NUM,
    CASE
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END IS NULL THEN 'NO DUE DATE'
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END IS NULL THEN 'NO DUE DATE'
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END <= 0 THEN 'CURRENT'
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END BETWEEN 1 AND 30 THEN '1-30'
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END BETWEEN 31 AND 60 THEN '31-60'
        WHEN CASE  WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END BETWEEN 61 AND 90 THEN '61-90'
        ELSE '90+'
    END,
        P.BZ_LOAD_DATE_PAID
HAVING MAX(CASE WHEN D_DUE.[DATE] IS NULL THEN NULL ELSE DATEDIFF(DAY, D_DUE.[DATE], CAST(GETDATE() AS DATE)) END) > 0;
GO