USE [Oracle_Reporting_P2];
GO

IF OBJECT_ID(N'[svo].[D_GL_HEADER]', 'U') IS NOT NULL
    DROP TABLE [svo].[D_GL_HEADER];
GO

BEGIN -- BEGIN GL HEADER

    CREATE TABLE [svo].[D_GL_HEADER]
    (
        GL_HEADER_SK                BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JE_HEADER_ID                BIGINT        NOT NULL,
        LEDGER_SK                   BIGINT        NOT NULL,
        POSTED_DATE_SK              INT           NOT NULL,
        DEFAULT_EFFECTIVE_DATE_SK   INT           NOT NULL,
        GL_HEADER_NAME              VARCHAR(100)  NOT NULL,
        GL_HEADER_STATUS            VARCHAR(4)    NOT NULL,
        GL_HEADER_DESCRIPTION       VARCHAR(240)  NOT NULL,
        ACCRUAL_REV_CHANGESIGN_FLAG VARCHAR(4)    NOT NULL,
        ACTUAL_FLAG                 VARCHAR(4)    NOT NULL,
        BALANCED_JE_FLAG            VARCHAR(4)    NOT NULL,
        CURRENCY_CODE               VARCHAR(15)   NOT NULL,
        CURRENCY_CONVERSION_DATE    DATE          NOT NULL,
        CURRENCY_CONVERSION_RATE    FLOAT         NOT NULL,
        CURRENCY_CONVERSION_TYPE    VARCHAR(30)   NOT NULL,
        EXTERNAL_REFERENCE          VARCHAR(80)   NOT NULL,
        JE_BATCH_ID                 BIGINT        NOT NULL,
        CATEGORY                    VARCHAR(25)   NOT NULL,
        JE_SOURCE                   VARCHAR(25)   NOT NULL,
        MULTI_CURRENCY_FLAG         VARCHAR(4)    NOT NULL,
        POST_CURRENCY_CODE          VARCHAR(10)   NOT NULL,
        POST_MULTI_CURRENCY_FLAG    VARCHAR(4)    NOT NULL,
        RUNNING_TOTAL_CR            FLOAT         NOT NULL,
        RUNNING_TOTAL_DR            FLOAT         NOT NULL,
        RUNNING_TOTAL_ACCOUNTED_CR  FLOAT         NOT NULL,
        RUNNING_TOTAL_ACCOUNTED_DR  FLOAT         NOT NULL,
        CR_DR_VARIANCE              FLOAT         NOT NULL,
        DATE_CREATED                DATE          NOT NULL,
        CREATED_BY                  VARCHAR(32)   NOT NULL,
        CREATION_DATE               DATE          NOT NULL,
        LAST_UPDATE_DATE            DATE          NOT NULL,
        LAST_UPDATE_LOGIN           VARCHAR(32)   NOT NULL,
        LAST_UPDATED_BY             VARCHAR(64)   NOT NULL,
        BZ_LOAD_DATE                DATE          NOT NULL,
        SV_LOAD_DATE                DATE          NOT NULL
    ) ON [FG_SilverDim];


IF NOT EXISTS (SELECT 1 FROM svo.[D_GL_HEADER] WHERE GL_HEADER_SK = 0)
BEGIN
    SET IDENTITY_INSERT [svo].[D_GL_HEADER] ON;

    INSERT INTO [svo].[D_GL_HEADER]
    ([GL_HEADER_SK],[JE_HEADER_ID],[LEDGER_SK],[POSTED_DATE_SK],[DEFAULT_EFFECTIVE_DATE_SK],[GL_HEADER_NAME],[GL_HEADER_STATUS],
     [GL_HEADER_DESCRIPTION],[ACCRUAL_REV_CHANGESIGN_FLAG],[ACTUAL_FLAG],[BALANCED_JE_FLAG],[CURRENCY_CODE],[CURRENCY_CONVERSION_DATE],
     [CURRENCY_CONVERSION_RATE],[CURRENCY_CONVERSION_TYPE],[EXTERNAL_REFERENCE],[JE_BATCH_ID],[CATEGORY],[JE_SOURCE],[MULTI_CURRENCY_FLAG],
     [POST_CURRENCY_CODE],[POST_MULTI_CURRENCY_FLAG],[RUNNING_TOTAL_CR],[RUNNING_TOTAL_DR],[RUNNING_TOTAL_ACCOUNTED_CR],[RUNNING_TOTAL_ACCOUNTED_DR],
     [CR_DR_VARIANCE],[DATE_CREATED],[CREATED_BY],[CREATION_DATE],[LAST_UPDATE_DATE],[LAST_UPDATE_LOGIN],[LAST_UPDATED_BY],[BZ_LOAD_DATE],[SV_LOAD_DATE])
    VALUES (0,-1,0,0,0,'NULL','NULL','NULL','NULL','NULL','NULL','NULL','0001-01-01',0,'NULL','NULL',
            -1,'NULL','NULL','NULL','NULL','NULL',0,0,0,0,0,'0001-01-01','NULL','0001-01-01','0001-01-01',
            'NULL','NULL','0001-01-01','0001-01-01');

    SET IDENTITY_INSERT [svo].[D_GL_HEADER] OFF;
END;


    INSERT INTO [svo].[D_GL_HEADER]
    (
        JE_HEADER_ID,
        LEDGER_SK,
        POSTED_DATE_SK,
        DEFAULT_EFFECTIVE_DATE_SK,
        GL_HEADER_NAME,
        GL_HEADER_STATUS,
        GL_HEADER_DESCRIPTION,
        ACCRUAL_REV_CHANGESIGN_FLAG,
        ACTUAL_FLAG,
        BALANCED_JE_FLAG,
        CURRENCY_CODE,
        CURRENCY_CONVERSION_DATE,
        CURRENCY_CONVERSION_RATE,
        CURRENCY_CONVERSION_TYPE,
        EXTERNAL_REFERENCE,
        JE_BATCH_ID,
        CATEGORY,
        JE_SOURCE,
        MULTI_CURRENCY_FLAG,
        POST_CURRENCY_CODE,
        POST_MULTI_CURRENCY_FLAG,
        RUNNING_TOTAL_CR,
        RUNNING_TOTAL_DR,
        RUNNING_TOTAL_ACCOUNTED_CR,
        RUNNING_TOTAL_ACCOUNTED_DR,
        CR_DR_VARIANCE,
        DATE_CREATED,
        CREATED_BY,
        CREATION_DATE,
        LAST_UPDATE_DATE,
        LAST_UPDATE_LOGIN,
        LAST_UPDATED_BY,
        BZ_LOAD_DATE,
        SV_LOAD_DATE
    )
    SELECT
          ISNULL(H.JEHEADERID, 0) AS JE_HEADER_ID
        , ISNULL(LGR.LEDGER_SK, 0) AS LEDGER_SK
        , ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, H.GLJEHEADERSPOSTEDDATE), 112) AS INT), 0) AS POSTED_DATE_SK
        , ISNULL(CAST(CONVERT(CHAR(8), TRY_CONVERT(DATE, H.GLJEHEADERSDEFAULTEFFECTIVEDATE), 112) AS INT), 0) AS DEFAULT_EFFECTIVE_DATE_SK
        , ISNULL(H.GLJEHEADERSNAME, 'NULL') AS GL_HEADER_NAME
        , ISNULL(H.GLJEHEADERSSTATUS, 'NULL') AS GL_HEADER_STATUS
        , ISNULL(H.GLJEHEADERSDESCRIPTION, 'NULL') AS GL_HEADER_DESCRIPTION
        , ISNULL(H.GLJEHEADERSACCRUALREVCHANGESIGNFLAG, 'NULL') AS ACCRUAL_REV_CHANGESIGN_FLAG
        , ISNULL(H.GLJEHEADERSACTUALFLAG, 'NULL') AS ACTUAL_FLAG
        , ISNULL(H.GLJEHEADERSBALANCEDJEFLAG, 'NULL') AS BALANCED_JE_FLAG
        , ISNULL(H.GLJEHEADERSCURRENCYCODE, 'NULL') AS CURRENCY_CODE
        , CAST(ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONDATE, '1900-01-01') AS DATE) AS CURRENCY_CONVERSION_DATE
        , ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONRATE, 0) AS CURRENCY_CONVERSION_RATE
        , ISNULL(H.GLJEHEADERSCURRENCYCONVERSIONTYPE, 'NULL') AS CURRENCY_CONVERSION_TYPE
        , ISNULL(H.GLJEHEADERSEXTERNALREFERENCE, 'NULL') AS EXTERNAL_REFERENCE
        , ISNULL(H.GLJEHEADERSJEBATCHID, 0) AS JE_BATCH_ID
        , ISNULL(cat.JournalCategoryJeCategoryKey,'NULL') AS CATEGORY
        , ISNULL(src.JournalSourceJeSourceKey,'NULL') AS JE_SOURCE
        , ISNULL(H.GLJEHEADERSMULTICURRENCYFLAG, 'NULL') AS MULTI_CURRENCY_FLAG
        , ISNULL(H.GLJEHEADERSPOSTCURRENCYCODE, 'NULL') AS POST_CURRENCY_CODE
        , ISNULL(H.GLJEHEADERSPOSTMULTICURRENCYFLAG, 'NULL') AS POST_MULTI_CURRENCY_FLAG
        , CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALCR, 0) AS FLOAT) AS RUNNING_TOTAL_CR
        , CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALDR, 0) AS FLOAT) AS RUNNING_TOTAL_DR
        , CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_CR
        , CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS RUNNING_TOTAL_ACCOUNTED_DR
        , CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDCR, 0) AS FLOAT)
          - CAST(ISNULL(H.GLJEHEADERSRUNNINGTOTALACCOUNTEDDR, 0) AS FLOAT) AS CR_DR_VARIANCE
        , CAST(ISNULL(H.GLJEHEADERSDATECREATED, '1900-01-01') AS DATE) AS DATE_CREATED
        , ISNULL(H.GLJEHEADERSCREATEDBY, 'NULL') AS CREATED_BY
        , CAST(ISNULL(H.GLJEHEADERSCREATIONDATE, '1900-01-01') AS DATE) AS CREATION_DATE
        , CAST(ISNULL(H.GLJEHEADERSLASTUPDATEDATE, '1900-01-01') AS DATE) AS LAST_UPDATE_DATE
        , ISNULL(H.GLJEHEADERSLASTUPDATELOGIN, 'NULL') AS LAST_UPDATE_LOGIN
        , ISNULL(H.GLJEHEADERSLASTUPDATEDBY, 'NULL') AS LAST_UPDATED_BY
        , CAST(GETDATE() - 9 AS DATE) AS BZ_LOAD_DATE   -- keep your existing logic
        , CAST(GETDATE() AS DATE)     AS SV_LOAD_DATE
    FROM bzo.GL_JournalHeaderExtractPVO AS H
    LEFT JOIN svo.D_LEDGER AS LGR ON LGR.LEDGER_ID = H.GLJEHEADERSLEDGERID
    LEFT JOIN [bzo].[GL_JournalCategoryExtractPVO] cat on H.GlJeHeadersJeCategory = cat.JournalCategoryJeCategoryName
	LEFT JOIN [bzo].[GL_JournalSourceExtractPVO] src on H.GlJeHeadersJeSource = src.JournalSourceJeSourceName;
END; -- END GL HEADER
GO
