SELECT  
       AP_INVOICE_HEADER_SK
      ,INVOICE_ID
      ,INVOICE_LINE_NUMBER
      ,INVOICE_DISTRIBUTION_ID
      ,DIST_INV_LINE_NUMBER
      ,DISTRIBUTION_LINE_NUMBER
      ,DIST_ACCOUNTING_DATE_SK
      ,LINE_ACCOUNTING_DATE_SK
      ,ACCOUNT_SK
      ,BUSINESS_OFFERING_SK
      ,COMPANY_SK
      ,COST_CENTER_SK
      ,INDUSTRY_SK
      ,INTERCOMPANY_SK
      ,LEGAL_ENTITY_SK
      ,BUSINESS_UNIT_SK
      ,VENDOR_SITE_SK
      ,LEDGER_SK
      ,DISTRIBUTION_CLASS
      ,DIST_DESCRIPTION
      ,LINE_DESCRIPTION
      ,DISTRIBUTION_AMOUNT
      ,POSTED_FLAG
      ,TYPE_1099
      ,INV_TAX_JURIDISTION_CODE
      ,INV_TAX_RATE
      ,LINE_TYPE_LOOKUP_CODE
      ,PO_DISTRIBUTION_ID
      ,DIST_LAST_UPDATE_DATE
      ,DIST_LAST_UPDATE_BY
      ,DIST_LAST_UPDATE_LOGIN
      ,DIST_CODE_COMBINATION_ID
      ,BZ_LOAD_DATE
      ,SV_LOAD_DATE
      ,LINES_AMOUNT_debug_only
      ,1 AS IS_ORIG_AP_INV
  FROM svo.F_AP_INVOICE_LINE_DISTRIBUTION

  UNION

 SELECT
 	IH.AP_INVOICE_HEADER_SK
,	IH.INVOICE_ID
,	-1												AS INVOICE_LINE_NUMBER	--AE_LINE_NUM?, TMP_LINE_NUM?
,	SL.SOURCE_DIST_ID_NUM1							AS INVOICE_DISTRIBUTION_ID
,	-1												AS DIST_INV_LINE_NUMBER
,	-1												AS DISTRIBUTION_LINE_NUMBER
,	SL.ACCOUNTING_DATE_SK							AS DIST_ACCOUNTING_DATE_SK
,	SL.ACCOUNTING_DATE_SK							AS LINE_ACCOUNTING_DATE_SK		--Unknown Date
,	SL.ACCOUNT_SK
,	SL.BUSINESS_OFFERING_SK
,	SL.COMPANY_SK
,	SL.COST_CENTER_SK
,	SL.INDUSTRY_SK
,	SL.INTERCOMPANY_SK
,	SL.LEGAL_ENTITY_SK
,	SL.BUSINESS_UNIT_SK
,	SL.VENDOR_SITE_SK
,	SL.LEDGER_SK
,	'UNK'											AS DISTRIBUTION_CLASS
,	SL.LINE_DESCRIPTION								AS DIST_DESCRIPTION
,	SL.LINE_DESCRIPTION								AS LINE_DESCRIPTION
,	SL.ACCOUNTED_CR - SL.ACCOUNTED_DR				AS DISTRIBUTION_AMOUNT
,	'Y'												AS POSTED_FLAG
,	'UNK'											AS TAX_1099
,	'UNK'											AS INV_TAX_JURISDICTION_CODE
,	0   											AS INV_TAX_RATE
,	'UNK'											AS LINE_TYPE_LOOKUP_CODE
,	0												AS PO_DISTRIBUTION_ID
,	SL.LAST_UPDATE_DATE
,	SL.LAST_UPDATED_BY
,	SL.LAST_UPDATE_LOGIN
,	SL.CODE_COMBINATION_ID
,	SL.BZ_LOAD_DATE
,	SL.SV_LOAD_DATE
,	SL.LINES_AMOUNT_debug_only
,	0												AS IS_ORIG_AP_INV
FROM 
	(
		SELECT
 			SL.SL_JOURNAL_DIST_FACT_PK
		,	SL.TRANSACTION_SOURCE_ID_INT1
		,	SL.SOURCE_DIST_ID_NUM1
		,	SL.ACCOUNTED_CR
		,	SL.ACCOUNTED_DR
		,	SL.CODE_COMBINATION_ID
		,	SL.ACCOUNTING_DATE_SK
		,	SL.ACCOUNTING_DATE_SK	AS LINE_ACCOUNTING_DATE_SK
		,	SL.EVENT_TYPE_CODE
		,	SL.TRANSACTION_ENTITY_CODE
		,	SL.LINE_DESCRIPTION
		,	SL.SOURCE_DISTRIBUTION_TYPE
        ,	SL.ACCOUNT_SK
        ,	SL.BUSINESS_OFFERING_SK
        ,	SL.COMPANY_SK
        ,	SL.COST_CENTER_SK
        ,	SL.INDUSTRY_SK
        ,	SL.INTERCOMPANY_SK
        ,	SL.LEGAL_ENTITY_SK
        ,	SL.BUSINESS_UNIT_SK
        ,	SL.VENDOR_SITE_SK
        ,	SL.LEDGER_SK
        ,	SL.LAST_UPDATE_DATE
        ,	SL.LAST_UPDATED_BY
        ,	SL.LAST_UPDATE_LOGIN
        ,	SL.BZ_LOAD_DATE
        ,	SL.SV_LOAD_DATE
        ,   SL.ENTERED_CR - ENTERED_DR AS LINES_AMOUNT_debug_only
		FROM
			svo.F_SL_JOURNAL_DISTRIBUTION					SL
			LEFT JOIN svo.F_AP_INVOICE_LINE_DISTRIBUTION    AP	ON	SL.TRANSACTION_SOURCE_ID_INT1	=	AP.INVOICE_ID
															    	AND SL.SOURCE_DIST_ID_NUM1			=	AP.INVOICE_DISTRIBUTION_ID	
            LEFT JOIN svo.D_ACCOUNT                         DA ON   SL.ACCOUNT_SK = DA.ACCOUNT_SK
		WHERE 1=1
			AND SL.APPLICATION_ID				=	'200'
			AND SL.TRANSACTION_ENTITY_CODE		=	'AP_INVOICES'
			AND AP.INVOICE_ID					IS  NULL				--If its already there, don't care
			AND (ACCOUNTED_CR-ACCOUNTED_DR)		!=	0					--If its 0, don't care
			AND DA.ACCOUNT_LVL5_CODE            =   'OPEXP'			 
	) SL
	INNER JOIN svo.D_AP_INVOICE_HEADER	IH	ON	IH.INVOICE_ID	=	SL.TRANSACTION_SOURCE_ID_INT1
WHERE 1=1
--	AND SL.TRANSACTION_SOURCE_ID_INT1	=	1389193
