/* =========================================================
   usp_Load_F_AP_INVOICE_LINE_DISTRIBUTION_V2
   Derived fact: union of svo.F_AP_INVOICE_LINE_DISTRIBUTION (IS_ORIG_AP_INV=1)
   and svo.F_SL_JOURNAL_DISTRIBUTION AP rows missing from AP extract, OPEXP only.
   Full refresh: TRUNCATE then INSERT. No bzo source.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_F_AP_INVOICE_LINE_DISTRIBUTION_V2
    @BatchId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000) = NULL,
        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @RowInserted    INT            = 0;

    BEGIN TRY
        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS, BATCH_ID, TABLE_BRIDGE_ID)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED', ISNULL(@BatchId, -1), -1);

        SET @RunId = SCOPE_IDENTITY();
        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        TRUNCATE TABLE svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2;

        INSERT INTO svo.F_AP_INVOICE_LINE_DISTRIBUTION_V2 (
            AP_INVOICE_HEADER_SK, INVOICE_ID, INVOICE_LINE_NUMBER, INVOICE_DISTRIBUTION_ID, DIST_INV_LINE_NUMBER, DISTRIBUTION_LINE_NUMBER,
            DIST_ACCOUNTING_DATE_SK, LINE_ACCOUNTING_DATE_SK,
            ACCOUNT_SK, BUSINESS_OFFERING_SK, COMPANY_SK, COST_CENTER_SK, INDUSTRY_SK, INTERCOMPANY_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK, VENDOR_SITE_SK, LEDGER_SK,
            DISTRIBUTION_CLASS, DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG, TYPE_1099,
            INV_TAX_JURIDISTION_CODE, INV_TAX_RATE, LINE_TYPE_LOOKUP_CODE,
            PO_DISTRIBUTION_ID, DIST_LAST_UPDATE_DATE, DIST_LAST_UPDATE_BY, DIST_LAST_UPDATE_LOGIN, DIST_CODE_COMBINATION_ID,
            BZ_LOAD_DATE, SV_LOAD_DATE,
            LINES_AMOUNT_debug_only, IS_ORIG_AP_INV
        )
        SELECT AP_INVOICE_HEADER_SK, INVOICE_ID, INVOICE_LINE_NUMBER, INVOICE_DISTRIBUTION_ID, DIST_INV_LINE_NUMBER, DISTRIBUTION_LINE_NUMBER,
            DIST_ACCOUNTING_DATE_SK, LINE_ACCOUNTING_DATE_SK,
            ACCOUNT_SK, BUSINESS_OFFERING_SK, COMPANY_SK, COST_CENTER_SK, INDUSTRY_SK, INTERCOMPANY_SK, LEGAL_ENTITY_SK, BUSINESS_UNIT_SK, VENDOR_SITE_SK, LEDGER_SK,
            DISTRIBUTION_CLASS, DIST_DESCRIPTION, LINE_DESCRIPTION, DISTRIBUTION_AMOUNT, POSTED_FLAG, TYPE_1099,
            INV_TAX_JURIDISTION_CODE, INV_TAX_RATE, LINE_TYPE_LOOKUP_CODE,
            PO_DISTRIBUTION_ID, DIST_LAST_UPDATE_DATE, DIST_LAST_UPDATE_BY, DIST_LAST_UPDATE_LOGIN, DIST_CODE_COMBINATION_ID,
            BZ_LOAD_DATE, SV_LOAD_DATE,
            LINES_AMOUNT_debug_only, 1 AS IS_ORIG_AP_INV
        FROM svo.F_AP_INVOICE_LINE_DISTRIBUTION

        UNION

        SELECT IH.AP_INVOICE_HEADER_SK, IH.INVOICE_ID, -1 AS INVOICE_LINE_NUMBER,
            SL.SOURCE_DIST_ID_NUM1 AS INVOICE_DISTRIBUTION_ID, -1 AS DIST_INV_LINE_NUMBER, -1 AS DISTRIBUTION_LINE_NUMBER,
            SL.ACCOUNTING_DATE_SK AS DIST_ACCOUNTING_DATE_SK, SL.ACCOUNTING_DATE_SK AS LINE_ACCOUNTING_DATE_SK,
            SL.ACCOUNT_SK, SL.BUSINESS_OFFERING_SK, SL.COMPANY_SK, SL.COST_CENTER_SK, SL.INDUSTRY_SK, SL.INTERCOMPANY_SK,
            SL.LEGAL_ENTITY_SK, SL.BUSINESS_UNIT_SK, SL.VENDOR_SITE_SK, SL.LEDGER_SK,
            'UNK' AS DISTRIBUTION_CLASS, SL.LINE_DESCRIPTION AS DIST_DESCRIPTION, SL.LINE_DESCRIPTION AS LINE_DESCRIPTION,
            SL.ACCOUNTED_DR - SL.ACCOUNTED_CR AS DISTRIBUTION_AMOUNT, 'Y' AS POSTED_FLAG, 'UNK' AS TYPE_1099,
            'UNK' AS INV_TAX_JURIDISTION_CODE, 0 AS INV_TAX_RATE, 'UNK' AS LINE_TYPE_LOOKUP_CODE,
            0 AS PO_DISTRIBUTION_ID,
            ISNULL(CONVERT(DATE, SL.LAST_UPDATE_DATE), '0001-01-01') AS DIST_LAST_UPDATE_DATE,
            ISNULL(SL.LAST_UPDATED_BY, 'UNK') AS DIST_LAST_UPDATE_BY,
            ISNULL(SL.LAST_UPDATE_LOGIN, 'UNK') AS DIST_LAST_UPDATE_LOGIN,
            SL.CODE_COMBINATION_ID AS DIST_CODE_COMBINATION_ID,
            SL.BZ_LOAD_DATE, SL.SV_LOAD_DATE,
            SL.LINES_AMOUNT_debug_only, 0 AS IS_ORIG_AP_INV
        FROM (
            SELECT
                SL.SL_JOURNAL_DIST_FACT_PK,
                SL.TRANSACTION_SOURCE_ID_INT1,
                SL.SOURCE_DIST_ID_NUM1,
                SL.ACCOUNTED_CR,
                SL.ACCOUNTED_DR,
                SL.CODE_COMBINATION_ID,
                SL.ACCOUNTING_DATE_SK,
                SL.LINE_DESCRIPTION,
                SL.ACCOUNT_SK,
                SL.BUSINESS_OFFERING_SK,
                SL.COMPANY_SK,
                SL.COST_CENTER_SK,
                SL.INDUSTRY_SK,
                SL.INTERCOMPANY_SK,
                SL.LEGAL_ENTITY_SK,
                SL.BUSINESS_UNIT_SK,
                SL.VENDOR_SITE_SK,
                SL.LEDGER_SK,
                SL.LAST_UPDATE_DATE,
                SL.LAST_UPDATED_BY,
                SL.LAST_UPDATE_LOGIN,
                SL.BZ_LOAD_DATE,
                SL.SV_LOAD_DATE,
                SL.ENTERED_DR - SL.ENTERED_CR AS LINES_AMOUNT_debug_only
            FROM svo.F_SL_JOURNAL_DISTRIBUTION SL
            LEFT JOIN svo.F_AP_INVOICE_LINE_DISTRIBUTION AP
                ON SL.TRANSACTION_SOURCE_ID_INT1 = AP.INVOICE_ID
                AND SL.SOURCE_DIST_ID_NUM1 = AP.INVOICE_DISTRIBUTION_ID
            LEFT JOIN svo.D_ACCOUNT DA ON SL.ACCOUNT_SK = DA.ACCOUNT_SK
            WHERE SL.APPLICATION_ID = 200
                AND SL.TRANSACTION_ENTITY_CODE = 'AP_INVOICES'
                AND AP.INVOICE_ID IS NULL
                AND (SL.ACCOUNTED_CR - SL.ACCOUNTED_DR) != 0
                AND DA.ACCOUNT_LVL5_CODE = 'OPEXP'
        ) SL
        INNER JOIN svo.D_AP_INVOICE_HEADER IH ON IH.INVOICE_ID = SL.TRANSACTION_SOURCE_ID_INT1;

        SET @RowInserted = @@ROWCOUNT;

        UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = CAST(GETDATE() AS DATETIME2(7)), UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_UPDATED = 0, ROW_EXPIRED = 0, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_UPDATED = 0, ROW_EXPIRED = 0, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        ;THROW;
    END CATCH
END;
GO
