/* Run on Oracle_Reporting_P2 to list actual columns in svo.F_SL_JOURNAL_DISTRIBUTION */
SELECT COLUMN_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'svo' AND TABLE_NAME = 'F_SL_JOURNAL_DISTRIBUTION'
ORDER BY ORDINAL_POSITION;
