USE [Oracle_Reporting_P2]
GO

/****** Object:  Table [bzo].[Opportunity]    Script Date: 2/16/2026 12:12:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [bzo].[Opportunity](
	[AccountId] [nvarchar](18) NULL,
	[Amount] [numeric](18, 2) NULL,
	[Budget_Confirmed__c] [bit] NULL,
	[cafsl__Data_Set_Exclude_List__c] [nvarchar](max) NULL,
	[Campaign_End_Date__c] [datetime2](7) NULL,
	[Campaign_Start_Date__c] [datetime2](7) NULL,
	[CampaignId] [nvarchar](18) NULL,
	[CloseDate] [datetime2](7) NULL,
	[ContactId] [nvarchar](18) NULL,
	[ContractId] [nvarchar](18) NULL,
	[CreatedById] [nvarchar](18) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CurrencyIsoCode] [nvarchar](255) NULL,
	[Customer__c] [nvarchar](18) NULL,
	[Days_Since_Last_Activity__c] [float] NULL,
	[Description] [nvarchar](max) NULL,
	[Discovery_Completed__c] [bit] NULL,
	[DOZISF__ZoomInfo_Opsos_App_Field__c] [nvarchar](150) NULL,
	[DOZISF__ZoomInfo_Opsos_Current_Endpoint__c] [nvarchar](255) NULL,
	[DOZISF__ZoomInfo_Opsos_Last_Processed_Date__c] [datetime2](7) NULL,
	[ExpectedRevenue] [numeric](18, 2) NULL,
	[Field_History_Date__c] [datetime2](7) NULL,
	[Fiscal] [nvarchar](6) NULL,
	[FiscalQuarter] [int] NULL,
	[FiscalYear] [int] NULL,
	[Forecast_Manager__c] [nvarchar](18) NULL,
	[ForecastCategory] [nvarchar](255) NULL,
	[ForecastCategoryName] [nvarchar](255) NULL,
	[HasOpenActivity] [bit] NULL,
	[HasOpportunityLineItem] [bit] NULL,
	[HasOverdueTask] [bit] NULL,
	[Id] [nvarchar](18) NOT NULL,
	[Industry__c] [nvarchar](255) NULL,
	[IsClosed] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[IsExcludedFromTerritory2Filter] [bit] NULL,
	[IsPrivate] [bit] NULL,
	[IsSplit] [bit] NULL,
	[IsWon] [bit] NULL,
	[Last_Task_Date__c] [datetime2](7) NULL,
	[LastActivityDate] [datetime2](7) NULL,
	[LastAmountChangedHistoryId] [nvarchar](18) NULL,
	[LastCloseDateChangedHistoryId] [nvarchar](18) NULL,
	[LastModifiedById] [nvarchar](18) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[LastReferencedDate] [datetime2](7) NULL,
	[LastStageChangeDate] [datetime2](7) NULL,
	[LastViewedDate] [datetime2](7) NULL,
	[LeadSource] [nvarchar](255) NULL,
	[LID__LinkedIn_Company_Id__c] [nvarchar](80) NULL,
	[LM_AccountType__c] [nvarchar](20) NULL,
	[LM_Additional_RFP_Details__c] [nvarchar](max) NULL,
	[LM_AE_Code__c] [nvarchar](1300) NULL,
	[LM_Brand_Industry__c] [nvarchar](255) NULL,
	[LM_Brand_Name__c] [nvarchar](255) NULL,
	[LM_Business_Unit__c] [nvarchar](20) NULL,
	[lm_collaborative__c] [bit] NULL,
	[LM_CPQ_Transaction_Number__c] [nvarchar](80) NULL,
	[LM_Customer_PO_Number__c] [nvarchar](80) NULL,
	[LM_Estimated_Amount__c] [numeric](18, 0) NULL,
	[LM_Industry_Category__c] [nvarchar](255) NULL,
	[LM_Inventory_on_Hold__c] [numeric](18, 2) NULL,
	[LM_Is_Team_Match__c] [bit] NULL,
	[LM_Last_Activity_Date__c] [datetime2](7) NULL,
	[LM_Logo_Industry_Categories__c] [nvarchar](255) NULL,
	[LM_NAICS_Code__c] [nvarchar](1300) NULL,
	[LM_Office__c] [nvarchar](255) NULL,
	[LM_Primary_Oracle_Quote__c] [nvarchar](18) NULL,
	[LM_Quote_Status__c] [nvarchar](255) NULL,
	[LM_Related_Opportunity__c] [nvarchar](18) NULL,
	[LM_Response_Due_DateTime__c] [datetime2](7) NULL,
	[LM_Response_Due_DateTime_CPQ__c] [nvarchar](50) NULL,
	[LM_Sales_Category__c] [nvarchar](50) NULL,
	[LM_TCV_Airport__c] [numeric](18, 0) NULL,
	[LM_TCV_Logos__c] [numeric](18, 0) NULL,
	[LM_TCV_Outdoor__c] [numeric](18, 0) NULL,
	[LM_TCV_Transit__c] [numeric](18, 0) NULL,
	[LM_Total_Contract_Value__c] [numeric](18, 0) NULL,
	[LM_Transaction_Type__c] [nvarchar](50) NULL,
	[Loss_Reason__c] [nvarchar](255) NULL,
	[NAICS_Description__c] [nvarchar](255) NULL,
	[Name] [nvarchar](120) NULL,
	[NextStep] [nvarchar](255) NULL,
	[No_Activity_60_Days__c] [bit] NULL,
	[Number_of_Weeks__c] [float] NULL,
	[OwnerId] [nvarchar](18) NULL,
	[Pricebook2Id] [nvarchar](18) NULL,
	[Probability] [float] NULL,
	[PushCount] [int] NULL,
	[ROI_Analysis_Completed__c] [bit] NULL,
	[StageName] [nvarchar](255) NULL,
	[SystemModstamp] [datetime2](7) NULL,
	[Territory2Id] [nvarchar](18) NULL,
	[Total_By_LOB__c] [numeric](18, 2) NULL,
	[Total_In_Market__c] [numeric](18, 2) NULL,
	[Total_Out_of_Market__c] [numeric](18, 2) NULL,
	[Total_Price__c] [numeric](18, 2) NULL,
	[TotalOpportunityQuantity] [float] NULL,
	[Transaction_ID__c] [nvarchar](255) NULL,
	[Type] [nvarchar](255) NULL,
	[UniqueEntry__Current_Endpoint__c] [nvarchar](255) NULL,
	[UniqueEntry__RingLead_App_Field__c] [nvarchar](255) NULL,
	[UniqueEntry__RingLead_Last_Processed_Date__c] [datetime2](7) NULL,
 CONSTRAINT [PK_Opportunity_Id] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

