IF OBJECT_ID('svo.D_SM_SUBSCRIPTION_PRODUCT','U') IS NOT NULL 
    DROP TABLE svo.D_SM_SUBSCRIPTION_PRODUCT;
GO

CREATE TABLE svo.D_SM_SUBSCRIPTION_PRODUCT
(
    SUBSCRIPTION_PRODUCT_SK BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SUBSCRIPTION_PRODUCT_ID BIGINT NOT NULL,
    SUBSCRIPTION_ID         BIGINT NULL,
    INVENTORY_ITEM_ID       BIGINT NULL,
    DEFINITION_ORG_ID       BIGINT NULL,
    BZ_LOAD_DATE            DATE   NULL,
    SV_LOAD_DATE            DATE   NULL
) ON [FG_SilverDim];
GO

SET IDENTITY_INSERT svo.D_SM_SUBSCRIPTION_PRODUCT ON;
INSERT INTO svo.D_SM_SUBSCRIPTION_PRODUCT
    (SUBSCRIPTION_PRODUCT_SK, SUBSCRIPTION_PRODUCT_ID, SUBSCRIPTION_ID, INVENTORY_ITEM_ID, DEFINITION_ORG_ID, BZ_LOAD_DATE, SV_LOAD_DATE)
VALUES
    (0, -1, -1, -1, -1, '0001-01-01', '0001-01-01');
SET IDENTITY_INSERT svo.D_SM_SUBSCRIPTION_PRODUCT OFF;
GO

INSERT INTO svo.D_SM_SUBSCRIPTION_PRODUCT
(
    SUBSCRIPTION_PRODUCT_ID,
    SUBSCRIPTION_ID,
    INVENTORY_ITEM_ID,
    DEFINITION_ORG_ID,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
SELECT DISTINCT
    P.SubscriptionProductId,
    P.SubscriptionId,
    P.InventoryItemId,
    P.DefinitionOrgId,
    CAST(P.AddDateTime AS DATE),
    CAST(GETDATE() AS DATE)
FROM bzo.OSS_SubscriptionProductExtractPVO P
WHERE NOT EXISTS (
    SELECT 1 FROM svo.D_SM_SUBSCRIPTION_PRODUCT D WHERE D.SUBSCRIPTION_PRODUCT_ID = P.SubscriptionProductId
);
GO