/* ==========
   LEGAL_ENTITY
   ========== */
IF OBJECT_ID(N'svo.D_LEGAL_ENTITY', 'U') IS NOT NULL
    DROP TABLE svo.D_LEGAL_ENTITY;
GO

CREATE TABLE svo.D_LEGAL_ENTITY
(
    LEGAL_ENTITY_SK                       BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    LEGAL_ENTITY_ID                       BIGINT NOT NULL,
    LEGAL_ENTITY_ENTERPRISE_ID            INT NULL,
    LEGAL_ENTITY_GEOGRAPHY_ID             BIGINT NULL,
    LEGAL_ENTITY_LEGAL_EMPLOYER_FLAG      VARCHAR(4) NULL,
    LEGAL_ENTITY_IDENTIFIER               VARCHAR(100) NULL,
    LEGAL_ENTITY_NAME                     VARCHAR(100) NULL,
    LEGAL_ENTITY_OBJECT_VERSION_NUMBER    FLOAT NULL,
    LEGAL_ENTITY_PARTY_ID                 BIGINT NULL,
    LEGAL_ENTITY_PSU_FLAG                 VARCHAR(4) NULL,
    LEGAL_ENTITY_TRANSACTING_ENTITY_FLAG  VARCHAR(4) NULL,
    LEGAL_ENTITY_LAST_UPDATE_DATE         DATE NOT NULL,
    LEGAL_ENTITY_LAST_UPDATE_LOGIN        VARCHAR(100) NULL,
    LEGAL_ENTITY_LAST_UPDATED_BY          VARCHAR(64) NULL,
    BZ_LOAD_DATE                          DATE NULL,
    SV_LOAD_DATE                          DATE NULL
) ON FG_SilverDim;
GO

INSERT INTO svo.D_LEGAL_ENTITY (
   LEGAL_ENTITY_ID,
   LEGAL_ENTITY_ENTERPRISE_ID,
   LEGAL_ENTITY_GEOGRAPHY_ID,
   LEGAL_ENTITY_LEGAL_EMPLOYER_FLAG,
   LEGAL_ENTITY_IDENTIFIER,
   LEGAL_ENTITY_NAME,
   LEGAL_ENTITY_OBJECT_VERSION_NUMBER,
   LEGAL_ENTITY_PARTY_ID,
   LEGAL_ENTITY_PSU_FLAG,
   LEGAL_ENTITY_TRANSACTING_ENTITY_FLAG,
   LEGAL_ENTITY_LAST_UPDATE_DATE,
   LEGAL_ENTITY_LAST_UPDATE_LOGIN,
   LEGAL_ENTITY_LAST_UPDATED_BY,
   BZ_LOAD_DATE,
   SV_LOAD_DATE
)
SELECT  
   LEGALENTITYLEGALENTITYID,
   LEGALENTITYENTERPRISEID,
   LEGALENTITYGEOGRAPHYID,
   LEGALENTITYLEGALEMPLOYERFLAG,
   LEGALENTITYLEGALENTITYIDENTIFIER,
   LEGALENTITYNAME,
   LEGALENTITYOBJECTVERSIONNUMBER,
   LEGALENTITYPARTYID,
   LEGALENTITYPSUFLAG,
   LEGALENTITYTRANSACTINGENTITYFLAG,
   CAST(LEGALENTITYLASTUPDATEDATE AS DATE),
   LEGALENTITYLASTUPDATELOGIN,
   LEGALENTITYLASTUPDATEDBY,
   COALESCE(CAST(AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
   CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM Oracle_Reporting_P2.bzo.GL_LegalEntityExtractPVO;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_LEGAL_ENTITY_ID' AND object_id = OBJECT_ID('svo.D_LEGAL_ENTITY'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_LEGAL_ENTITY_ID ON svo.D_LEGAL_ENTITY(LEGAL_ENTITY_ID) ON FG_SilverDim;
END
GO

IF NOT EXISTS (SELECT 1 FROM svo.D_LEGAL_ENTITY WHERE LEGAL_ENTITY_SK = 0)
BEGIN
    SET IDENTITY_INSERT svo.D_LEGAL_ENTITY ON;

    INSERT INTO svo.D_LEGAL_ENTITY (
    LEGAL_ENTITY_SK, LEGAL_ENTITY_ID, LEGAL_ENTITY_ENTERPRISE_ID, LEGAL_ENTITY_GEOGRAPHY_ID,
    LEGAL_ENTITY_LEGAL_EMPLOYER_FLAG, LEGAL_ENTITY_IDENTIFIER, LEGAL_ENTITY_NAME,
    LEGAL_ENTITY_OBJECT_VERSION_NUMBER, LEGAL_ENTITY_PARTY_ID, LEGAL_ENTITY_PSU_FLAG,
    LEGAL_ENTITY_TRANSACTING_ENTITY_FLAG, LEGAL_ENTITY_LAST_UPDATE_DATE, LEGAL_ENTITY_LAST_UPDATE_LOGIN,
    LEGAL_ENTITY_LAST_UPDATED_BY
    )
    VALUES ( 0,-1,-1,-1,'NULL','00-0000000','Unknown',-1,-1,'NULL','NULL','0001-01-01','Unknown','Unknown')
    SET IDENTITY_INSERT svo.D_LEGAL_ENTITY OFF;
END
GO