IF OBJECT_ID('svo.D_PARTY_CONTACT_POINT','U') IS NOT NULL
    DROP TABLE svo.D_PARTY_CONTACT_POINT;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE svo.D_PARTY_CONTACT_POINT
(
    PARTY_CONTACT_POINT_SK  BIGINT IDENTITY(1,1) NOT NULL,

    CONTACT_POINT_ID        BIGINT        NOT NULL,  -- bzo.AR_PartyContactPointExtractPVO.ContactPointId
    OWNER_TABLE_ID          BIGINT        NOT NULL,  -- points to PARTY_ID in this PVO set
    CONTACT_POINT_TYPE      VARCHAR(30)   NOT NULL,
    CONTACT_POINT_PURPOSE   VARCHAR(30)   NULL,
    PHONE_NUMBER            VARCHAR(40)   NULL,
    PRIMARY_FLAG            VARCHAR(1)    NULL,

    LAST_UPDATE_DATE        DATE          NOT NULL,
    LAST_UPDATED_BY         VARCHAR(64)   NOT NULL,
    LAST_UPDATE_LOGIN       VARCHAR(32)   NULL,

    BZ_LOAD_DATE            DATE          NOT NULL,
    SV_LOAD_DATE            DATE          NOT NULL
        CONSTRAINT DF_D_PARTY_CONTACT_POINT_SV_LOAD_DATE
        DEFAULT (CAST(GETDATE() AS DATE)),

    CONSTRAINT PK_D_PARTY_CONTACT_POINT PRIMARY KEY CLUSTERED (PARTY_CONTACT_POINT_SK)
        ON FG_SilverDim,

    CONSTRAINT UQ_D_PARTY_CONTACT_POINT UNIQUE (CONTACT_POINT_ID)
        ON FG_SilverDim
)
ON FG_SilverDim;
GO

SET IDENTITY_INSERT svo.D_PARTY_CONTACT_POINT ON;

INSERT INTO svo.D_PARTY_CONTACT_POINT
(
    PARTY_CONTACT_POINT_SK,
    CONTACT_POINT_ID,
    OWNER_TABLE_ID,
    CONTACT_POINT_TYPE,
    CONTACT_POINT_PURPOSE,
    PHONE_NUMBER,
    PRIMARY_FLAG,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
VALUES
(
    0,
    0,
    0,
    'UNKNOWN',
    'UNKNOWN',
    'UNKNOWN',
    'N',
    '0001-01-01',
    'SYSTEM',
    'UNKNOWN',
    CAST('0001-01-01' AS DATE),
    CAST(GETDATE() AS DATE)
);

SET IDENTITY_INSERT svo.D_PARTY_CONTACT_POINT OFF;
GO
INSERT INTO svo.D_PARTY_CONTACT_POINT
(
    CONTACT_POINT_ID,
    OWNER_TABLE_ID,
    CONTACT_POINT_TYPE,
    CONTACT_POINT_PURPOSE,
    PHONE_NUMBER,
    PRIMARY_FLAG,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    BZ_LOAD_DATE
)
SELECT
    C.ContactPointId,
    C.OwnerTableId,
    C.ContactPointType,
    C.ContactPointPurpose,
    C.PhoneNumber,
    C.PrimaryFlag,
    C.LastUpdateDate,
    C.LastUpdatedBy,
    C.LastUpdateLogin,
    COALESCE(CAST(C.AddDateTime AS DATE), CAST(GETDATE() AS DATE))
FROM    bzo.AR_PartyContactPointExtractPVO C
WHERE   NOT EXISTS
(
    SELECT 1
    FROM   svo.D_PARTY_CONTACT_POINT D
    WHERE  D.CONTACT_POINT_ID = C.ContactPointId
);
GO
