/* =========================================================
   usp_Load_D_RM_PERF_OBLIGATION
   Type 1 incremental load. Source: bzo.VRM_PerfObligationsPVO
   Watermark: AddDateTime. Grain: PERF_OBLIGATION_ID. Plug row SK=0 if missing.
   Idempotent: safe to retry.
   ========================================================= */
CREATE OR ALTER PROCEDURE svo.usp_Load_D_RM_PERF_OBLIGATION
    @BatchId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @ProcName       SYSNAME        = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID),
        @TargetObject   SYSNAME        = 'svo.D_RM_PERF_OBLIGATION',
        @StartDttm      DATETIME2(0)   = SYSDATETIME(),
        @EndDttm        DATETIME2(0),
        @RunId          BIGINT         = NULL,
        @ErrMsg         NVARCHAR(4000) = NULL,
        @AsOfDate       DATE           = CAST(GETDATE() AS DATE),
        @LastWatermark  DATETIME2(7),
        @MaxWatermark   DATETIME2(7)   = NULL,
        @RowInserted    INT            = 0,
        @RowUpdated     INT            = 0,
        @TableBridgeID  INT            = NULL;

    DECLARE @MergeActions TABLE (ActionTaken VARCHAR(10) NOT NULL);

    SELECT @TableBridgeID = TableBridgeID FROM meta.MedallionTableBridge WHERE targettable = N'VRM_PerfObligationsPVO';

    BEGIN TRY
        SELECT @LastWatermark = w.LAST_WATERMARK
        FROM etl.ETL_WATERMARK w
        WHERE w.TABLE_NAME = @TargetObject;

        IF @LastWatermark IS NULL
            SET @LastWatermark = '1900-01-01';

        INSERT INTO etl.ETL_RUN (PROC_NAME, TARGET_OBJECT, ASOF_DATE, START_DTTM, STATUS, BATCH_ID, TABLE_BRIDGE_ID)
        VALUES (@ProcName, @TargetObject, @AsOfDate, @StartDttm, 'STARTED', ISNULL(@BatchId, -1), ISNULL(@TableBridgeID, -1));

        SET @RunId = SCOPE_IDENTITY();
        IF @RunId IS NULL
            THROW 50001, 'ETL_RUN insert failed: RUN_ID is NULL.', 1;

        IF NOT EXISTS (SELECT 1 FROM svo.D_RM_PERF_OBLIGATION WHERE RM_PERF_OBLIGATION_SK = 0)
        BEGIN
            SET IDENTITY_INSERT svo.D_RM_PERF_OBLIGATION ON;
            INSERT INTO svo.D_RM_PERF_OBLIGATION
            (RM_PERF_OBLIGATION_SK, PERF_OBLIGATION_ID, BASE_PRICE, BASE_PRICE_PERCENTAGE, CR_LIABILITY_AMT, DR_ASSET_AMT, DR_DISCOUNT_AMT, NET_LINE_AMT_CONTR, TOTAL_BILLED_AMT_CONTR, TOT_ALLOC_AMT_CONTR, TOTAL_RECOG_REV_AMT_CONTR, TOT_CARVE_OUT_AMT_CONTR, TOT_NET_CONSIDER_AMT_CONTR, COST_AMOUNT, CREATED_BY, CREATION_DATE, CUSTOMER_CONTRACT_HEADER_ID, DISCARD_FLAG, DISCOUNT_AMOUNT, DISCOUNT_PERCENTAGE, EXEMPT_FROM_ALLOCATION_FLAG, FMV_LINE_ID, GROSS_MARGIN_PERCENTAGE, INITIAL_PERF_EVT_CREATED_FLAG, INITIAL_PERF_EVT_EXPECTED_DATE, INITIAL_PERF_EVT_RECORDED_FLAG, LAST_UPDATE_DATE, LAST_UPDATED_BY, LATEST_REVISION_INTENT_CODE, LATEST_VERSION_DATE, LIST_PRICE_AMOUNT, OBLIGATION_REFERENCE, FMV_AMT, NET_LINE_AMT_OBLIG, NET_SALES_PRICE, OBLIG_CURRENCY_CODE, TOTAL_BILLED_AMT_OBLIG, TOT_ALLOC_AMT_OBLIG, TOTAL_RECOG_REV_AMT_OBLIG, TOT_CARVE_OUT_AMT_OBLIG, TOT_NET_CONSIDER_AMT_OBLIG, OBLIG_PAYMENT_AMOUNT, PERF_OBLIGATION_NUMBER, PERF_OBLIGATION_TYPE, PERF_OBLIG_CLASSIFICATION_CODE, PERF_OBLIG_FREEZE_FLAG, REMOVED_FLAG, SATISFACTION_DATE, SATISFACTION_METHOD, SATISFACTION_STATUS, UNIT_SELLING_PRICE, AVERAGE_PRICE, FAIR_MARKET_VALUE, FMV_TOLERANCE_HIGH_PCT, FMV_TOLERANCE_LOW_PCT, HIGHEST_PRICE, PRICE_LAST_UPDATE_DATE, LINE_COUNT, LOWEST_PRICE, STANDARD_DEVIATION, TOLERANCE_COVERAGE, TOLERANCE_COVERAGE_COUNT, TOLERANCE_RANGE_COVERAGE, TOTAL_AMOUNT, TOTAL_QUANTITY, BZ_LOAD_DATE, SV_LOAD_DATE)
            VALUES (0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Unknown', '1900-01-01', -1, 'U', 0, 0, 'U', -1, 0, 'U', '1900-01-01', 'U', '1900-01-01', 'Unk', -1, '9999-12-31', 0, -1, 0, 0, 0, 'Unk', 0, 0, 0, 0, 0, 0, -1, 'Unknown', 'U', 'U', 'U', '1900-01-01', 'Unknown', 0, 0, 0, 0, 0, 0, 0, '1900-01-01', 0, 0, 0, 0, 0, 0, 0, 0, CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE));
            SET IDENTITY_INSERT svo.D_RM_PERF_OBLIGATION OFF;
        END;

        IF OBJECT_ID('tempdb..#src') IS NOT NULL DROP TABLE #src;

        SELECT
            ISNULL(O.PerfObligationId, -1) AS PERF_OBLIGATION_ID,
            ISNULL(O.PerfObligationsBasePrice, 0) AS BASE_PRICE,
            ISNULL(O.PerfObligationsBasePricePercentage, 0) AS BASE_PRICE_PERCENTAGE,
            ISNULL(O.PerfObligationsContrCurCrLiabilityAmt, 0) AS CR_LIABILITY_AMT,
            ISNULL(O.PerfObligationsContrCurDrAssetAmt, 0) AS DR_ASSET_AMT,
            ISNULL(O.PerfObligationsContrCurDrDiscountAmt, 0) AS DR_DISCOUNT_AMT,
            ISNULL(O.PerfObligationsContrCurNetLineAmt, 0) AS NET_LINE_AMT_CONTR,
            ISNULL(O.PerfObligationsContrCurTotalBilledAmt, 0) AS TOTAL_BILLED_AMT_CONTR,
            ISNULL(O.PerfObligationsContrCurTotAllocAmt, 0) AS TOT_ALLOC_AMT_CONTR,
            ISNULL(O.PerfObligationsContrCurTotalRecogRevAmt, 0) AS TOTAL_RECOG_REV_AMT_CONTR,
            ISNULL(O.PerfObligationsContrCurTotCarveOutAmt, 0) AS TOT_CARVE_OUT_AMT_CONTR,
            ISNULL(O.PerfObligationsContrCurTotNetConsiderAmt, 0) AS TOT_NET_CONSIDER_AMT_CONTR,
            ISNULL(O.PerfObligationsCostAmount, 0) AS COST_AMOUNT,
            ISNULL(O.PerfObligationsCreatedBy, 'Unknown') AS CREATED_BY,
            ISNULL(O.PerfObligationsCreationDate, '1900-01-01') AS CREATION_DATE,
            ISNULL(O.PerfObligationsCustomerContractHeaderId, -1) AS CUSTOMER_CONTRACT_HEADER_ID,
            ISNULL(O.PerfObligationsDiscardFlag, 'U') AS DISCARD_FLAG,
            ISNULL(O.PerfObligationsDiscountAmount, 0) AS DISCOUNT_AMOUNT,
            ISNULL(O.PerfObligationsDiscountPercentage, 0) AS DISCOUNT_PERCENTAGE,
            ISNULL(O.PerfObligationsExemptFromAllocationFlag, 'U') AS EXEMPT_FROM_ALLOCATION_FLAG,
            ISNULL(O.PerfObligationsFmvLineId, -1) AS FMV_LINE_ID,
            ISNULL(O.PerfObligationsGrossMarginPercentage, 0) AS GROSS_MARGIN_PERCENTAGE,
            ISNULL(O.PerfObligationsInitialPerfEvtCreatedFlag, 'U') AS INITIAL_PERF_EVT_CREATED_FLAG,
            ISNULL(O.PerfObligationsInitialPerfEvtExpectedDate, '1900-01-01') AS INITIAL_PERF_EVT_EXPECTED_DATE,
            ISNULL(O.PerfObligationsInitialPerfEvtRecordedFlag, 'U') AS INITIAL_PERF_EVT_RECORDED_FLAG,
            ISNULL(O.PerfObligationsLastUpdateDate, '1900-01-01') AS LAST_UPDATE_DATE,
            ISNULL(O.PerfObligationsLastUpdatedBy, 'Unknown') AS LAST_UPDATED_BY,
            ISNULL(O.PerfObligationsLatestRevisionIntentCode, 'Unk') AS LATEST_REVISION_INTENT_CODE,
            ISNULL(O.PerfObligationsLatestVersionDate, '9999-12-31') AS LATEST_VERSION_DATE,
            ISNULL(O.PerfObligationsListPriceAmount, 0) AS LIST_PRICE_AMOUNT,
            ISNULL(O.PerfObligationsObligationReference, 'Unknown') AS OBLIGATION_REFERENCE,
            ISNULL(O.PerfObligationsObligCurFmvAmt, 0) AS FMV_AMT,
            ISNULL(O.PerfObligationsObligCurNetLineAmt, 0) AS NET_LINE_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligCurNetSalesPrice, 0) AS NET_SALES_PRICE,
            ISNULL(O.PerfObligationsObligCurrencyCode, 'Unk') AS OBLIG_CURRENCY_CODE,
            ISNULL(O.PerfObligationsObligCurTotalBilledAmt, 0) AS TOTAL_BILLED_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligCurTotAllocAmt, 0) AS TOT_ALLOC_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligCurTotalRecogRevAmt, 0) AS TOTAL_RECOG_REV_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligCurTotCarveOutAmt, 0) AS TOT_CARVE_OUT_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligCurTotNetConsiderAmt, 0) AS TOT_NET_CONSIDER_AMT_OBLIG,
            ISNULL(O.PerfObligationsObligPaymentAmount, 0) AS OBLIG_PAYMENT_AMOUNT,
            ISNULL(O.PerfObligationsPerfObligationNumber, -1) AS PERF_OBLIGATION_NUMBER,
            ISNULL(O.PerfObligationsPerfObligationType, 'Unknown') AS PERF_OBLIGATION_TYPE,
            ISNULL(O.PerfObligationsPerfObligClassificationCode, 'Unk') AS PERF_OBLIG_CLASSIFICATION_CODE,
            ISNULL(O.PerfObligationsPerfObligFreezeFlag, 'U') AS PERF_OBLIG_FREEZE_FLAG,
            ISNULL(O.PerfObligationsRemovedFlag, 'U') AS REMOVED_FLAG,
            ISNULL(O.PerfObligationsSatisfactionDate, '9999-12-31') AS SATISFACTION_DATE,
            ISNULL(O.PerfObligationsSatisfactionMethod, 'Unknown') AS SATISFACTION_METHOD,
            ISNULL(O.PerfObligationsSatisfactionStatus, 'Unknown') AS SATISFACTION_STATUS,
            ISNULL(O.PerfObligationsUnitSellingPrice, 0) AS UNIT_SELLING_PRICE,
            ISNULL(O.PriceLinePEOAveragePrice, 0) AS AVERAGE_PRICE,
            ISNULL(O.PriceLinePEOFairMarketValue, 0) AS FAIR_MARKET_VALUE,
            ISNULL(O.PriceLinePEOFmvToleranceHighPct, 0) AS FMV_TOLERANCE_HIGH_PCT,
            ISNULL(O.PriceLinePEOFmvToleranceLowPct, 0) AS FMV_TOLERANCE_LOW_PCT,
            ISNULL(O.PriceLinePEOHighestPrice, 0) AS HIGHEST_PRICE,
            ISNULL(O.PriceLinePEOLastUpdateDate, '1900-01-01') AS PRICE_LAST_UPDATE_DATE,
            ISNULL(O.PriceLinePEOLineCount, 0) AS LINE_COUNT,
            ISNULL(O.PriceLinePEOLowestPrice, 0) AS LOWEST_PRICE,
            ISNULL(O.PriceLinePEOStandardDeviation, 0) AS STANDARD_DEVIATION,
            ISNULL(O.PriceLinePEOToleranceCoverage, 0) AS TOLERANCE_COVERAGE,
            ISNULL(O.PriceLinePEOToleranceCoverageCount, 0) AS TOLERANCE_COVERAGE_COUNT,
            ISNULL(O.PriceLinePEOToleranceRangeCoverage, 0) AS TOLERANCE_RANGE_COVERAGE,
            ISNULL(O.PriceLinePEOTotalAmount, 0) AS TOTAL_AMOUNT,
            ISNULL(O.PriceLinePEOTotalQuantity, 0) AS TOTAL_QUANTITY,
            CAST(ISNULL(O.AddDateTime, GETDATE()) AS DATE) AS BZ_LOAD_DATE,
            CAST(GETDATE() AS DATE) AS SV_LOAD_DATE,
            ISNULL(O.AddDateTime, SYSDATETIME()) AS SourceAddDateTime
        INTO #src
        FROM bzo.VRM_PerfObligationsPVO AS O
        WHERE O.AddDateTime > @LastWatermark;

        SELECT @MaxWatermark = MAX(SourceAddDateTime) FROM #src;

        MERGE svo.D_RM_PERF_OBLIGATION AS tgt
        USING #src AS src ON tgt.PERF_OBLIGATION_ID = src.PERF_OBLIGATION_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.BASE_PRICE = src.BASE_PRICE,
            tgt.BASE_PRICE_PERCENTAGE = src.BASE_PRICE_PERCENTAGE,
            tgt.CR_LIABILITY_AMT = src.CR_LIABILITY_AMT,
            tgt.DR_ASSET_AMT = src.DR_ASSET_AMT,
            tgt.DR_DISCOUNT_AMT = src.DR_DISCOUNT_AMT,
            tgt.NET_LINE_AMT_CONTR = src.NET_LINE_AMT_CONTR,
            tgt.TOTAL_BILLED_AMT_CONTR = src.TOTAL_BILLED_AMT_CONTR,
            tgt.TOT_ALLOC_AMT_CONTR = src.TOT_ALLOC_AMT_CONTR,
            tgt.TOTAL_RECOG_REV_AMT_CONTR = src.TOTAL_RECOG_REV_AMT_CONTR,
            tgt.TOT_CARVE_OUT_AMT_CONTR = src.TOT_CARVE_OUT_AMT_CONTR,
            tgt.TOT_NET_CONSIDER_AMT_CONTR = src.TOT_NET_CONSIDER_AMT_CONTR,
            tgt.COST_AMOUNT = src.COST_AMOUNT,
            tgt.CREATED_BY = src.CREATED_BY,
            tgt.CREATION_DATE = src.CREATION_DATE,
            tgt.CUSTOMER_CONTRACT_HEADER_ID = src.CUSTOMER_CONTRACT_HEADER_ID,
            tgt.DISCARD_FLAG = src.DISCARD_FLAG,
            tgt.DISCOUNT_AMOUNT = src.DISCOUNT_AMOUNT,
            tgt.DISCOUNT_PERCENTAGE = src.DISCOUNT_PERCENTAGE,
            tgt.EXEMPT_FROM_ALLOCATION_FLAG = src.EXEMPT_FROM_ALLOCATION_FLAG,
            tgt.FMV_LINE_ID = src.FMV_LINE_ID,
            tgt.GROSS_MARGIN_PERCENTAGE = src.GROSS_MARGIN_PERCENTAGE,
            tgt.INITIAL_PERF_EVT_CREATED_FLAG = src.INITIAL_PERF_EVT_CREATED_FLAG,
            tgt.INITIAL_PERF_EVT_EXPECTED_DATE = src.INITIAL_PERF_EVT_EXPECTED_DATE,
            tgt.INITIAL_PERF_EVT_RECORDED_FLAG = src.INITIAL_PERF_EVT_RECORDED_FLAG,
            tgt.LAST_UPDATE_DATE = src.LAST_UPDATE_DATE,
            tgt.LAST_UPDATED_BY = src.LAST_UPDATED_BY,
            tgt.LATEST_REVISION_INTENT_CODE = src.LATEST_REVISION_INTENT_CODE,
            tgt.LATEST_VERSION_DATE = src.LATEST_VERSION_DATE,
            tgt.LIST_PRICE_AMOUNT = src.LIST_PRICE_AMOUNT,
            tgt.OBLIGATION_REFERENCE = src.OBLIGATION_REFERENCE,
            tgt.FMV_AMT = src.FMV_AMT,
            tgt.NET_LINE_AMT_OBLIG = src.NET_LINE_AMT_OBLIG,
            tgt.NET_SALES_PRICE = src.NET_SALES_PRICE,
            tgt.OBLIG_CURRENCY_CODE = src.OBLIG_CURRENCY_CODE,
            tgt.TOTAL_BILLED_AMT_OBLIG = src.TOTAL_BILLED_AMT_OBLIG,
            tgt.TOT_ALLOC_AMT_OBLIG = src.TOT_ALLOC_AMT_OBLIG,
            tgt.TOTAL_RECOG_REV_AMT_OBLIG = src.TOTAL_RECOG_REV_AMT_OBLIG,
            tgt.TOT_CARVE_OUT_AMT_OBLIG = src.TOT_CARVE_OUT_AMT_OBLIG,
            tgt.TOT_NET_CONSIDER_AMT_OBLIG = src.TOT_NET_CONSIDER_AMT_OBLIG,
            tgt.OBLIG_PAYMENT_AMOUNT = src.OBLIG_PAYMENT_AMOUNT,
            tgt.PERF_OBLIGATION_NUMBER = src.PERF_OBLIGATION_NUMBER,
            tgt.PERF_OBLIGATION_TYPE = src.PERF_OBLIGATION_TYPE,
            tgt.PERF_OBLIG_CLASSIFICATION_CODE = src.PERF_OBLIG_CLASSIFICATION_CODE,
            tgt.PERF_OBLIG_FREEZE_FLAG = src.PERF_OBLIG_FREEZE_FLAG,
            tgt.REMOVED_FLAG = src.REMOVED_FLAG,
            tgt.SATISFACTION_DATE = src.SATISFACTION_DATE,
            tgt.SATISFACTION_METHOD = src.SATISFACTION_METHOD,
            tgt.SATISFACTION_STATUS = src.SATISFACTION_STATUS,
            tgt.UNIT_SELLING_PRICE = src.UNIT_SELLING_PRICE,
            tgt.AVERAGE_PRICE = src.AVERAGE_PRICE,
            tgt.FAIR_MARKET_VALUE = src.FAIR_MARKET_VALUE,
            tgt.FMV_TOLERANCE_HIGH_PCT = src.FMV_TOLERANCE_HIGH_PCT,
            tgt.FMV_TOLERANCE_LOW_PCT = src.FMV_TOLERANCE_LOW_PCT,
            tgt.HIGHEST_PRICE = src.HIGHEST_PRICE,
            tgt.PRICE_LAST_UPDATE_DATE = src.PRICE_LAST_UPDATE_DATE,
            tgt.LINE_COUNT = src.LINE_COUNT,
            tgt.LOWEST_PRICE = src.LOWEST_PRICE,
            tgt.STANDARD_DEVIATION = src.STANDARD_DEVIATION,
            tgt.TOLERANCE_COVERAGE = src.TOLERANCE_COVERAGE,
            tgt.TOLERANCE_COVERAGE_COUNT = src.TOLERANCE_COVERAGE_COUNT,
            tgt.TOLERANCE_RANGE_COVERAGE = src.TOLERANCE_RANGE_COVERAGE,
            tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
            tgt.TOTAL_QUANTITY = src.TOTAL_QUANTITY,
            tgt.BZ_LOAD_DATE = src.BZ_LOAD_DATE,
            tgt.SV_LOAD_DATE = src.SV_LOAD_DATE
        WHEN NOT MATCHED BY TARGET THEN INSERT (
            PERF_OBLIGATION_ID, BASE_PRICE, BASE_PRICE_PERCENTAGE, CR_LIABILITY_AMT, DR_ASSET_AMT, DR_DISCOUNT_AMT, NET_LINE_AMT_CONTR, TOTAL_BILLED_AMT_CONTR, TOT_ALLOC_AMT_CONTR, TOTAL_RECOG_REV_AMT_CONTR, TOT_CARVE_OUT_AMT_CONTR, TOT_NET_CONSIDER_AMT_CONTR, COST_AMOUNT, CREATED_BY, CREATION_DATE, CUSTOMER_CONTRACT_HEADER_ID, DISCARD_FLAG, DISCOUNT_AMOUNT, DISCOUNT_PERCENTAGE, EXEMPT_FROM_ALLOCATION_FLAG, FMV_LINE_ID, GROSS_MARGIN_PERCENTAGE, INITIAL_PERF_EVT_CREATED_FLAG, INITIAL_PERF_EVT_EXPECTED_DATE, INITIAL_PERF_EVT_RECORDED_FLAG, LAST_UPDATE_DATE, LAST_UPDATED_BY, LATEST_REVISION_INTENT_CODE, LATEST_VERSION_DATE, LIST_PRICE_AMOUNT, OBLIGATION_REFERENCE, FMV_AMT, NET_LINE_AMT_OBLIG, NET_SALES_PRICE, OBLIG_CURRENCY_CODE, TOTAL_BILLED_AMT_OBLIG, TOT_ALLOC_AMT_OBLIG, TOTAL_RECOG_REV_AMT_OBLIG, TOT_CARVE_OUT_AMT_OBLIG, TOT_NET_CONSIDER_AMT_OBLIG, OBLIG_PAYMENT_AMOUNT, PERF_OBLIGATION_NUMBER, PERF_OBLIGATION_TYPE, PERF_OBLIG_CLASSIFICATION_CODE, PERF_OBLIG_FREEZE_FLAG, REMOVED_FLAG, SATISFACTION_DATE, SATISFACTION_METHOD, SATISFACTION_STATUS, UNIT_SELLING_PRICE, AVERAGE_PRICE, FAIR_MARKET_VALUE, FMV_TOLERANCE_HIGH_PCT, FMV_TOLERANCE_LOW_PCT, HIGHEST_PRICE, PRICE_LAST_UPDATE_DATE, LINE_COUNT, LOWEST_PRICE, STANDARD_DEVIATION, TOLERANCE_COVERAGE, TOLERANCE_COVERAGE_COUNT, TOLERANCE_RANGE_COVERAGE, TOTAL_AMOUNT, TOTAL_QUANTITY, BZ_LOAD_DATE, SV_LOAD_DATE
        ) VALUES (
            src.PERF_OBLIGATION_ID, src.BASE_PRICE, src.BASE_PRICE_PERCENTAGE, src.CR_LIABILITY_AMT, src.DR_ASSET_AMT, src.DR_DISCOUNT_AMT, src.NET_LINE_AMT_CONTR, src.TOTAL_BILLED_AMT_CONTR, src.TOT_ALLOC_AMT_CONTR, src.TOTAL_RECOG_REV_AMT_CONTR, src.TOT_CARVE_OUT_AMT_CONTR, src.TOT_NET_CONSIDER_AMT_CONTR, src.COST_AMOUNT, src.CREATED_BY, src.CREATION_DATE, src.CUSTOMER_CONTRACT_HEADER_ID, src.DISCARD_FLAG, src.DISCOUNT_AMOUNT, src.DISCOUNT_PERCENTAGE, src.EXEMPT_FROM_ALLOCATION_FLAG, src.FMV_LINE_ID, src.GROSS_MARGIN_PERCENTAGE, src.INITIAL_PERF_EVT_CREATED_FLAG, src.INITIAL_PERF_EVT_EXPECTED_DATE, src.INITIAL_PERF_EVT_RECORDED_FLAG, src.LAST_UPDATE_DATE, src.LAST_UPDATED_BY, src.LATEST_REVISION_INTENT_CODE, src.LATEST_VERSION_DATE, src.LIST_PRICE_AMOUNT, src.OBLIGATION_REFERENCE, src.FMV_AMT, src.NET_LINE_AMT_OBLIG, src.NET_SALES_PRICE, src.OBLIG_CURRENCY_CODE, src.TOTAL_BILLED_AMT_OBLIG, src.TOT_ALLOC_AMT_OBLIG, src.TOTAL_RECOG_REV_AMT_OBLIG, src.TOT_CARVE_OUT_AMT_OBLIG, src.TOT_NET_CONSIDER_AMT_OBLIG, src.OBLIG_PAYMENT_AMOUNT, src.PERF_OBLIGATION_NUMBER, src.PERF_OBLIGATION_TYPE, src.PERF_OBLIG_CLASSIFICATION_CODE, src.PERF_OBLIG_FREEZE_FLAG, src.REMOVED_FLAG, src.SATISFACTION_DATE, src.SATISFACTION_METHOD, src.SATISFACTION_STATUS, src.UNIT_SELLING_PRICE, src.AVERAGE_PRICE, src.FAIR_MARKET_VALUE, src.FMV_TOLERANCE_HIGH_PCT, src.FMV_TOLERANCE_LOW_PCT, src.HIGHEST_PRICE, src.PRICE_LAST_UPDATE_DATE, src.LINE_COUNT, src.LOWEST_PRICE, src.STANDARD_DEVIATION, src.TOLERANCE_COVERAGE, src.TOLERANCE_COVERAGE_COUNT, src.TOLERANCE_RANGE_COVERAGE, src.TOTAL_AMOUNT, src.TOTAL_QUANTITY, src.BZ_LOAD_DATE, src.SV_LOAD_DATE
        )
        OUTPUT $action INTO @MergeActions(ActionTaken);

        SELECT @RowInserted = SUM(CASE WHEN ActionTaken = 'INSERT' THEN 1 ELSE 0 END),
               @RowUpdated  = SUM(CASE WHEN ActionTaken = 'UPDATE' THEN 1 ELSE 0 END)
        FROM @MergeActions;

        IF @MaxWatermark IS NOT NULL
            UPDATE etl.ETL_WATERMARK SET LAST_WATERMARK = @MaxWatermark, UDT_DATE = SYSDATETIME() WHERE TABLE_NAME = @TargetObject;

        SET @EndDttm = SYSDATETIME();
        UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'SUCCESS', ROW_INSERTED = @RowInserted, ROW_UPDATED = @RowUpdated, ROW_EXPIRED = 0, ERROR_MESSAGE = NULL WHERE RUN_ID = @RunId;
    END TRY
    BEGIN CATCH
        SET @EndDttm = SYSDATETIME();
        SET @ErrMsg = CONCAT('Error ', ERROR_NUMBER(), ' (Line ', ERROR_LINE(), '): ', ERROR_MESSAGE());
        IF @RunId IS NOT NULL
            UPDATE etl.ETL_RUN SET END_DTTM = @EndDttm, STATUS = 'FAILURE', ROW_INSERTED = @RowInserted, ROW_UPDATED = @RowUpdated, ROW_EXPIRED = 0, ERROR_MESSAGE = @ErrMsg WHERE RUN_ID = @RunId;
        ;THROW;
    END CATCH
END;
GO
