-- Rebuild Dimensions from scratch. EVERYTHING WILL BE REPLACED! ---
 
/* =================
   BUSINESS_OFFERING
   ================= */
--IF OBJECT_ID(N'svo.D_BUSINESS_OFFERING', 'U') IS NOT NULL
--    DROP TABLE svo.D_BUSINESS_OFFERING;
--GO

--CREATE TABLE svo.D_BUSINESS_OFFERING
--(
--    BUSINESS_OFFERING_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--    BUSINESS_OFFERING_ID        VARCHAR(100) NOT NULL,
--    BUSINESS_OFFERING_LVL1_CODE VARCHAR(100) NULL,
--    BUSINESS_OFFERING_LVL1_DESC VARCHAR(500) NULL,
--    BUSINESS_OFFERING_LVL2_CODE VARCHAR(25) NULL,
--    BUSINESS_OFFERING_LVL2_DESC VARCHAR(500) NULL,
--    BUSINESS_OFFERING_LVL3_CODE VARCHAR(25) NULL,
--    BUSINESS_OFFERING_LVL3_DESC VARCHAR(500) NULL,
--    BUSINESS_OFFERING_LVL4_CODE VARCHAR(150) NULL,
--    BUSINESS_OFFERING_LVL4_DESC VARCHAR(500) NULL,
--    BUSINESS_OFFERING_LVL5_CODE VARCHAR(100) NULL,
--    BUSINESS_OFFERING_LVL5_DESC VARCHAR(500) NULL,
--    BUSINESS_OFFERING_DISTANCE  SMALLINT NULL,
--    BUSINESS_OFFERING_CATEGORY  VARCHAR(60) NULL,
--    BUSINESS_OFFERING_ENABLED_FLAG VARCHAR(4) NULL,
--    START_DATE_ACTIVE     DATE NOT NULL,
--    END_DATE_ACTIVE       DATE NOT NULL,
--    CREATED_BY            VARCHAR(64) NULL,
--    CREATION_DATE         DATE NULL,
--    BZ_LOAD_DATE          DATE NULL,
--    SV_LOAD_DATE          DATE NULL
--) ON FG_SilverDim;
--GO

TRUNCATE TABLE svo.D_BUSINESS_OFFERING;
GO

INSERT INTO svo.D_BUSINESS_OFFERING (
     BUSINESS_OFFERING_ID,
     BUSINESS_OFFERING_LVL1_CODE,
     BUSINESS_OFFERING_LVL1_DESC,
     BUSINESS_OFFERING_LVL2_CODE,
     BUSINESS_OFFERING_LVL2_DESC,
     BUSINESS_OFFERING_LVL3_CODE,
     BUSINESS_OFFERING_LVL3_DESC,
     BUSINESS_OFFERING_LVL4_CODE,
     BUSINESS_OFFERING_LVL4_DESC,
     BUSINESS_OFFERING_LVL5_CODE,
     BUSINESS_OFFERING_LVL5_DESC,
     BUSINESS_OFFERING_DISTANCE,
     BUSINESS_OFFERING_CATEGORY,
     BUSINESS_OFFERING_ENABLED_FLAG,
     START_DATE_ACTIVE,
     END_DATE_ACTIVE,
     CREATED_BY,
     CREATION_DATE,
     BZ_LOAD_DATE,
     SV_LOAD_DATE
)
SELECT
    ISNULL(TRIM(lvl5.VALUE),'-1') AS BUSINESS_OFFERING_ID,
    COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL1_CODE,
    COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL1_DESC,
    COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL2_CODE,
    COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL2_DESC,
    COALESCE(h1.DEP29PK1VALUE,h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL3_CODE,
    COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL3_DESC,
    COALESCE(h1.DEP28PK1VALUE,lvl5.VALUE) AS BUSINESS_OFFERING_LVL4_CODE,
    COALESCE(lvl4.DESCRIPTION,lvl5.DESCRIPTION) AS BUSINESS_OFFERING_LVL4_DESC,
    lvl5.VALUE       AS BUSINESS_OFFERING_LVL5_CODE,
    lvl5.DESCRIPTION AS BUSINESS_OFFERING_LVL5_DESC,
    0                  AS BUSINESS_OFFERING_DISTANCE,
    lvl5.ATTRIBUTECATEGORY AS BUSINESS_OFFERING_CATEGORY,
    lvl5.ENABLEDFLAG AS BUSINESS_OFFERING_ENABLED_FLAG,
    ISNULL(lvl5.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
    ISNULL(lvl5.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
    lvl5.CREATEDBY AS CREATED_BY,
    CAST(lvl5.CREATIONDATE AS DATE) AS CREATION_DATE,
    COALESCE(CAST(h1.AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM bzo.GL_SegmentValueHierarchyExtractPVO h1 
INNER JOIN bzo.GL_FndTreeAndVersionVO ver1 
    ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'BUSINESS OFFERING LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP28PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
RIGHT JOIN bzo.GL_ValueSetValuesPVO lvl5 ON lvl5.VALUE = h1.DEP0PK1VALUE AND lvl5.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR'
WHERE lvl5.ATTRIBUTECATEGORY = 'BUSINESS OFFERING LAMAR' AND lvl5.SUMMARYFLAG = 'N'
--and ISNULL(TRIM(lvl5.VALUE),'-1') = '214'
GO

	
--IF EXISTS (SELECT 1 FROM svo.D_BUSINESS_OFFERING  WHERE (BUSINESS_OFFERING_ID = '-1') ) DELETE FROM svo.D_BUSINESS_OFFERING  WHERE (BUSINESS_OFFERING_ID = '-1');



--/* =========================
--   BUSINESS OFFERING
--   ========================= */
--IF NOT EXISTS (SELECT 1 FROM sys.indexes  WHERE name = 'UX_D_BUSINESS_OFFERING_ID' AND object_id = OBJECT_ID('svo.D_BUSINESS_OFFERING'))
--BEGIN
--    CREATE UNIQUE NONCLUSTERED INDEX UX_D_BUSINESS_OFFERING_ID ON svo.D_BUSINESS_OFFERING(BUSINESS_OFFERING_ID) ON FG_SilverDim;
--END

IF NOT EXISTS (SELECT 1 FROM svo.D_BUSINESS_OFFERING WHERE BUSINESS_OFFERING_SK = 0)
BEGIN
    SET IDENTITY_INSERT svo.D_BUSINESS_OFFERING ON;

    INSERT INTO svo.D_BUSINESS_OFFERING(BUSINESS_OFFERING_SK,BUSINESS_OFFERING_ID,BUSINESS_OFFERING_LVL1_CODE,
                BUSINESS_OFFERING_LVL1_DESC,BUSINESS_OFFERING_LVL2_CODE,BUSINESS_OFFERING_LVL2_DESC,BUSINESS_OFFERING_LVL3_CODE,
                BUSINESS_OFFERING_LVL3_DESC,BUSINESS_OFFERING_LVL4_CODE,BUSINESS_OFFERING_LVL4_DESC,BUSINESS_OFFERING_LVL5_CODE,
                BUSINESS_OFFERING_LVL5_DESC,BUSINESS_OFFERING_DISTANCE,BUSINESS_OFFERING_CATEGORY,BUSINESS_OFFERING_ENABLED_FLAG,
                START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,CREATION_DATE) 
    VALUES (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',0,'Missing','NULL','0001-01-01','9999-12-31',
            'UNK','2025-10-18');

    SET IDENTITY_INSERT svo.D_BUSINESS_OFFERING OFF;
END
GO
