 
/* ===========
   COST_CENTER
   =========== */
--IF OBJECT_ID(N'svo.D_COST_CENTER', 'U') IS NOT NULL
--    DROP TABLE svo.D_COST_CENTER;
--GO

--CREATE TABLE svo.D_COST_CENTER
--(
--    COST_CENTER_SK        BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--    COST_CENTER_ID        VARCHAR(100) NOT NULL,
--    COST_CENTER_LVL1_CODE VARCHAR(100) NULL,
--    COST_CENTER_LVL1_DESC VARCHAR(500) NULL,
--    COST_CENTER_LVL2_CODE VARCHAR(25) NULL,
--    COST_CENTER_LVL2_DESC VARCHAR(500) NULL,
--    COST_CENTER_LVL3_CODE VARCHAR(25) NULL,
--    COST_CENTER_LVL3_DESC VARCHAR(500) NULL,
--    COST_CENTER_LVL4_CODE VARCHAR(150) NULL,
--    COST_CENTER_LVL4_DESC VARCHAR(500) NULL,
--    COST_CENTER_DISTANCE  SMALLINT NULL,
--    COST_CENTER_CATEGORY  VARCHAR(60) NULL,
--    COST_CENTER_ENABLED_FLAG VARCHAR(4) NULL,
--    START_DATE_ACTIVE     DATE NOT NULL,
--    END_DATE_ACTIVE       DATE NOT NULL,
--    CREATED_BY            VARCHAR(64) NULL,
--    CREATION_DATE         DATE NULL,
--    BZ_LOAD_DATE          DATE NULL,
--    SV_LOAD_DATE          DATE NULL
--) ON FG_SilverDim;
--GO

TRUNCATE TABLE svo.D_COST_CENTER;
GO

INSERT INTO svo.D_COST_CENTER (
     COST_CENTER_ID,
     COST_CENTER_LVL1_CODE,
     COST_CENTER_LVL1_DESC,
     COST_CENTER_LVL2_CODE,
     COST_CENTER_LVL2_DESC,
     COST_CENTER_LVL3_CODE,
     COST_CENTER_LVL3_DESC,
     COST_CENTER_LVL4_CODE,
     COST_CENTER_LVL4_DESC,
     COST_CENTER_DISTANCE,
     COST_CENTER_CATEGORY,
     COST_CENTER_ENABLED_FLAG,
     START_DATE_ACTIVE,
     END_DATE_ACTIVE,
     CREATED_BY,
     CREATION_DATE,
     BZ_LOAD_DATE,
     SV_LOAD_DATE
)
SELECT
    ISNULL(TRIM(lvl4.VALUE),'-1') AS COST_CENTER_ID,
    COALESCE(h1.DEP31PK1VALUE,h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,lvl4.VALUE) AS COST_CENTER_LVL1_CODE,
    COALESCE(lvl1.DESCRIPTION,lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION) AS COST_CENTER_LVL1_DESC,
    COALESCE(h1.DEP30PK1VALUE,h1.DEP29PK1VALUE,lvl4.VALUE) AS COST_CENTER_LVL2_CODE,
    COALESCE(lvl2.DESCRIPTION,lvl3.DESCRIPTION,lvl4.DESCRIPTION) AS COST_CENTER_LVL2_DESC,
    COALESCE(h1.DEP29PK1VALUE,lvl4.VALUE) AS COST_CENTER_LVL3_CODE,
    COALESCE(lvl3.DESCRIPTION,lvl4.DESCRIPTION) AS COST_CENTER_LVL3_DESC,
    lvl4.VALUE       AS COST_CENTER_LVL4_CODE,
    lvl4.DESCRIPTION AS COST_CENTER_LVL4_DESC,
    0                  AS COST_CENTER_DISTANCE,
    lvl4.ATTRIBUTECATEGORY AS COST_CENTER_CATEGORY,
    lvl4.ENABLEDFLAG AS COST_CENTER_ENABLED_FLAG,
    ISNULL(lvl4.STARTDATEACTIVE, '0001-01-01') AS START_DATE_ACTIVE,
    ISNULL(lvl4.ENDDATEACTIVE,  '9999-12-31') AS END_DATE_ACTIVE,
    lvl4.CREATEDBY AS CREATED_BY,
    CAST(lvl4.CREATIONDATE AS DATE) AS CREATION_DATE,
    COALESCE(CAST(h1.AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
    CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM bzo.GL_SegmentValueHierarchyExtractPVO h1 
INNER JOIN bzo.GL_FndTreeAndVersionVO ver1 
    ON ver1.TREEVERSIONID = h1.TREEVERSIONID AND ver1.TREENAME LIKE 'CENTER LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl1 ON lvl1.VALUE = h1.DEP31PK1VALUE AND lvl1.ATTRIBUTECATEGORY = 'CENTER LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl2 ON lvl2.VALUE = h1.DEP30PK1VALUE AND lvl2.ATTRIBUTECATEGORY = 'CENTER LAMAR'
INNER JOIN bzo.GL_ValueSetValuesPVO lvl3 ON lvl3.VALUE = h1.DEP29PK1VALUE AND lvl3.ATTRIBUTECATEGORY = 'CENTER LAMAR'
RIGHT JOIN bzo.GL_ValueSetValuesPVO lvl4 ON lvl4.VALUE = h1.DEP0PK1VALUE AND lvl4.ATTRIBUTECATEGORY = 'CENTER LAMAR'
WHERE lvl4.ATTRIBUTECATEGORY = 'CENTER LAMAR' AND lvl4.SUMMARYFLAG = 'N';
GO
 
 
--IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_COST_CENTER_ID' AND object_id = OBJECT_ID('svo.D_COST_CENTER'))
--BEGIN
--    CREATE UNIQUE NONCLUSTERED INDEX UX_D_COST_CENTER_ID ON svo.D_COST_CENTER(COST_CENTER_ID) ON FG_SilverDim;
--END

IF NOT EXISTS (SELECT 1 FROM svo.D_COST_CENTER WHERE COST_CENTER_SK = 0)
BEGIN
    SET IDENTITY_INSERT svo.D_COST_CENTER ON;

    INSERT INTO svo.D_COST_CENTER (COST_CENTER_SK,COST_CENTER_ID,COST_CENTER_LVL1_CODE,COST_CENTER_LVL1_DESC,COST_CENTER_LVL2_CODE,
            COST_CENTER_LVL2_DESC,COST_CENTER_LVL3_CODE,COST_CENTER_LVL3_DESC,COST_CENTER_LVL4_CODE,COST_CENTER_LVL4_DESC,
            COST_CENTER_DISTANCE,COST_CENTER_CATEGORY,COST_CENTER_ENABLED_FLAG,START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,
            CREATION_DATE) 
    VALUES (0,'-1','-1','Unknown','-1','Unknown','-1','Unknown','-1','Unknown',0,'Missing','NULL','0001-01-01','9999-12-31','UNK','2025-10-18');

    SET IDENTITY_INSERT svo.D_COST_CENTER OFF;
END
GO
