 

--IF OBJECT_ID('svo.D_AP_INVOICE_HEADER','U') IS NOT NULL 
--    DROP TABLE svo.D_AP_INVOICE_HEADER;
--GO

--CREATE TABLE svo.D_AP_INVOICE_HEADER
--(
--    AP_INVOICE_HEADER_SK   BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--    INVOICE_ID             BIGINT        NOT NULL,
--    INVOICE_NUMBER         VARCHAR(50)   NOT NULL,
--    VENDOR_SITE_SK         BIGINT        NOT NULL,
--    INVOICE_DATE_SK        INT           NOT NULL,
--    GL_DATE_SK             INT           NOT NULL,
--    INVOICE_TYPE_CODE      VARCHAR(25)   NOT NULL,
--    INVOICE_CURRENCY_CODE  VARCHAR(15)   NOT NULL,
--    PAYMENT_CURRENCY_CODE  VARCHAR(15)   NOT NULL,
--    APPROVAL_STATUS        VARCHAR(25)   NOT NULL,
--    PAYMENT_STATUS_FLAG    VARCHAR(1)    NOT NULL,
--    TERMS_DATE_SK          INT           NOT NULL,
--    INVOICE_AMOUNT         DECIMAL(29,4) NOT NULL,
--    AMOUNT_PAID            DECIMAL(29,4) NOT NULL,
--    DISCOUNT_AMOUNT_TAKEN  DECIMAL(29,4) NOT NULL,
--    CANCELLED_AMOUNT       DECIMAL(29,4) NOT NULL,
--    CANCELLED_BY           VARCHAR(64)   NOT NULL,
--    CANCELLED_DATE_SK      INT           NOT NULL,
--    EXCLUDE_FREIGHT_FROM_DISC VARCHAR(1) NOT NULL,
--    DESCRIPTION            VARCHAR(240)  NOT NULL,
--    PAYMENT_TERMS          VARCHAR(30)   NOT NULL,
--    CODE_COMBINATION_ID    BIGINT        NULL,
--    BZ_LOAD_DATE           DATE          NOT NULL,
--    SV_LOAD_DATE           DATE          NOT NULL
--) ON [FG_SilverDim];
--GO

--CREATE UNIQUE NONCLUSTERED INDEX UX_D_AP_INVOICE_HEADER_CURR
--    ON svo.D_AP_INVOICE_HEADER (INVOICE_ID)
--    ON [FG_SilverDim];
--GO

TRUNCATE TABLE svo.D_AP_INVOICE_HEADER;
GO

IF NOT EXISTS (SELECT 1 FROM svo.D_AP_INVOICE_HEADER WHERE AP_INVOICE_HEADER_SK = 0)
BEGIN
    SET IDENTITY_INSERT svo.D_AP_INVOICE_HEADER ON;

    INSERT INTO svo.D_AP_INVOICE_HEADER
    (AP_INVOICE_HEADER_SK, INVOICE_ID, INVOICE_NUMBER, VENDOR_SITE_SK, INVOICE_DATE_SK, GL_DATE_SK,
     INVOICE_TYPE_CODE, INVOICE_CURRENCY_CODE, PAYMENT_CURRENCY_CODE,
     APPROVAL_STATUS, PAYMENT_STATUS_FLAG, TERMS_DATE_SK,
     INVOICE_AMOUNT, AMOUNT_PAID, DISCOUNT_AMOUNT_TAKEN, CANCELLED_AMOUNT,
     CANCELLED_BY, CANCELLED_DATE_SK, EXCLUDE_FREIGHT_FROM_DISC, DESCRIPTION, PAYMENT_TERMS,
     CODE_COMBINATION_ID, BZ_LOAD_DATE, SV_LOAD_DATE)
    VALUES
    (0, -1, 'Unknown', 0, 10101, 10101,
     'UNK', 'UNK', 'UNK',
     'U', 'U', 10101,
     0, 0, 0, 0,
     'UNK', 10101, 'U', 'UNK', 'UNK',
     NULL, CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE));

    SET IDENTITY_INSERT svo.D_AP_INVOICE_HEADER OFF;
END;
GO

INSERT INTO svo.D_AP_INVOICE_HEADER
(
    INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_SITE_SK,
    INVOICE_DATE_SK,
    GL_DATE_SK,
    INVOICE_TYPE_CODE,
    INVOICE_CURRENCY_CODE,
    PAYMENT_CURRENCY_CODE,
    APPROVAL_STATUS,
    PAYMENT_STATUS_FLAG,
    TERMS_DATE_SK,
    INVOICE_AMOUNT,
    AMOUNT_PAID,
    DISCOUNT_AMOUNT_TAKEN,
    CANCELLED_AMOUNT,
    CANCELLED_BY,
    CANCELLED_DATE_SK,
    EXCLUDE_FREIGHT_FROM_DISC,
    DESCRIPTION,
    PAYMENT_TERMS,
    CODE_COMBINATION_ID,
    BZ_LOAD_DATE,
    SV_LOAD_DATE
)
SELECT
    H.ApInvoicesInvoiceId,
    H.ApInvoicesInvoiceNum,
    ISNULL(VS.VENDOR_SITE_SK,0) AS VENDOR_SITE_SK,
    CONVERT(INT, CONVERT(CHAR(8), ISNULL(H.ApInvoicesInvoiceDate,'0001-01-01'), 112)),
    CONVERT(INT, CONVERT(CHAR(8), ISNULL(H.ApInvoicesGlDate,'0001-01-01'), 112)),
    ISNULL(H.ApInvoicesInvoiceTypeLookupCode,'UNK'),
    ISNULL(H.ApInvoicesInvoiceCurrencyCode,'UNK'),
    ISNULL(H.ApInvoicesPaymentCurrencyCode,'UNK'),
    ISNULL(H.ApInvoicesApprovalStatus,'U'),
    ISNULL(H.ApInvoicesPaymentStatusFlag,'U'),
    CONVERT(INT, CONVERT(CHAR(8), ISNULL(H.ApInvoicesTermsDate,'0001-01-01'), 112)),
    ISNULL(H.ApInvoicesInvoiceAmount,0),
    ISNULL(H.ApInvoicesAmountPaid,0),
    ISNULL(H.ApInvoicesDiscountAmountTaken,0),
    ISNULL(H.ApInvoicesCancelledAmount,0),
    ISNULL(H.ApInvoicesCancelledBy,'UNK'),
    CONVERT(INT, CONVERT(CHAR(8), ISNULL(H.ApInvoicesCancelledDate,'0001-01-01'), 112)),
    ISNULL(H.ApInvoicesExcludeFreightFromDiscount,'U'),
    ISNULL(H.ApInvoicesDescription,'UNK'),
    ISNULL(PT.PAYMENT_TERM_NAME,'UNK'),
    H.ApInvoicesAcctsPayCodeCombinationId,
    CAST(ISNULL(H.AddDateTime, GETDATE()) AS DATE),
    CAST(GETDATE() AS DATE)
FROM bzo.AP_InvoiceHeaderExtractPVO H
LEFT JOIN svo.D_PAYMENT_TERM AS PT ON PT.PAYMENT_TERM_ID = H.ApInvoicesTermsId
LEFT JOIN svo.D_VENDOR_SITE  AS VS ON VS.VENDOR_ID = H.ApInvoicesVendorId AND VS.VENDOR_SITE_ID = H.ApInvoicesVendorSiteId

GO
