


--IF OBJECT_ID('svo.D_AP_DISBURSEMENT_HEADER','U') IS NOT NULL DROP TABLE svo.D_AP_DISBURSEMENT_HEADER;
--GO

--CREATE TABLE svo.D_AP_DISBURSEMENT_HEADER(
--    AP_DISBURSEMENT_HEADER_SK      BIGINT IDENTITY(1,1) PRIMARY KEY,
--    CHECK_ID                       BIGINT NOT NULL,    
--    CHECK_DATE_SK                  INT NOT NULL,
--    CLEARED_DATE_SK                INT NULL,
--    VOID_DATE_SK                   INT NULL,
--    PAYMENT_METHOD                 VARCHAR(30) NOT NULL DEFAULT 1,
--    CHECK_NUMBER                   BIGINT NOT NULL,
--    VOUCHER_NUM                    BIGINT NULL,
--    BANK_ACCOUNT_NUM               VARCHAR(30) NULL,
--    AMOUNT                         DECIMAL(29,4) NOT NULL,
--    BASE_AMOUNT                    DECIMAL(29,4) NULL,
--    CLEARED_AMOUNT                 DECIMAL(29,4) NULL,
--    CLEARED_CHARGES_AMOUNT         DECIMAL(29,4) NULL,
--    BZ_LOAD_DATE                   DATE NULL,
--    SV_LOAD_DATE                   DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE)
--) ON [FG_SilverFact];

--CREATE UNIQUE INDEX UQ_D_AP_DISBURSEMENT_HEADER_GRAIN ON svo.D_AP_DISBURSEMENT_HEADER(CHECK_ID) ON [FG_SilverFact];
--GO

TRUNCATE TABLE svo.D_AP_DISBURSEMENT_HEADER;
GO

SET IDENTITY_INSERT svo.D_AP_DISBURSEMENT_HEADER ON;
INSERT INTO svo.D_AP_DISBURSEMENT_HEADER(AP_DISBURSEMENT_HEADER_SK, CHECK_ID,  PAYMENT_METHOD, CHECK_DATE_SK,CHECK_NUMBER,AMOUNT, BZ_LOAD_DATE, SV_LOAD_DATE)
VALUES(0,-1,'UNK',0,0,-1, CAST(GETDATE() AS DATE),CAST(GETDATE() AS DATE));
SET IDENTITY_INSERT svo.D_AP_DISBURSEMENT_HEADER OFF;
GO

/* D_AP_DISBURSEMENT_HEADER load */
INSERT INTO svo.D_AP_DISBURSEMENT_HEADER(
    CHECK_ID, 
    CHECK_NUMBER, 
    CHECK_DATE_SK, 
    CLEARED_DATE_SK, 
    VOID_DATE_SK,
    VOUCHER_NUM, 
    BANK_ACCOUNT_NUM,
    PAYMENT_METHOD, 
    AMOUNT, 
    BASE_AMOUNT, 
    CLEARED_AMOUNT, 
    CLEARED_CHARGES_AMOUNT, 
    BZ_LOAD_DATE, 
    SV_LOAD_DATE
)
SELECT 
    D.ApChecksAllCheckId AS ApChecksAllCheckId,
    D.ApChecksAllCheckNumber AS ApChecksAllCheckNumber,
    CONVERT(INT, FORMAT(ISNULL(D.ApChecksAllCheckDate,'0001-01-01'),'yyyyMMdd')) AS CHECK_DATE_SK,
    CONVERT(INT, FORMAT(ISNULL(D.ApChecksAllClearedDate,'0001-01-01'),'yyyyMMdd')) AS CLEARED_DATE_SK,
    CONVERT(INT, FORMAT(ISNULL(D.ApChecksAllVoidDate,'0001-01-01'),'yyyyMMdd')) AS VOID_DATE_SK,
    ISNULL(D.ApChecksAllCheckVoucherNum,-1) AS ApChecksAllCheckVoucherNum,
    ISNULL(D.ApChecksAllBankAccountNum,-1) AS ApChecksAllBankAccountNum,
    ISNULL(PM.PAYMENT_METHOD_NAME,'UNK') AS PAYMENT_METHOD,
    ISNULL(D.ApChecksAllAmount,0) AS ApChecksAllAmount,
    ISNULL(D.ApChecksAllBaseAmount,0) AS ApChecksAllBaseAmount,
    ISNULL(D.ApChecksAllClearedAmount,0) AS ApChecksAllClearedAmount,
    ISNULL(D.ApChecksAllClearedChargesAmount,0) AS ApChecksAllClearedChargesAmount,
    CAST(D.AddDateTime as DATE) AS BZ_LOAD_DATE,
    CAST(GETDATE() as DATE) AS SV_LOAD_DATE
FROM bzo.AP_DisbursementHeaderExtractPVO D
LEFT JOIN svo.D_PAYMENT_METHOD     AS PM  ON PM.PAYMENT_METHOD_ID   = D.ApChecksAllPaymentMethodCode

--WHERE NOT EXISTS (
--    SELECT 1 FROM svo.D_AP_DISBURSEMENT_HEADER F WHERE F.CHECK_ID = D.ApChecksAllCheckId
--);

 