
--/* ======
--   LEDGER
--   ====== */
--IF OBJECT_ID(N'svo.D_LEDGER', 'U') IS NOT NULL
--    DROP TABLE svo.D_LEDGER;
--GO

--CREATE TABLE svo.D_LEDGER(
--    LEDGER_SK                         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--    LEDGER_ID                         BIGINT           NULL,
--    LEDGER_NAME                       VARCHAR(240)     NULL,
--    LEDGER_ACCOUNTED_PERIOD_TYPE      VARCHAR(100)     NULL,
--    LEDGER_CHART_OF_ACCOUNTS_ID       BIGINT           NULL,
--    LEDGER_CURRENCY_CODE              VARCHAR(15)      NULL,
--    LEDGER_DESCRIPTION                VARCHAR(500)     NULL,
--    LEDGER_CATEGORY_CODE              VARCHAR(100)     NULL,
--    LEDGER_PERIOD_SET_NAME            VARCHAR(100)     NULL,
--    LEDGER_SHORT_NAME                 VARCHAR(50)      NULL,
--    BZ_LOAD_DATE                      DATE             NULL,
--    SV_LOAD_DATE                      DATE             NULL
--) ON FG_SilverDim;
--GO

TRUNCATE TABLE svo.D_LEDGER;
GO

INSERT INTO svo.D_LEDGER (
     LEDGER_ID,
     LEDGER_NAME,
     LEDGER_ACCOUNTED_PERIOD_TYPE,
     LEDGER_CHART_OF_ACCOUNTS_ID,
     LEDGER_CURRENCY_CODE,
     LEDGER_DESCRIPTION,
     LEDGER_CATEGORY_CODE,
     LEDGER_PERIOD_SET_NAME,
     LEDGER_SHORT_NAME,
     BZ_LOAD_DATE,
     SV_LOAD_DATE
)
SELECT 
   LedgerLedgerId,
   LedgerName,
   LedgerAccountedPeriodType,
   LedgerChartOfAccountsId,
   LedgerCurrencyCode,
   LedgerDescription,
   LedgerLedgerCategoryCode,
   LedgerPeriodSetName,
   LedgerShortName,
   COALESCE(CAST(AddDateTime AS DATE), CAST('0001-01-01' AS DATE)) AS BZ_LOAD_DATE,
   CAST(GETDATE() AS DATE) AS SV_LOAD_DATE
FROM Oracle_Reporting_P2.bzo.GL_LedgerExtractPVO;
GO


--IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_D_LEDGER_ID' AND object_id = OBJECT_ID('svo.D_LEDGER'))
--BEGIN
--    CREATE UNIQUE NONCLUSTERED INDEX UX_D_LEDGER_ID ON svo.D_LEDGER(LEDGER_ID) ON FG_SilverDim;
--END

IF NOT EXISTS (SELECT 1 FROM svo.D_LEDGER WHERE LEDGER_SK=0)
BEGIN
  SET IDENTITY_INSERT svo.D_LEDGER ON;
INSERT INTO svo.D_LEDGER (
         LEDGER_SK, LEDGER_ID,LEDGER_NAME,LEDGER_ACCOUNTED_PERIOD_TYPE,LEDGER_CHART_OF_ACCOUNTS_ID,LEDGER_CURRENCY_CODE
        ,LEDGER_DESCRIPTION,LEDGER_CATEGORY_CODE,LEDGER_PERIOD_SET_NAME,LEDGER_SHORT_NAME,BZ_LOAD_DATE,SV_LOAD_DATE
    )
  SELECT
     0 AS LEDGER_SK,-1 AS LEDGER_ID,'Unknown' AS LEDGER_NAME,'NULL' AS LEDGER_ACCOUNTED_PERIOD_TYPE,0 AS LEDGER_CHART_OF_ACCOUNTS_ID,
     'NULL' AS LEDGER_CURRENCY_CODE,'NULL' AS LEDGER_DESCRIPTION, 0 AS LEDGER_CATEGORY_CODE, 'NULL' AS LEDGER_PERIOD_SET_NAME,
     'NULL' AS LEDGER_SHORT_NAME, GETDATE() BZ_LOAD_DATE, GETDATE()SV_LOAD_DATE;

  SET IDENTITY_INSERT svo.D_LEDGER OFF;
END;
