PRINT CONCAT(CHAR(10),CHAR(13),'10_LINES_CODE_COMBO_LOOKUP... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 10_LINES_CODE_COMBO_LOOKUP.sql

PRINT CONCAT(CHAR(10),CHAR(13),'20_D_ACCOUNT... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 20_D_ACCOUNT.sql

PRINT CONCAT(CHAR(10),CHAR(13),'30_BUSINESS_OFFERING... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 30_BUSINESS_OFFERING.sql

PRINT CONCAT(CHAR(10),CHAR(13),'40_COMPANY... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 40_COMPANY.sql

PRINT CONCAT(CHAR(10),CHAR(13),'50_COST_CENTER... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 50_COST_CENTER.sql

PRINT CONCAT(CHAR(10),CHAR(13),'60_INDUSTRY... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 60_INDUSTRY.sql

PRINT CONCAT(CHAR(10),CHAR(13),'70_INTERCOMPANY... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 70_INTERCOMPANY.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_BUSINESS_UNIT... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_BUSINESS_UNIT.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_CALENDAR... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_CALENDAR.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_CURRENCY... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_CURRENCY.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_LEDGER... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_LEDGER.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_LEGAL_ENTITY... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_LEGAL_ENTITY.sql

--PRINT CONCAT(CHAR(10),CHAR(13),'D_PAYMENT_METHOD... Start ',CONVERT(varchar(19), GETDATE(), 120));
--:r D_PAYMENT_METHOD.sql

--PRINT CONCAT(CHAR(10),CHAR(13),'D_PAYMENT_TERM... Start ',CONVERT(varchar(19), GETDATE(), 120));
--:r D_PAYMENT_TERM.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_VENDOR_SITE... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_VENDOR_SITE.sql

PRINT CONCAT(CHAR(10),CHAR(13),'10_D_GL_HEADER... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 10_D_GL_HEADER.sql

PRINT CONCAT(CHAR(10),CHAR(13),'20_GL_Load_Balance_Fact... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 20_GL_Load_Balance_Fact.sql

PRINT CONCAT(CHAR(10),CHAR(13),'30_GL_Load_Lines_Fact... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r 30_GL_Load_Lines_Fact.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_AP_DISBURSEMENT_HEADER... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_AP_DISBURSEMENT_HEADER.sql

PRINT CONCAT(CHAR(10),CHAR(13),'D_AP_INVOICE_HEADER... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r D_AP_INVOICE_HEADER.sql

PRINT CONCAT(CHAR(10),CHAR(13),'F_AP_INVOICE_LINE_DISTRIBUTION... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r F_AP_INVOICE_LINE_DISTRIBUTION.sql

PRINT CONCAT(CHAR(10),CHAR(13),'F_AP_PAYMENTS... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r F_AP_PAYMENTS.sql

PRINT CONCAT(CHAR(10),CHAR(13),'F_AP_AGING_SNAPSHOT... Start ',CONVERT(varchar(19), GETDATE(), 120));
:r F_AP_AGING_SNAPSHOT.sql

 